### ISSUE TITLE
Shopify Serve Fails (This command ran with ID: 51317)

### ISSUE THREAD

**Issue by 90stareq** [Shopify/shopify-app-cli#1001]
# Issue summary

all of a sudden Shopify Serve is not working

## Expected behavior

should start the development server

## Actual behavior

Here is the error message:
`
\This command ran with ID: 51317
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        29: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/bin/shopify:32:in `<main>'
        28: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        27: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        26: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/bin/shopify:33:in `block in <main>'
        25: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/core/entry_point.rb:42:in `call'
        24: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/core/monorail.rb:32:in `log'
        23: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
        22: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/core/executor.rb:15:in `call'
        21: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        20: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        19: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        18: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        17: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        16: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        15: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        14: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        13: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-ui/lib/cli/ui.rb:172:in `log_output_to'
        12: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        11: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        10: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
         9: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
         8: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/command.rb:25:in `call'
         7: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/project_types/node/commands/serve.rb:15:in `call'
         6: from /usr/lib/ruby/2.7.0/forwardable.rb:235:in `start'
         5: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/tunnel.rb:66:in `start'
         4: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/tunnel.rb:162:in `start_ngrok'
         3: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/process_supervision.rb:60:in `start'
         2: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/process_supervision.rb:125:in `running?'
         1: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/process_supervision.rb:40:in `for_ident'
/var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/process_supervision.rb:40:in `Integer': can't convert nil into Integer (TypeError)
`

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: public
- Operating System: Ubuntu 20.0

**Comment by paulomarg** [comment]
Hi @90stareq, can you please confirm whether the file `~/.cache/shopify/sv/ngrok.pid` exists and that the user you're running `serve` with has read/write access to it? That will help us in debugging this issue.

If the file is there but is not accessible to the user, you could try deleting the `~/.cache/shopify/sv` folder or giving the user permission to it.

**Comment by 90stareq** [comment]
@paulomarg Thank You so much.
after deleting `~/.cache/shopify/sv/ngrok.pid` server started working again
