### ISSUE TITLE
Suggest preconditions be checked by CLI before proceeding with Rails app generation

### ISSUE THREAD

**Issue by keithrbennett** [Shopify/shopify-app-cli#1006]
**There are errors that are caught by utilities, generators, etc, called by the CLI. Perhaps the CLI could check for the most common of these errors before proceeding, possibly even adding a `-n` option or the like to test the preconditions without generating the app. This would save the developer time by a) accelerating the discovery of the error, and b) offering more information about resolving the error.**

This would be especially helpful for newcomers to the Shopify environment such as myself.

For example, the absence of the required environment variable `SHOPIFY_API_SECRET` (see image below) is an opportunity to explain _how_ they can obtain the secret, by outputting the help text and/or outputting a URL pointing to the specific online documentation page that contains this information.

![image](https://user-images.githubusercontent.com/28410/101841434-ea860080-3b13-11eb-8b8e-dbff6d73d908.png)

This issue is related to #1004.

## Steps to reproduce the problem

1. Run `shopify create rails` without `SHOPIFY_API_SECRET` specified in the environment.

## Specifications

- App type: rails
- Operating System: Kubuntu 20.04
- Shell: zsh
- Ruby version (ruby -v): 2.7.2p137

**Comment by andyw8** [comment]
This will be partially addressed in https://github.com/Shopify/shopify_app/pull/1144

**Comment by thecodepixi** [comment]
Closing stale issue that appears to be resolved by previous unlinked PRs. If this issue still persists, please feel free to open a new issue on the repo.
