### ISSUE TITLE
Issues with shopify cli during selection of app (Windows)

### ISSUE THREAD

**Issue by adra47** [Shopify/shopify-app-cli#1012]
# Issue summary

Similar to issue #971, but it happens when the cli asks To which app does this project belong to? (Navigate up with 'k' and down with 'j', press Enter to select, filter with 'f'

No matter what I press, k, j, or f the cli just chooses the first app on the list and doesn't navigate up or down.  The app I'm working on is in Node. I just updated to cli version 1.5, and I haven't used the cli very frequently, but in version 1.4 I didn't see this issue although it was behaving the same way when selecting a development store (it will just choose the first one on the list instead of navigating up or down)

While this is being worked on, if there is any workaround to this, or directions on how to downgrade to the previous version would be appreciated :) 

## Expected behavior

What do you think should happen?

Should navigate up and down according to instructions

## Actual behavior

What actually happens?
Should navigate up or down as the instructions indicate

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: Shopify Cli
- Operating System: Windows
- Shell:
- Ruby version (ruby -v): ruby 2.7.2p137

**Comment by rashedxyz** [comment]
Is there any update regarding this issue?

**Comment by mllemango** [comment]
We're working on a fix right now! Hope to see it integrated in the cli soon 🤞

**Comment by rashedxyz** [comment]
> We're working on a fix right now! Hope to see it integrated in the cli soon 🤞

Hi, would you please tell me the ETA of this fix?
