### ISSUE TITLE
Issues with logging into Shopify account through the CLI 

### ISSUE THREAD

**Issue by jazilzaim** [Shopify/shopify-app-cli#1017]
# Issue summary
After logging in of my account through the CLI, I get an error. 

`This command ran with ID: 35335
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
	43: from /usr/local/Cellar/shopify-cli/1.5.0/src/bin/shopify:32:in `<main>'
	42: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	41: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	40: from /usr/local/Cellar/shopify-cli/1.5.0/src/bin/shopify:33:in `block in <main>'
	39: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/core/entry_point.rb:42:in `call'
	38: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/core/monorail.rb:32:in `log'
	37: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
	36: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/core/executor.rb:15:in `call'
	35: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	34: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	33: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	32: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	31: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	30: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	29: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	28: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	27: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-ui/lib/cli/ui.rb:172:in `log_output_to'
	26: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	25: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	24: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	23: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
	22: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/commands/create.rb:8:in `call'
	21: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/command.rb:19:in `call'
	20: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/sub_command.rb:12:in `call'
	19: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/project_types/node/commands/create.rb:16:in `call'
	18: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/form.rb:13:in `ask'
	17: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/project_types/node/forms/create.rb:13:in `ask'
	16: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/task.rb:7:in `call'
	15: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/tasks/select_org_and_shop.rb:14:in `call'
	14: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/tasks/select_org_and_shop.rb:41:in `get_organization'
	13: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/tasks/select_org_and_shop.rb:30:in `organizations'
	12: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/partners_api/organizations.rb:6:in `fetch_all'
	11: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/partners_api.rb:48:in `query'
	10: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/partners_api.rb:63:in `authenticated_req'
	 9: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/partners_api.rb:49:in `block in query'
	 8: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/partners_api.rb:74:in `api_client'
	 7: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/partners_api.rb:80:in `access_token'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `get'
	 5: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/db.rb:87:in `get'
	 4: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/partners_api.rb:81:in `block in access_token'
	 3: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/partners_api.rb:93:in `authenticate'
	 2: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/oauth.rb:43:in `authenticate'
	 1: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/oauth.rb:148:in `request_exchange_token'
/usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/oauth.rb:169:in `post_token_request': Invalid 'subject_token' value: invalid (ShopifyCli::OAuth::Error)`

Write a short description of the issue here ↓
It is saying something about Oath and then says something about some issues with Ruby. Not sure what is happening.

## Expected behavior

What do you think should happen?
Should be able to confirm my login info and allow me to create the Shopify app through their CLI.

## Actual behavior

What actually happens?
I get an error.

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Specifications

- App type: Shopify app
- Operating System: macOS 
- Shell: zsh
- Ruby version (ruby -v): ruby 2.6.3p62

**Comment by EthTS** [comment]
I get the same Error as well , 

Operating System: Windows.

**Comment by jazilzaim** [comment]
> I get the same Error as well ,
> 
> Operating System: Windows.

I figured out the error. It is with your Auth. Got to clear cache from your browser. Re-log into Shopify and then it should be fixed. It is a cache issue with your browser.
