### ISSUE TITLE
Missing SHOPIFY_API_KEY

### ISSUE THREAD

**Issue by yehiasalam** [Shopify/shopify-app-cli#1018]
# Issue summary

Hi,

I generated the project using `shopify create rails` and now trying `serve`. I'm getting `Missing SHOPIFY_API_KEY`, however i can see the file `.env` in the project root with all the required keys:

```
SHOPIFY_API_KEY=xx
SHOPIFY_API_SECRET=xx
SHOP=xx
SCOPES=write_products,write_customers,write_draft_orders
HOST=https://xx.ngrok.io
```

## Expected behavior

`shopify serve` to launch normally.

## Actual behavior

```
PS C:\stage\charla\plugin-shopify> rails webpacker:install
rails aborted!
Missing SHOPIFY_API_KEY
C:/stage/charla/plugin-shopify/config/initializers/shopify_app.rb:3:in `block in <main>'
C:/stage/charla/plugin-shopify/config/initializers/shopify_app.rb:1:in `<main>'
C:/stage/charla/plugin-shopify/config/environment.rb:5:in `<main>'
Tasks: TOP => app:template => environment
(See full trace by running task with --trace)
```

## Specifications

- App type: Rails
- Operating System: Windows
- Shell: Windows Terminal
- Ruby version (ruby -v): 2.6.6

**Comment by yehiasalam** [comment]
I added the values manually in `shopify_app.rb`, not sure why it wasnt picking them up from `.env`

```
  config.application_name = "XXX"
  config.api_key = ENV.fetch('SHOPIFY_API_KEY', XXX').presence || raise('Missing SHOPIFY_API_KEY')
  config.secret = ENV.fetch('SHOPIFY_API_SECRET', 'XXX').presence || raise('Missing SHOPIFY_API_SECRET')
  config.old_secret = ""
  config.scope = "write_products,write_customers,write_draft_orders" # Consult this page for more scope options:
                      
```

**Comment by brtsos** [comment]
Look here: https://github.com/shopify/shopify_app

"You will need to load the ENV variables into your environment, you can do this with the dot-env gem or any other method you wish to."

Install this game and should work fine.

**Comment by yehiasalam** [comment]
works now thanks.

**Comment by fX13303** [comment]
Hi, I am getting the same problem but I can't figure out what happened. Please give me some tips to resolve it
