### ISSUE TITLE
Cloned Github Repo is not working

### ISSUE THREAD

**Issue by 90stareq** [Shopify/shopify-app-cli#1024]
# Issue summary

Hi
I am  new here at shopify. I have cloned https://github.com/Shopify/shopify-app-node this repo and used:- npm i ----> npm i ngrok ---> shopify serve  then this error message apears: "shopify serve was not found"

i followed the installation instruction  but didn't work.
how can i solve this issue

## Expected behavior

The app should run

## Actual behavior
 this error message apears: "shopify serve was not found"

## Steps to reproduce the problem

1. clone the repo
2. npm i
3. npm i ngrok
4. shopify serve

## Specifications

- App type: Public
- Operating System: w10
- Shell: vscode
- Ruby version (ruby -v): ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]

**Comment by 90stareq** [comment]
finally i findout the solution from another repo https://github.com/MathewsJoseph25/create-shopify-app

**Comment by tanema** [comment]
Have you installed the CLI? As you can see in the readme of that repo, it suggests running `shopify create`, the command from this cli.
