### ISSUE TITLE
My app stopped working when upgraded to version 1.5.0

### ISSUE THREAD

**Issue by nandezer** [Shopify/shopify-app-cli#1025]
# Issue summary

Write a short description of the issue here ↓
I upgraded the Shopify CLI  from 1.4.1 to 1.5.0 for my Windows following the instructions from [here](https://shopify.github.io/shopify-app-cli/getting-started/upgrade/).
When I executed `shopify serve` to run my app, the ngrok tunnel is created fine, the .env updated correctly, but when the server starts running I get the following error:
```
(node:10960) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tap' of undefined
┃     at C:\my_test_app\node_modules\@next\react-refresh-utils\ReactRefreshWebpackPlugin.js:100:61
┃     at SyncHook.eval (eval at create (C:\my_test_app\node_modules\next\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
┃     at SyncHook.lazyCompileHook (C:\my_test_app\node_modules\next\node_modules\tapable\lib\Hook.js:154:20)
┃     at Compiler.newCompilation (C:\my_test_app\node_modules\next\node_modules\webpack\lib\Compiler.js:631:26)
┃     at C:\my_test_app\node_modules\next\node_modules\webpack\lib\Compiler.js:667:29
┃     at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\my_test_app\node_modules\next\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
┃     at AsyncSeriesHook.lazyCompileHook (C:\my_test_app\node_modules\next\node_modules\tapable\lib\Hook.js:154:20)
┃     at Compiler.compile (C:\my_test_app\node_modules\next\node_modules\webpack\lib\Compiler.js:662:28)
┃     at C:\my_test_app\node_modules\next\node_modules\webpack\lib\Watching.js:77:18
┃     at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\my_test_app\node_modules\next\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
┃     at AsyncSeriesHook.lazyCompileHook (C:\my_test_app\node_modules\next\node_modules\tapable\lib\Hook.js:154:20)
┃     at Watching._go (C:\my_test_app\node_modules\next\node_modules\webpack\lib\Watching.js:41:32)
┃     at C:\my_test_app\node_modules\next\node_modules\webpack\lib\Watching.js:33:9
┃     at Compiler.readRecords (C:\my_test_app\node_modules\next\node_modules\webpack\lib\Compiler.js:529:11)
┃     at new Watching (C:\my_test_app\node_modules\next\node_modules\webpack\lib\Watching.js:30:17)
┃     at Compiler.watch (C:\my_test_app\node_modules\next\node_modules\webpack\lib\Compiler.js:244:10)
┃ (Use `node --trace-warnings ...` to show where the warning was created)
┃ (node:10960) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
┃ (node:10960) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
```

## Expected behavior

What do you think should happen?
The app should run in the server correctly, same as it did in the previous version.

## Actual behavior

What actually happens?
I get the TypeError mentioned above.

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. Create app as [this ](https://www.youtube.com/watch?v=PIXN032XJJ8&ab_channel=ShopifyDevs)tutorial shows with shopify app cli version 1.4.1
2. Upgrade the shopify version for Windows following [this](https://shopify.github.io/shopify-app-cli/getting-started/upgrade/) step.
3. Run `Shopify serve` in the command line.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type:
- Operating System: Windows 10
- Shell: command line
- Ruby version (ruby -v): ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]

**Comment by tanema** [comment]
This error is from your code, and not from the CLI. Updating the CLI does not change how your app is run.

**Comment by nandezer** [comment]
> This error is from your code, and not from the CLI. Updating the CLI does not change how your app is run.

I am new to Shopify CLI but I did not change anything on my code and it was running fine before the update.

**Comment by mkevinosullivan** [comment]
@nandezer, are you still having this issue, even with the latest version of the CLI (`1.8.0`)?

**Comment by nandezer** [comment]
Hey @mkevinosullivan, 

No I have sorted the problem, thanks! 
(Can't really recall what I did, as it was a while ago, but its all good thanks!)
