### ISSUE TITLE
Why am I getting a `root_path` error after creating Shopify App via Shopify CLI?

### ISSUE THREAD

**Issue by brandonironbirdlabscom** [Shopify/shopify-app-cli#1035]
# Issue summary

I am trying to get started with the Shopify CLI and am having problems getting a vanilla app working (i.e. haven't written any code yet, only trying to get things to connect up properly).

## Expected behavior

I have used the `shopify create`, `shopify serve`, and `shopify open` commands to make a simple rails app. I would expect to be able to visit the URL specified by the `shopify open` command in order to install and visit the app on my development store.

## Actual behavior

When visiting the URL specified by the `shopify open` command, I get the following error:

`undefined method 'root_path' for #<ActionDispatch::Routing::RoutesProxy:0x0000000124837528>`

Here is a screenshot:

<img width="1004" alt="Screen Shot 2021-01-16 at 4 31 51 PM" src="https://user-images.githubusercontent.com/72539554/104856947-20b06000-58ca-11eb-8df6-abe0c7ef8105.png">

## Specifications

- App type: Rails
- Rails version: 6.1.1
- Shopify CLI version: 1.5.0 (installed via Homebrew)
- Ruby version: 2.7.2

**Comment by paulomarg** [comment]
Hi @brandonironbirdlabscom, I believe this error is related to Rails 6.1, we're currently working on supporting that version in the repository.

Could you please try this again with Rails v < 6.1 to see the the problem is still present?

**Comment by brandonironbirdlabscom** [comment]
Thanks for your help, @paulomarg - I have downgraded to Rails 6.0.3.4, which allows me to install the app. However, I now receive an error saying that:

`"This app can’t load due to an issue with browser cookies. Try enabling cookies in your browser, switching to another browser, or contacting the developer to get support."`

I see this error on both Chrome and Safari.

Again, I haven't changed the code generated by the app. Any ideas (happy to open a new ticket if necessary).

Thanks for your help, @paulomarg!
<img width="956" alt="Screen Shot 2021-01-19 at 1 28 21 PM" src="https://user-images.githubusercontent.com/72539554/105095638-cb578880-5a5a-11eb-967d-c84b07f53f07.png">

**Comment by paulomarg** [comment]
It seems like there is currently an issue with fresh Rails apps - we'll investigate it!

**Comment by brandonironbirdlabscom** [comment]
Thanks, @paulomarg - I'll keep an eye out!

**Comment by paulomarg** [comment]
We've addressed the issue with new apps - could you please create a new one to see if it works now?

**Comment by brandonironbirdlabscom** [comment]
Awesome, @paulomarg - it appears to work using Rails 6.0.3.4. Thanks for your help!

Still seems to be having trouble with Rails 6.1.1 however.

**Comment by paulomarg** [comment]
Yes, that fixes the issue for Rails <= 6.0 - we're still working on supporting 6.1!

**Comment by brandonironbirdlabscom** [comment]
sounds good, @paulomarg - thanks again!
