### ISSUE TITLE
No able to install ngrok over Win 10

### ISSUE THREAD

**Issue by o-nkar** [Shopify/shopify-app-cli#1036]
# Issue summary
Once I am trying to run Shopify serve it try to install the ngrok, but end with an error
Write a short description of the issue here ↓

![image](https://user-images.githubusercontent.com/40701358/104890662-e0b6af00-5995-11eb-9e3d-be26aa4332ea.png)

## Specifications

- App type: node app
- Operating System: Windows 10 Home Single Language
  Version	20H2
  OS build	19042.746
  Experience	Windows Feature Experience Pack 120.2212.551.0

- Shell: cmd
- Ruby version (ruby -v): Ruby27-x64

**Comment by mllemango** [comment]
Hey @o-nkar, we've seen this issue before https://github.com/Shopify/shopify-app-cli/issues/1023, you can work around this by placing `ngrok.exe` in your folder "C:/Users/onkar/AppData/Local/shopify/".

**Comment by o-nkar** [comment]
Nopes, it doesn't work, when I place the ngrok.exe over this path, it outputs another error and doesn't work.
![image](https://user-images.githubusercontent.com/40701358/105350999-f2a48600-5c11-11eb-8f6a-8581fb13bbaf.png)

**Comment by mllemango** [comment]
Could you check that you have permissions on `ngrok.exe`? Either by going into file explorer "C:\Users\DELL\AppData\Local\shopify", or by calling `icacls C:\Users\DELL\AppData\Local\shopify\ngrok.exe`?

**Comment by o-nkar** [comment]
@mllemango  Yup, I think it is an issue to permission and now it works, thanks for your valuable inputs.
