### ISSUE TITLE
Installed 1.5.0. Getting This version of Shopify App CLI is no longer supported.

### ISSUE THREAD

**Issue by zinyosrim** [Shopify/shopify-app-cli#1042]
# Issue summary

I followed the installation instructions
When entering Shopify commands they don't execute.

## Expected behavior

Should execute CLI properly

## Actual behavior
`shopify version` on cmd prompt returns:
> ✗ This version of Shopify App CLI is no longer supported. You’ll need to migrate to the new CLI version to continue.
> 
>   Please visit this page for complete instructions:
>   https://shopify.github.io/shopify-app-cli/migrate/

## Steps to reproduce the problem

1. `brew uninstall shopify-cli`
1. `rm '/usr/local/bin/shopify'` 
1. `brew tap shopify/shopify`
2. `brew install shopify-cli`
3. `which shopify`  -> `/usr/local/bin/shopify`
4. `brew install shopify-cli` -> `Warning: shopify/shopify/shopify-cli 1.5.0 is already installed and up-to-date
To reinstall 1.5.0, run brew reinstall shopify-cli'`
4. `shopify version`  -> message above

## Specifications

- App type: -
- Operating System: Mac OS 11.0.1
- Shell: zsh
- Ruby version (ruby -v): ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]

**Comment by andyw8** [comment]
@zinyosrim could share the output of running this:

`ls -al /usr/local/bin/shopify`

**Comment by zinyosrim** [comment]
`lrwxr-xr-x  1 denizthemenace  admin  39 19 Jan 11:53 /usr/local/bin/shopify -> ../Cellar/shopify-cli/1.5.0/bin/shopify`

**Comment by andyw8** [comment]
Thanks, and could you also check what `where shopify` returns.

**Comment by zinyosrim** [comment]
strangely twice
/usr/local/bin/shopify
/usr/local/bin/shopify

**Comment by zinyosrim** [comment]
I ran `find / -name shopify 2>&- ` on my Mac.
@andyw8 do you see any possible conflicts here?
`/usr/local/bin/shopify
/usr/local/Homebrew/Library/Taps/shopify
/usr/local/Cellar/shopify-cli/1.5.0/bin/shopify
/usr/local/Cellar/shopify-cli/1.5.0/src/bin/shopify
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/shopify
/System/Volumes/Data/usr/local/bin/shopify
/System/Volumes/Data/usr/local/Homebrew/Library/Taps/shopify
/System/Volumes/Data/usr/local/Cellar/shopify-cli/1.5.0/bin/shopify
/System/Volumes/Data/usr/local/Cellar/shopify-cli/1.5.0/src/bin/shopify
/System/Volumes/Data/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/shopify
/System/Volumes/Data/Users/myuser/.rvm/gems/ruby-3.0.0/gems/shopify-cli-1.5.0/bin/shopify
/System/Volumes/Data/Users/myuser/Dev/shopify-demo-app-node-react/.git/logs/refs/remotes/origin/dependabot/npm_and_yarn/shopify
/System/Volumes/Data/Users/myuser/Dev/shopify-demo-app-node-react/.git/refs/remotes/origin/dependabot/npm_and_yarn/shopify
/System/Volumes/Data/Users/myuser/.pyenv/versions/3.6.0/lib/python3.6/site-packages/shopify
/Users/myuser/.rvm/gems/ruby-3.0.0/gems/shopify-cli-1.5.0/bin/shopify
/Users/myuser/Dev/shopify-demo-app-node-react/.git/logs/refs/remotes/origin/dependabot/npm_and_yarn/shopify
/Users/myuser/Dev/shopify-demo-app-node-react/.git/refs/remotes/origin/dependabot/npm_and_yarn/shopify
/Users/myuser/.pyenv/versions/3.6.0/lib/python3.6/site-packages/shopify`

**Comment by mkevinosullivan** [comment]
@zinyosrim What was the previous version of Shopify App CLI that you had installed?  Or, when did you last update the CLI?

**Comment by zinyosrim** [comment]
I installed the CLI at least 6 months ago but never used.
Then I wanted to use it yesterday.
I had ruby 2.4.2  or 2.2.4 (?), ran in some issue where I got a message that I need a higher version, then installed 3.0.0, But  had the same issue also with the ruby version I had before. 
Sorry for being not precise, but I spent hours on this and really don't remember my initial configuration in detail.  

So, no haven't tried 2.5+

**Comment by mkevinosullivan** [comment]
I tried with Ruby 3.0.0 just a moment ago and it seems fine.

Do you have a `.shopify-cli` directory in your home directory?  The error you're getting would indicate a very old installation (where we had a shell-based installation and runtime method).

**Comment by zinyosrim** [comment]
@mkevinosullivan  I don't have a `.shopify-cli` directory in my home directory. I also already followed the instructions previously. There is definitely nothing in my `.zshrc` and .`profile ` re. Shopify

**Comment by mkevinosullivan** [comment]
Very strange ... what output does the following command output?
```
$ ruby -e "IO.open(9)"
```

**Comment by zinyosrim** [comment]
no output at all ?!!

**Comment by mkevinosullivan** [comment]
Aha! K, that would imply that there's something in your environment that's got file descriptor 9 open, which is fine.  It just so happens that that was a file descriptor which the very old version of CLI (before v1.0.0) used to open to pass information between the shell and the CLI, and why we test it and print that message.

To help figure out what file might be at the other end of that file descriptor, what's the output of:
```
$ ruby -e 'system("lsof -p #{Process.pid}")'
```

In terms of a fix, we'll put our heads together internally, as there doesn't appear to an obvious fix to the test in the CLI.

**Comment by zinyosrim** [comment]
Here's the `ruby -e 'system("lsof -p #{Process.pid}")'` output
[ruby-e-output.txt](https://github.com/Shopify/shopify-app-cli/files/5851062/ruby-e-output.txt)

**Comment by mkevinosullivan** [comment]
It looks like you are using `Hyper` as your terminal, and that's what has file descriptor 9 open.  Can you try with the standard macOS Terminal application and see if you get the same error?

**Comment by zinyosrim** [comment]
never got to this point

<img width="697" alt="image" src="https://user-images.githubusercontent.com/17767575/105401081-0823ab00-5c26-11eb-8b4f-69538d064bd9.png">

**Comment by mkevinosullivan** [comment]
K, that's what it's supposed to do!

**Comment by zinyosrim** [comment]
Will there be any fix for the hyper issue? I guess many developers are using it as default terminal. I also tested with Iterm2, it was ok as well

**Comment by mkevinosullivan** [comment]
We'll likely remove that test that is preventing it working with Hyper - it's a question of timing.  There are small chunks of code (like that file descriptor test) that are to support the transition from beta version to v1.0.0 and beyond, and the intention is to remove them eventually.  The goal was to revisit the need and remove them after v1+ of the CLI had been in the wild for 12 months or so (i.e., around July 2021). We'll discuss internally if we can remove it sooner.
