### ISSUE TITLE
How to navigate Partners Account (keyboard navigation not working on Windows)

### ISSUE THREAD

**Issue by lavecart** [Shopify/shopify-app-cli#1044]
I want to build Shopify App with Nodejs and Reactjs using Shopify App Cli. I have three Shopify Partners Account. During Create project I can't select the Partners Account among three.

The command line tells to navigate with `k and j` but it not working for me in this step. Always selecting the first one. 

What's the problem?

**Comment by mllemango** [comment]
Hey @lavecart really sorry you're running into this problem! This is a known issue we're currently in the process of fixing. You're on windows cmd correct?

**Comment by andyw8** [comment]
Marking as duplicate of #1012
