### ISSUE TITLE
Using shopify-app-cli with existing app

### ISSUE THREAD

**Issue by hidr0** [Shopify/shopify-app-cli#1062]
I have used shopify-cli to create a prototype of the app I want to implement, but we noticed that we could use our existing app and integrate Shopify there and not support two apps.

How can I use `shopify serve` when developing in my old? It is very easy because it sets up ngrok and everything else.

When I write `shopify serve` it says "shopify serve was not found".

When I write `shopify connect` it says "You are not in a Shopify app project". I did not find a tutorial on how to create a Shopify app project in an existing Rails project.

**Comment by andyw8** [comment]
Hi @hidr0 

Which version of shopify-app-cli are you using?

And which version of Rails is your app built with?

**Comment by hidr0** [comment]
Hello @andyw8 

Shopify - 1.5.0
Rails - 6.0.3.4
Ruby - 2.6.5

**Comment by hidr0** [comment]
@tanema With you fix if I run `shopify connect` on my 'old rails app' I will be able to connect and work right?

**Comment by tanema** [comment]
Yes

**Comment by lukashambsch** [comment]
Why was this closed? I'm still seeing the same issue and it doesn't look like the PR with the fix was merged.

**Comment by wnm** [comment]
In the meantime, to fix it, create two files in your app root folder:

1) `.env` with these values:

```
SHOPIFY_API_KEY=#your api key#
SHOPIFY_API_SECRET=#your api secret#
SHOP=your-test-store.myshopify.com
SCOPES=read_customers,write_customers,read_orders,read_fulfillments,read_locales,read_shipping
```

2) `.shopify-cli.yml` with these values:

```
---
project_type: rails
organization_id: 123456

```

If those two files exists, you will no longer get the "You are not in a Shopify app project" warning.
