### ISSUE TITLE
Guideline for snake_case in options – should be kebab-case

### ISSUE THREAD

**Issue by kaelig** [Shopify/shopify-app-cli#1067]
# Issue summary

In https://github.com/Shopify/shopify-app-cli/wiki/UX-guidelines-for-commands, the guidelines promote naming options using `snake_case`, which breaks common command-line tool conventions. It should be `kebab-case`, like in other CLI tools.

## Expected behavior

> Option names should be plain English kebab-case. So the option to set an organization ID would be --organization-id. For example, in this command, the user sets the name and organization ID for the Node.js app:
>
> `$ shopify create node --name="My App" --organization-id=123456789`

We could go even further with guidance for naming that spans across commands and options:

- Command and option names should always be a single, lowercase word without spaces, hyphens, underscores, or other word delimiters
- If there is no obvious way to avoid having multiple words, separate with kebab-case

## Actual behavior

This rule seems to come from the fact we have an `organization_id` field in our databases. This is an implementation detail that shouldn't transpire in a CLI.

> Option names should be plain English snake_case. So the option to set an organization ID would be --organization_id. For example, in this command, the user sets the name and organization ID for the Node.js app:
>
> `$ shopify create node --name="My App" --organization_id=123456789`

Furthermore, the [Figma CLI UI Kit](https://www.figma.com/file/ZXIgM4wQpfRNjGaIArjWOgTD/CLI-UI-Kit?node-id=740%3A1127) uses camelCase (see screenshot below), which may add confusion and should be consistent with the guidelines in this repo's Wiki.

![Screen Shot 2021-02-04 at 1 39 08 PM](https://user-images.githubusercontent.com/85783/106958628-79676180-66ee-11eb-8c5c-7039936fac9e.png)

**Comment by kaelig** [comment]
One way this could be fixed on the `shopify` CLI without introducing breaking changes:

Add support for both snake_case and kebab-case flags wherever snake_case had already been introduced (for backwards compatibility), but only show snake-case in the CLI help and docs. And in the next major version of the tool, delete options and commands that were using snake_case.

**Comment by andyw8** [comment]
cc @gfscott @tiffanytse

**Comment by gfscott** [comment]
I agree kebab-case is the standard practice; I must admit I don't actually recall this decision being made one way or the other. @attaboy You had originally imported the guidelines into the Wiki — do you remember? Was there a prior document/design here?

The approach of aliasing and then deprecating makes sense to me. I think we should consider deprecating the Figma kit altogether. I don't think Figma's the right tool for CLI design and it's always going to be playing catch-up, leading to inconsistencies like this.

**Comment by attaboy** [comment]
I don't have a memory of a decision, tbh! When I wrote the wiki docs, I was trying to assemble a bunch of disparate docs and Figma files floating around, as well as discuss existing patterns — so if I did make any decision, it was likely based on what the CLI already does (which is decidedly snake_case!). 

I'm totally fine with changing the rule — I agree kebab-case is more conventional.

![image](https://user-images.githubusercontent.com/71433/107087900-2531af80-67ca-11eb-9357-3eb5131015fe.png)

**Comment by t6d** [comment]
As far as I know, we're using Ruby's standard `OptionParser`. Independent of its configuration, the parser supports both snake case and kebab case:

```ruby
require 'minitest/autorun'

def parse_with_snake_case_config(*argv)
  flags = {}
  parser = OptionParser.new do |p|
    p.on("--api_key=[NUMBER]") { flags[:api_key] = 2 }
  end
  parser.parse!(argv)
  flags
end

def parse_with_kebab_case_config(*argv)
  flags = {}
  parser = OptionParser.new do |p|
    p.on("--api-key=[NUMBER]") { flags[:api_key] = 2 }
  end
  parser.parse!(argv)
  flags
end

class SnakeCaseParserTest < Minitest::Test
  def test_accepts_snake_and_kebab_case
    parse_with_kebab_case_config("--api-key=2").tap do |flags|
      assert_equal 2, flags[:api_key]
    end

    parse_with_kebab_case_config("--api_key=2").tap do |flags|
      assert_equal 2, flags[:api_key]
    end
  end
end

class KebabParserTest < Minitest::Test
  def test_accepts_snake_and_kebab_case
    parse_with_snake_case_config("--api-key=2").tap do |flags|
      assert_equal 2, flags[:api_key]
    end

    parse_with_snake_case_config("--api_key=2").tap do |flags|
      assert_equal 2, flags[:api_key]
    end
  end
end
```
