### ISSUE TITLE
Simple app not working

### ISSUE THREAD

**Issue by SerhiDi** [Shopify/shopify-app-cli#1076]
I can't deploy my Shopify app. I can only use this app with `ngrok` on a Shopify development store.

I created a new simple shopify react/node app, to check it.

1. `npm run build` error

Steps to reproduce:
- run Shopify CLI command `shopify create`
- select `Node.js App`
- run `npm run build`

`shopify-app-node@1.0.0 build: `NEXT_TELEMETRY_DISABLED=1 next build``

2. Heroku error.
I tried to deploy this app

Steps to reproduce:
- run Shopify CLI command `shopify create`
- select `Node.js App`
- run command `heroku login`.
- run Shopify CLI command `shopify deploy heroku`

Heroku log (when I click `open app`):
`TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined`

**It is a simple app, without any changes from my side.** 

_P.S. Your tutorial don't have any information (Shopify has strange documentation), how a developer can get build folder and upload it to another hosting. I mean no information about Next.js deploy process_

**Comment by paulomarg** [comment]
Hi @SerhiDi, it seems that you haven't set up the environment variables from the `.env` file in your Heroku container.

If you add them to your Heroku app's settings, it should solve the `"key" argument must be of type string` error.

Hope this helps!

**Comment by thecodepixi** [comment]
Closing this issue as this seems to be a heroku issue, and there hasn't been any further discussion. Feel free to reopen if the issue still exists or originates from the cli generated code 😄

**Comment by SerhiDi** [comment]
Yes, it's Heroku issue.
I added environment variables inside **Heroku app - Settings.**
I think `shopify-app-cli` MUST contain information about this issue because Heroku uses as a deployment server.

Text from documentation - `Currently, the only option is Heroku`.
https://shopify.dev/tools/cli/reference/node-app
Very strange, only one option for deploy but the documentation does not contain information 'how I can do this deploy'

_P.S. All working correct on another hosting._
