### ISSUE TITLE
"shopify generate" still appears in the help command

### ISSUE THREAD

**Issue by Wilddata** [Shopify/shopify-app-cli#1089]
# Issue summary

Write a short description of the issue here ↓
"shopify generate" is still in the help command but doesn't work. No workaround provided by Shopify in the new docs

`
shopify -h
[...]
generate: Generate code in your Node project. Supports generating new billing API calls, new pages, or new webhooks.
  Usage: shopify generate [ billing | page | webhook ]`

## Expected behavior

Remove the command or fix it

## Actual behavior

`shopify generate billing
? How would you like to charge for your app? (You chose: recurring-billing)
⠋ Generating recurring-billing code ...
✗ Error                  
 `

## Specifications

- App type: NodeJS
- Operating System: Mac OS

**Comment by mkevinosullivan** [comment]
Thanks @Wilddata - there is a new version of the CLI command released (`v1.6.0`) that removes the `generate` command [v1.6.0 changelog entry](https://github.com/Shopify/shopify-app-cli/blob/master/CHANGELOG.md#version-160)

**Comment by paulomarg** [comment]
Just wanted to add that for now you can still run the `generate` command, but it will only produce a list of useful resources to achieve the functions it used to provide.

**Comment by Wilddata** [comment]
I appreciate the very fast response.
My shopify version was stuck to 1.5 for some reasons
