### ISSUE TITLE
1.6.0 - no longer able to set accessMode to offline

### ISSUE THREAD

**Issue by konrain** [Shopify/shopify-app-cli#1092]
# Issue summary

the new api does not seem to have the option to set the accessMode = "offline"

**Comment by paulomarg** [comment]
Hi @konrain, thanks for reporting this, but we'll need some information to be able to look into your issue. Could please let us know:
- Which type of app you're using (and if it is a new app)
- The version of Ruby / Rails or Node you're using
- What errors you are seeing
- What steps trigger those errors

Thanks!

**Comment by konrain** [comment]
@paarthmadan thanks for the response. there are no errors, before 1.6.0 we were able to do:

``` javascript
    createShopifyAuth({
      apiKey: SHOPIFY_API_KEY,
      secret: SHOPIFY_API_SECRET,
      scopes: [SCOPES],
      accessMode: "offline",  <--- here
      async afterAuth(ctx) {
      ...
    }
```
That does not seem possible with the new release, perhaps there is a different way of doing it but I looked through the docs and couldn't find anything mentioning this. 

Its not possible to get a storefront access token when accessMode is "online" which is the default for node apps [contrary to what the docs say](https://shopify.dev/concepts/about-apis/authentication#offline-access)

**Comment by paulomarg** [comment]
The node app should still support the `accessMode` param, but it may indeed be failing with the `'offline'` value. We'll look into it!

**Comment by konrain** [comment]
@paulomarg Oh it looks like its working, was a bit confused with the new API. My apologies!
