### ISSUE TITLE
shopify serve command not found

### ISSUE THREAD

**Issue by SajanBasnet** [Shopify/shopify-app-cli#1098]
# Issue summary

I installied the shopify-app-cli with "gem install shopify-cli" and created the rails app successfully with shopify create rails  
But when I tried to start the local development server it shows 
shopify serve was not found

![Screenshot from 2021-03-04 21-05-11](https://user-images.githubusercontent.com/68499928/109986782-2b19a280-7d2e-11eb-93e9-4f91f3ac1195.png)

## Expected behavior
Should start the local development server.

## Specifications

- App type: Rails app
- Operating System: Ubuntu 20.04.2 LTS
- Shell:zsh
- Ruby version (ruby -v):2.7.1

**Comment by mllemango** [comment]
Hey @SajanBasnet, it looks like you need to `cd` into your newly created rails app first and then try `shopify serve`!

**Comment by mllemango** [comment]
It looks like the `shopify create rails` command did not complete properly then, could you paste the output of the create command?

**Comment by Rojal17** [comment]
@milakoeva that may be a reason i guess 
![Screenshot from 2021-03-05 00-08-37](https://user-images.githubusercontent.com/54588757/110011006-07168b00-7d47-11eb-9976-f7abeadc81b4.png)
shopify_app gem icouldn't be installed cause of the rails version being greater than 6.1

Is there a way I could specify the rails version with "shopify create rails" ?

**Comment by SajanBasnet** [comment]
@milakoeva that may be a reason i guess 
![Screenshot from 2021-03-05 00-08-37](https://user-images.githubusercontent.com/54588757/110011006-07168b00-7d47-11eb-9976-f7abeadc81b4.png)
shopify_app gem couldn't be installed cause of the rails version being greater than 6.1

Is there a way I could specify the rails version with "shopify create rails" ?

**Comment by mllemango** [comment]
The cli will check if you have rails installed, if it's greater than 6.1, it should install 6.0.x.x. I'm not able to reproduce this error on my end :/ 
Did you install rails before using `shopify create rails`? 
Also whats the output of `gem env`

**Comment by SajanBasnet** [comment]
$gem env
![Screenshot from 2021-03-05 00-19-52](https://user-images.githubusercontent.com/68499928/110013029-3e863700-7d49-11eb-8aea-54cf42d81314.png)

**Comment by SajanBasnet** [comment]
This worked for me : 

Uninstalling the rails and railties with version greater than 6.1
recreating a new rails app 
shopify serve

**Comment by mllemango** [comment]
Great to hear you got this working! We'll look into ways to prevent this moving forward.
