### ISSUE TITLE
Official Apollo React component support ended in March 2020, they recommend hooks instead

### ISSUE THREAD

**Issue by zinyosrim** [Shopify/shopify-app-cli#1099]
# Issue summary

I've started building a new Shopify app and I was surprised to read that Apollo recommends the useQuery hook and 
 the react component [support ended in March 2020](https://www.apollographql.com/docs/react/api/react/components/). 

Is there a migration guide available?

Zin

**Comment by paulomarg** [comment]
Hi @zinyosrim, thanks for reporting this. We'll look into refactoring the Node app to use `@apollo-client` to bring it up to date.

I'm closing this issue so we can track it under https://github.com/Shopify/shopify-app-node/issues/555.
