### ISSUE TITLE
1.6.0 - Deploy is no longer functioning

### ISSUE THREAD

**Issue by yixe** [Shopify/shopify-app-cli#1106]
# Issue summary

deployment is not functioning in 1.6.0 even with a newly created shopify app with no modifications. Heroku outputs their typical "Application error" page

## Actual behavior

Heroku logs output
```
npm ERR! shopify-app-node@1.0.0 start: `cross-env NODE_ENV=production node ./server/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shopify-app-node@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2021-03-08T03_54_05_830Z-debug.log

at=error code=H10 desc="App crashed" method=GET path="/" host=infinite-everglades-54512.herokuapp.com request_id=775cca92-9d52-4d83-bace-375ffb8f718b fwd="144.224.67.226" dyno= connect= service= status=503 bytes= protocol=https
```

## Steps to reproduce the problem

1. shopify create (node)
2. shopify deploy heroku

## Specifications

- App type: Node
- Operating System: Mac
- Shell: Zsh

**Comment by paulomarg** [comment]
Hi @yixe, this type of issue usually occurs when your Heroku app doesn't have the right environment variables set. If you go to your app, **Settings** -> **Config Vars**, and set up the same values you have in your local `.env` file, your app should start working!

**Comment by yixe** [comment]
Thanks for the tip! @pauldowman

For anyone searching this in the future: After many trial and error what ended up fixing it was removing all other redirects from shopify except the one from heroku. If localhost or ngrok is listed you may run into this problem.
