### ISSUE TITLE
"System call failed: npm run dev" when i run shopify serve.

### ISSUE THREAD

**Issue by jfroome** [Shopify/shopify-app-cli#1110]
# Issue summary

Write a short description of the issue here ↓
project was working a couple days ago, I think something has updated and messed it up. 

![image](https://user-images.githubusercontent.com/23224601/110402066-b655a980-8048-11eb-9a1c-f5310a53de18.png)

## Expected behavior

What do you think should happen?
should run correctly

## Actual behavior

What actually happens?

<details>
  ┏━━ Running server... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ┃ '"node"' is not recognized as an internal or external command,
  ┃ operable program or batch file.
  ┃ '"node"' is not recognized as an internal or external command,
  ┃ operable program or batch file.
  ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0.03s) ━━━
  X System call failed: npm run dev
</details>

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. install an app
1. >shopify serve
1. error shows

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: 
- Operating System: windows 10
- Shell: visual studio code / powershell same behavior
- Ruby version (ruby -v): ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]

**Comment by cnscorpions** [comment]
@jfroome For me, it is "npm is not recognized ...." blabla. And I add "C:\Program Files\nodejs" in both user and system environment path variables. It does not work 😂

Env:
win10
NVM 1.1.9
Node v17.5.0
Npm 8.4.1
