### ISSUE TITLE
UX for how devs share apps or scaffolding tasks

### ISSUE THREAD

**Issue by nwtn** [Shopify/shopify-app-cli#114]
# Issue summary

How does handoff and sharing work?

If I make a PHP scaffold and need to share that with another partner, how do I do that?

More from Dave

1. app dev transfers app to someone else to work on (new team, or someone on same team). will the new dev be able to install shopify cli and start using it? i think this scenario is fine and doesn’t need work
2. same scenario, but the app dev has built a custom php app scaffolder that they’ve integrated into shopify app cli and used this to scaffold their app. new dev needs this php thing. what’s the process for sharing here? create a fork? create a branch? have some sort of plugin system?
3. same scenario as 2, but not sharing an app. dev who created php scaffold wants to share it with another dev to start a new project.

**Comment by tanema** [comment]
I think this is a large effort that will eventually be tackled if appropriate by our plugin system
