### ISSUE TITLE
Cannot Load Any Page other than Index

### ISSUE THREAD

**Issue by brandonironbirdlabscom** [Shopify/shopify-app-cli#1145]
# Issue summary

I am trying to add a second page to my app, but the page redirects and ends up not loading.

I have done the following:
- created a new file called "annotated-layout.js" within the pages folder
- I have properly exported the page using `export default AnnotatedLayout;`
- I have updated the embedded app's navigation bar to include a menu item directing to {{NGROK_URL}}/annotated-layout

## Expected behavior

The annotated-layout page should load properly.

## Actual behavior

The page loads/redirects between the NGROK URL and my Test Store Admin panel (where I have installed the app). I eventually receive a Shopify error saying that:

"This app can’t load due to an issue with browser cookies. Try enabling cookies in your browser, switching to another browser, or contacting the developer to get support."

## Specifications

- App type: Node
- Shopify CLI version: 1.7.1

**Comment by brandonironbirdlabscom** [comment]
It might be worth mentioning that I can properly load the page if I set `forceRedirect` to `false` in the _app.js file.

Please see image below (this time using a page called "dashboard")

<img width="1078" alt="Screen Shot 2021-03-30 at 9 18 07 PM" src="https://user-images.githubusercontent.com/72539554/113105932-dc7cee00-919d-11eb-9778-6255d679c43b.png">

**Comment by ScottJr** [comment]
@pauldowman - Thanks for the support. I've followed the guide you are referring (AppBridge) to and I'm still getting the issue specified. I'm still getting redirected.  I'm also getting the [error raised here](https://github.com/Shopify/shopify-app-cli/issues/1047)

```┃   Error: aborted
┃       at connResetException (node:internal/errors:631:14)
┃       at abortIncoming (node:_http_server:578:17)
┃       at socketOnEnd (node:_http_server:593:5)
┃       at Socket.emit (node:events:388:22)
┃       at endReadableNT (node:internal/streams/readable:1305:12)
┃       at processTicksAndRejections (node:internal/process/task_queues:80:21)```

I've done multiple clean installs with the CLI Node app and nothing other than index works.

**Comment by ScottJr** [comment]
Is this going to be re-opened or is this addressed somewhere else??
