### ISSUE TITLE
Address already in use :::8081

### ISSUE THREAD

**Issue by KarovInal** [Shopify/shopify-app-cli#1151]
# Issue summary
When I run the command `shopify serve`, I get an error that the port :8081 is busy. It's happening because I have McAfee, which takes 8081 port.
I tried manually edit the port in server.js file, but I have another problem with 
<details>
ngrok gateway error
The server returned an invalid or incomplete HTTP response.
</details>

## Expected behavior
I want to edit the port through `shopify serve` command. Like `shopify serve --port=3001`

## Actual behavior
If I using default port 8081, I have this error in termnal:
<details>
events.js:174
┃       throw er; // Unhandled 'error' event
┃       ^
┃
┃ Error: listen EADDRINUSE: address already in use :::8081
┃     at Server.setupListenHandle [as _listen2] (net.js:1280:14)
┃     at listenInCluster (net.js:1328:12)
┃     at Server.listen (net.js:1415:7)
┃     at Application.listen (/Users/inal.karov/products/stories-test-app/node_modules/koa/lib/application.js:82:19)
┃     at _callee7$ (/Users/inal.karov/products/stories-test-app/server/server.js:105:10)
┃     at tryCatch (/Users/inal.karov/products/stories-test-app/node_modules/@babel/polyfill/node_modules/regenerator-runtime/runtime.js:63:40)
┃     at Generator.invoke [as _invoke] (/Users/inal.karov/products/stories-test-app/node_modules/@babel/polyfill/node_modules/regenerator-runtime/runtime.js:293:22)
┃     at Generator.next (/Users/inal.karov/products/stories-test-app/node_modules/@babel/polyfill/node_modules/regenerator-runtime/runtime.js:118:21)
┃     at asyncGeneratorStep (/Users/inal.karov/products/stories-test-app/server/server.js:27:103)
┃     at _next (/Users/inal.karov/products/stories-test-app/server/server.js:29:194)
┃     at /Users/inal.karov/products/stories-test-app/server/server.js:29:364
┃     at new Promise (<anonymous>)
┃     at /Users/inal.karov/products/stories-test-app/server/server.js:29:97
┃ Emitted 'error' event at:
┃     at emitErrorNT (net.js:1307:8)
┃     at process._tickCallback (internal/process/next_tick.js:63:19)
┃ [nodemon] app crashed - waiting for file changes before starting...
</details>

## Specifications

- App type: public
- Operating System: MacOS Catalina
- Shell: zsh
- Ruby version (ruby -v): ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]

**Comment by paulomarg** [comment]
Hi @KarovInal, thanks for reporting this. Unfortunately, at the moment the CLI doesn't support using a custom port for the `serve` command, but we will look into adding that flag.

Meanwhile, you can work around this by running the application manually:
1. Run ngrok on a custom port: `~/.cache/shopify/ngrok http <port>`
2. Update your app's URL and OAuth callback URL in your Shopify Partners dashboard
3. Start your app by running this in your app's folder: `PORT=<port> bin/rails server`

**Comment by liyang001** [comment]
You can try changing the port in the file ~/shopify-cli-1.13.1\lib\shopify-cli\tunnel.rb to your port
