### ISSUE TITLE
Error on "shopify create node"

### ISSUE THREAD

**Issue by ronneysingh** [Shopify/shopify-app-cli#1171]
# Issue summary
Getting an error while running command "shopify create node"

## Expected behavior

It should create a new App in my partner's account

## Actual behavior
<details>

C:\>gem install shopify-cli
Fetching shopify-cli-1.8.0.gem
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
Successfully installed shopify-cli-1.8.0
Parsing documentation for shopify-cli-1.8.0
Installing ri documentation for shopify-cli-1.8.0
Done installing documentation for shopify-cli after 20 seconds
1 gem installed

C:\>shopify version
? Would you like to enable anonymous usage reporting?
If you select “Yes”, we’ll collect data about which commands you use and which errors you encounter.
Sharing this anonymous data helps Shopify improve this tool.
? Would you like to enable anonymous usage reporting?
If you select “Yes”, we’ll collect data about which commands you use and which errors you encounter.
Sharing this anonymous data helps Shopify improve this tool.
 (You chose: no)
1.8.0

C:\>cd C:\Shopify\Apps

C:\Shopify\Apps>shopify help
Use shopify help <command> to display detailed information about a specific command.

Available core commands:

connect: Connect (or re-connect) an existing project to a Shopify partner organization and/or a store. Creates or updates the .env file, and creates the .shopify-cli.yml file.
  Usage: shopify connect

create: Create a new project.
  Usage: shopify create [ node | rails ]

logout: Log out of a currently authenticated partner organization and store, or clear invalid credentials
  Usage: shopify logout

version: Prints version number.
  Usage: shopify version

C:\Shopify\Apps>shopify create node
? App name
> TestApp1
? What type of app are you building? (Navigate up with 'k' and down with 'j', press Enter to select, fil
? What type of app are you building? (You chose: Public: An app built for a wide merchant audience.)
i Authentication required. Login to the URL below with your Shopify Partners account credentials to continue.
Please open this URL in your browser:
https://accounts.shopify.com/oauth/authorize?client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&redirect_uri=http%3A%2F%2F127.0.0.1%3A3456&state=37768e7095011e70865a6cf6fe6d0cf5a8604ecb242637911061d207a90e&response_type=code&code_challenge=OUzmUn-_NMXbqL0dqDBHL2IpU_YGHr1lKwQxietqcIA&code_challenge_method=S256
This command ran with ID: 85203
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        50: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/bin/shopify:32:in `<main>'
        49: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        48: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        47: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/bin/shopify:33:in `block in <main>'
        46: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/core/entry_point.rb:42:in `call'
        45: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/core/monorail.rb:20:in `log'
        44: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
        43: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/core/executor.rb:15:in `call'
        42: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        41: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        40: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        39: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        38: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        37: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/commands/create.rb:8:in `call'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/command.rb:19:in `call'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/sub_command.rb:12:in `call'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/project_types/node/commands/create.rb:18:in `call'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/form.rb:13:in `ask'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/project_types/node/forms/create.rb:13:in `ask'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/task.rb:7:in `call'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/tasks/select_org_and_shop.rb:14:in `call'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/tasks/select_org_and_shop.rb:42:in `get_organization'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/tasks/select_org_and_shop.rb:31:in `organizations'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/partners_api/organizations.rb:6:in `fetch_all'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/partners_api.rb:48:in `query'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/partners_api.rb:63:in `authenticated_req'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/partners_api.rb:49:in `block in query'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/api.rb:26:in `query'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/api.rb:69:in `request'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/api.rb:46:in `block in request'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/api.rb:96:in `default_headers'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/api.rb:91:in `current_sha'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/git.rb:24:in `sha'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/git.rb:118:in `rev_parse'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/git.rb:112:in `exec'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/context.rb:404:in `capture3'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/system.rb:90:in `capture3'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/system.rb:194:in `delegate_open3'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:281:in `capture3'
         2: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:101:in `popen3'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `spawn': No such file or directory - git (Errno::ENOENT)

C:\Shopify\Apps>shopify create node
? App name
> Test App1
? What type of app are you building? (Navigate up with 'k' and down with 'j', press Enter to select, fil
? What type of app are you building? (You chose: Public: An app built for a wide merchant audience.)
This command ran with ID: 19179
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        50: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/bin/shopify:32:in `<main>'
        49: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        48: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        47: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/bin/shopify:33:in `block in <main>'
        46: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/core/entry_point.rb:42:in `call'
        45: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/core/monorail.rb:20:in `log'
        44: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
        43: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/core/executor.rb:15:in `call'
        42: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        41: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        40: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        39: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        38: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        37: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/commands/create.rb:8:in `call'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/command.rb:19:in `call'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/sub_command.rb:12:in `call'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/project_types/node/commands/create.rb:18:in `call'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/form.rb:13:in `ask'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/project_types/node/forms/create.rb:13:in `ask'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/task.rb:7:in `call'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/tasks/select_org_and_shop.rb:14:in `call'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/tasks/select_org_and_shop.rb:42:in `get_organization'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/tasks/select_org_and_shop.rb:31:in `organizations'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/partners_api/organizations.rb:6:in `fetch_all'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/partners_api.rb:48:in `query'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/partners_api.rb:63:in `authenticated_req'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/partners_api.rb:49:in `block in query'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/api.rb:26:in `query'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/api.rb:69:in `request'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/api.rb:46:in `block in request'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/api.rb:96:in `default_headers'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/api.rb:91:in `current_sha'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/git.rb:24:in `sha'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/git.rb:118:in `rev_parse'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/git.rb:112:in `exec'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/context.rb:404:in `capture3'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/system.rb:90:in `capture3'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/system.rb:194:in `delegate_open3'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:281:in `capture3'
         2: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:101:in `popen3'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `spawn': No such file or directory - git (Errno::ENOENT)
</details>

## Steps to reproduce the problem

1. Run "shopify create node" command

**Comment by mllemango** [comment]
hey @ronneysingh, could you make sure you have git installed?

**Comment by ronneysingh** [comment]
Hi @mllemango , I also suspected that there is an issue with Git.
