### ISSUE TITLE
Generate page doesn't work

### ISSUE THREAD

**Issue by thomasjthomasj** [Shopify/shopify-app-cli#1176]
# Issue summary

On Ubuntu running within WSL the command `shopify generate page test-page` errors. It looks like it's trying to access a file that doesn't exist, the file being `/var/lib/gems/2.7.0/gems/shopify-cli-1.8.0/lib/project_types/node/commands/generate/page`, but there is only `/var/lib/gems/2.7.0/gems/shopify-cli-1.8.0/lib/project_types/node/commands/generate.rb`

## Expected behavior

Running the command would create a new page within the Shopify app

## Actual behavior

I get this error:

<details>

```

$ shopify generate page test-page
[Note] You cannot use gems with Shopify App CLI.
[LoadError] cannot load such file -- /var/lib/gems/2.7.0/gems/shopify-cli-1.8.0/lib/project_types/node/commands/generate/page
       They are disabled.
       Please don't modify the CLI locally.
       If you would like to contribute to the CLI project, please refer to
       https://github.com/Shopify/shopify-app-cli/blob/master/.github/CONTRIBUTING.md

Traceback (most recent call last):
        13: from /var/lib/gems/2.7.0/gems/shopify-cli-1.8.0/bin/shopify:32:in `<main>'
        12: from /var/lib/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        11: from /var/lib/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        10: from /var/lib/gems/2.7.0/gems/shopify-cli-1.8.0/bin/shopify:33:in `block in <main>'
         9: from /var/lib/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/core/entry_point.rb:42:in `call'
         8: from /var/lib/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/core/monorail.rb:25:in `log'
         7: from /var/lib/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/command_registry.rb:41:in `lookup_command'
         6: from /var/lib/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/command_registry.rb:64:in `resolve_command'
         5: from /var/lib/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/command_registry.rb:70:in `resolve_global_command'
         4: from /var/lib/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/command_registry.rb:87:in `resolve_class'
         3: from /var/lib/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/command.rb:35:in `block in subcommand'
         2: from /var/lib/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/command.rb:35:in `const_get'
         1: from /var/lib/gems/2.7.0/gems/shopify-cli-1.8.0/bin/shopify:9:in `require'
/var/lib/gems/2.7.0/gems/shopify-cli-1.8.0/bin/shopify:9:in `require': cannot load such file -- /var/lib/gems/2.7.0/gems/shopify-cli-1.8.0/lib/project_types/node/commands/generate/page (LoadError)
```

</details>

## Steps to reproduce the problem

1. Install <a href="https://github.com/Shopify/shopify-app-cli/releases/tag/v1.8.0">shopify-cli-1.8.0</a> on Ubuntu from the .deb file
1. Create a new project with `shopify create`
1. Run `shopify generate page test-page`

## Specifications

- App type: Custom
- Operating System: Ubuntu 20.04 running in WSL2
- Shell: bash
- Ruby version (ruby -v): 2.7.0 and 3.0.0

**Comment by thomasjthomasj** [comment]
I have now noticed this is no longer supported. I'm going to leave the issue open with a suggestion to make the error message you get when trying to use this command clearer

**Comment by thomasjthomasj** [comment]
Thanks @mkevinosullivan - is there an alternative to `generate page` or is this feature just not there anymore?

**Comment by mkevinosullivan** [comment]
It's not there anymore - `generate page` assumed a very specific folder structure (from a specific cloned repo) and since the CLI can also be used with Node apps not originally created with the CLI, `generate page` could create a file/folder structure not intended by the developer, introducing issues unnecessarily.
