### ISSUE TITLE
Provide more user feedback on `update` process

### ISSUE THREAD

**Issue by gfscott** [Shopify/shopify-app-cli#118]
# Issue summary

`shopify update` currently provides very little information to the user. It also doesn’t transparently distinguish whether an update actually occurred.

Below, the first `update` command actually pulled an updated version; the second one didn't. But both produce similar output, leading to ambiguity for the user.
<img width="447" alt="Screen Shot 2019-06-14 at 15 31 02" src="https://user-images.githubusercontent.com/547470/59533659-2eb22980-8eba-11e9-9e0d-d4ae7bd0d2c0.png">

## Expected behavior

It would be helpful to provide more output that describes what’s happening. This would give users more confidence that the update has succeeded as intended and reduce potential confusion.

## Specifications

- Operating System: MacOS
- Shell: bash
- Ruby version (ruby -v): 2.3.7p456

**Comment by paulomarg** [comment]
Since the `update` command is no longer supported, we don't need to worry about this issue!
