### ISSUE TITLE
Shopify connect doesn't show all of my partner organization

### ISSUE THREAD

**Issue by ShirasuGyoza** [Shopify/shopify-app-cli#1190]
# Issue summary
I have three parnter accounts and want to connect one of these to my app using app cli. But the list shows only two accounts when I run `shopify serve`.

## Expected behavior
Show all(three) my partner accounts when I run `shopify connect`, and connect third account.

## Actual behavior
Show two of three my partner accounts of question of `To which partner organization does this project belong?` when I run `shopify connect`.

## Steps to reproduce the problem

1. Create Shopify partner account for my private project.
1. Test using app cli <- successfully connected and served test app.
1. Joined organization partner dashboad as a staff account using same account as 1.
2. Run `shopify connect` to connect my organization partner, but not appear on the list.

## Specifications
- App type: Public app
- cli version: 1.8.0
- Operating System: Mac OS Big Sur
- Shell: zsh
- Ruby version (ruby -v): 3.0.1

**Comment by ShirasuGyoza** [comment]
Solved this issue by downgrading cil and ruby to:
- ruby 2.6.3,
- Shopify 1.1.2
I think it's a problem of latest version of cli.

**Comment by paulomarg** [comment]
Thanks for letting us know @ShirasuGyoza, we'll investigate this!

**Comment by tanema** [comment]
Okay, this should be resolved now. There were permission restrictions that changed a while ago that made querying orgs a lot stricter and so that only org owners would see them. This has been resolved now.

**Comment by ShirasuGyoza** [comment]
@tanema 
Thank you for updating, I've tried `shopify connect` command and it now showed up all organizations!!
