### ISSUE TITLE
Shopify CLI page size is too high?

### ISSUE THREAD

**Issue by zloz** [Shopify/shopify-app-cli#1254]
# Issue summary

Write a short description of the issue here ↓

I created a simple node app from shopify cli, no personal code added, just plain barebone app created by shopify cli, on serving this app in my dev store, I get heavy page sizes causing time delay to load page (page size is bloated up time to render this empty page is 40~secs and page size is 5.78mb), this increases the development time immensely. 

![Screenshot 2021-05-23 at 11 58 41 AM](https://user-images.githubusercontent.com/4331831/119313478-3c20e280-bc91-11eb-9eb8-290ecb63318a.png)

There is no documentation on any configuration changes that we need to tweek.

I downloaded these heavy page files to check what is in it, the webpack is somehow bundling all my components in my app js and index js files (repeatedly), its bundling all this unnecessary files causing each page file to bloat up, it would be really helpful if someone can point out the webpack configurations I need to update, to change this behaviour.

## Expected behavior

What do you think should happen?

page size should not be this big in dev env.

## Steps to reproduce the problem

1. create a sample node based project
1. start serving the project in your partners store
1. see the page size for app.js and index.js

## Specifications

- App version: 1.9.1

**Comment by mllemango** [comment]
Hey @zloz, thanks for raising this with us. This is good insight into the known issue with our Next app loading very slowly. This is something we are currently investigating and we’ll update when we can. I'm going to close this issue in favour of tracking with this one https://github.com/Shopify/shopify-app-node/issues/584

**Comment by towfiqi** [comment]
Polaris is huge. Just removed Polaris and shaved 12mb!!
You guys should really focus on performance. And advocate lighter app and faster page load. 
Since lots of merchants are using apps through Mobile devices the apps made with Shopify cli would be very slow.
