### ISSUE TITLE
Add more specific help for `generate` subcommands

### ISSUE THREAD

**Issue by gfscott** [Shopify/shopify-app-cli#132]
# Issue summary
Inline help text for `generate` commands doesn't produce a specific enough result, but merely repeats the same help text for each subcommand.

## Expected behavior

Running `shopify help generate billing` should produce extended help text specifically related only to  the `billing` subcommand. The same would ideally be true for the `page` and `webhook` subcommands.

## Actual behavior

Running `shopify help generate page`, `shopify help generate billing` or `shopify help generate webhook` all return the extended help text for `shopify help generate`.

### Three different cries for help, three identical messages:

<img width="1792" alt="Screen Shot 2019-06-17 at 10 58 17" src="https://user-images.githubusercontent.com/547470/59614546-fa737e80-90ee-11e9-98d6-5d94764789ba.png">
<img width="1792" alt="Screen Shot 2019-06-17 at 10 58 27" src="https://user-images.githubusercontent.com/547470/59614547-fb0c1500-90ee-11e9-80f0-f644f3ca25c3.png">
<img width="1792" alt="Screen Shot 2019-06-17 at 10 58 34" src="https://user-images.githubusercontent.com/547470/59614548-fb0c1500-90ee-11e9-9b7e-04b2b31d9ecf.png">

**Comment by tanema** [comment]
This has been fixed now
