### ISSUE TITLE
Detect ngrok running and handle error for create command

### ISSUE THREAD

**Issue by davekilljoy** [Shopify/shopify-app-cli#139]
When ngork is already running and we try to run the create project command, the task fails immediately.

Ideally we should prompt the user that ngrok may be running, and ask them if they would like to kill all ngrok process'. If no, then error out and tell the user the command cant execut if ngork tunnel is running.

**Comment by ReinisL** [comment]
@davekilljoy I think it would be great to also add a feature to quickly reset ngrok tunnel from Shopify-cli when the tunnel expires or even better if it could automatically check if it's still active.
