### ISSUE TITLE
Check if you're in a Shopify project first

### ISSUE THREAD

**Issue by davekilljoy** [Shopify/shopify-app-cli#146]
# Issue summary
We should be checking if we're in a Shopify project before any other process' kick off

## Expected behavior
I get the error first, instead of after a few success messages

## Actual behavior
You are not in a shopify project<img width="580" alt="Screen Shot 2019-06-18 at 9 27 12 AM" src="https://user-images.githubusercontent.com/1523373/59688283-5e5b7d00-91ab-11e9-9af6-9f510a47ebd1.png">

Running `shopify serve` gives me success messages first for the ngrok tunnel and the tip on how to open the page, then errors out.

**Comment by djjimba** [comment]
I get the same error with the Node.js setup.

**Comment by LukaszWiktor** [comment]
Same here :hand:

**Comment by LukaszWiktor** [comment]
Found a workaround. Create a file `.shopify-cli.yml` inside the app project directory. The yaml file has to include following line:
```
app_type: node
```
Then you'll also need to rename (or copy) `.env.example` to `.env`

**Comment by dan-gamble** [comment]
I'm getting this issue when creating a project:

![img](https://i.imgur.com/AAu8DY3.png)

**Comment by tylerball** [comment]
This should be fixed by #212
