### ISSUE TITLE
Linux invalid "please install dependencies" message

### ISSUE THREAD

**Issue by rickmurt** [Shopify/shopify-app-cli#169]
# Issue summary

Ubuntu 18.04, when running `eval "$(curl -sS https://raw.githubusercontent.com/Shopify/shopify-app-cli/master/install.sh)"` I'm getting the following error message

> please install dependencies with 'sudo apt-get install git-core ruby'

but I have both git and ruby installed. I think it's because the `check_executables` function is doing `which "git ruby"` instead of `which "git"` and `which "ruby"`. If I just immediately `return 0;` in `check_linux_prerequisites`, thus skipping the `check_executables` call, it installs successfully and works as expected.

## Expected behavior

I should not get an error as I have both `git-core` and `ruby` installed

## Actual behavior

I get the error 

<details>please install dependencies with 'sudo apt-get install git-core ruby'</details>

## Steps to reproduce the problem

1. run `'sudo apt-get install git-core ruby'` on ubuntu 18.04

## Specifications

- Operating System: ubuntu 18.04
- Shell: zsh
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]

**Comment by katiedavis** [comment]
Hi @rickmurt thanks for filing this issue! I'm looking into.
