### ISSUE TITLE
shopify webhook generate outputs JSON::ParserError

### ISSUE THREAD

**Issue by dayvough** [Shopify/shopify-app-cli#176]
# Issue summary

Running `shopify generate webhook` on either the Rails or the Node app produces a wall of text.

## Expected behavior

Was expecting it to generate a webhook and say "✅ generated webhook" and tell me where to locate the file.

## Actual behavior

<img width="957" alt="Screen Shot 2019-06-20 at 03 34 55" src="https://user-images.githubusercontent.com/935170/59795111-1f453d00-930d-11e9-8cb1-ce170b85820e.png">

## Specifications

- Operating System: MacOS Mojave 10.14.4
- Shell: zsh
- Ruby version (ruby -v): ruby 2.6.0p0

**Comment by katiedavis** [comment]
Hi @dayvough, I couldn't replicate this on a node app, but you did find a bug on our rails apps. The generate features - `webhook`, `page`, and `billing` are not yet implemented on the CLI yet for Rails apps. 
Truly sorry about the confusion. 

I'm going to keep trying to replicate the error when running a new node app.
