### ISSUE TITLE
Rails embedded app fails `serve` with "Blocked host"

### ISSUE THREAD

**Issue by ragalie** [Shopify/shopify-app-cli#177]
# Issue summary

After creating a Rails embedded app and running `shopify serve`, the app fails to load the login page with a "Blocked host" error: 

![image (2)](https://user-images.githubusercontent.com/19682/59795663-baa4c680-92a9-11e9-8beb-82c064a0a201.png)

## Expected behavior

The app should redirect to the install page for my development shop.

## Steps to reproduce the problem

1. `shopify create project` with Rails embedded app
1. `shopify serve`
1. Ctrl-T

## Specifications

- Operating System: Mac OS
- Shell: bash
- Ruby version (ruby -v): 2.3.7p456

**Comment by tylerball** [comment]
shopify_app 11.3.0 and the CLI now solves this.

**Comment by tanema** [comment]
I thought @katiedavis Had a fix for this with an ngrok regex?

**Comment by tylerball** [comment]
@tanema the CLI is still installing an old version of shopify_app. Updating in #365 will fix this.
