### ISSUE TITLE
Could not read from remote repository.

### ISSUE THREAD

**Issue by RaphArbuz** [Shopify/shopify-app-cli#184]
# Issue summary

Write a short description of the issue here ↓

When running shopify create project, the script fails after all questions stating "fatal: Could not read from remote repository."

## Expected behavior

What do you think should happen?

The command should execute without an error.

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

<details>This command ran with ID: 18092
Please include this information in any issues/report along with relevant logs
/Users/username/.shopify-app-cli/lib/shopify-cli/tasks/clone.rb:26:in `block in git_progress': Cloning into 'test_app'... (RuntimeError)

Warning: Permanently added the RSA host key for IP address 'XX.XX.XX.XX' to the list of known hosts.

git@github.com: Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

	from /Users/username/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/progress.rb:34:in `progress'
	from /Users/username/.shopify-app-cli/lib/shopify-cli/tasks/clone.rb:15:in `git_progress'
	from /Users/username/.shopify-app-cli/lib/shopify-cli/tasks/clone.rb:10:in `block in call'
	from /Users/username/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/frame.rb:82:in `open'
	from /Users/username/.shopify-app-cli/lib/shopify-cli/tasks/clone.rb:9:in `call'
	from /Users/username/.shopify-app-cli/lib/shopify-cli/task.rb:7:in `call'
	from /Users/username/.shopify-app-cli/lib/shopify-cli/app_types/node.rb:44:in `build'
	from /Users/username/.shopify-app-cli/lib/shopify-cli/app_type_registry.rb:12:in `build'
	from /Users/username/.shopify-app-cli/lib/shopify-cli/commands/create/project.rb:24:in `call'
	from /Users/username/.shopify-app-cli/lib/shopify-cli/commands/create.rb:12:in `call'
	from /Users/username/.shopify-app-cli/lib/shopify-cli/command.rb:14:in `call'
	from /Users/username/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	from /Users/username/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	from /Users/username/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
	from /Users/username/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	from /Users/username/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
	from /Users/username/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	from /Users/username/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	from /Users/username/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	from /Users/username/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	from /Users/username/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	from /Users/username/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	from /Users/username/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	from /Users/username/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	from /Users/username/.shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
	from /Users/username/.shopify-app-cli/lib/shopify-cli/entry_point.rb:16:in `call'
	from /Users/username/.shopify-app-cli/bin/shopify:37:in `block in <main>'
	from /Users/username/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:74:in `handle_abort'
	from /Users/username/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:20:in `call'
	from /Users/username/.shopify-app-cli/bin/shopify:36:in `<main>'
</details>

## Steps to reproduce the problem

Run shopify create project test_app and answer every question.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- Operating System: MacOS 10.14.5
- Shell:
- Ruby version (ruby -v):

**Comment by adiii4** [comment]
Try to add the following environment variable:

`export SHOPIFY_CLI_BOOTSTRAP_GIT_URL=https://github.com/shopify/shopify-app-cli.git`

Then run the script/command again. Then it worked for me.

**Comment by RaphArbuz** [comment]
Thanks @adiii4! It worked after adding your environment variable (dunno if that helped but I did it) + running shopify update to update to last version.

**Comment by oneezy** [comment]
This works! Thanks a ton @adrianriepl
