### ISSUE TITLE
Generating a page doesn't keep module name casing

### ISSUE THREAD

**Issue by salexzee** [Shopify/shopify-app-cli#188]
# Issue summary

When running `shopify generate page PageName` the module does not keep the same casing. 

## Expected behavior

The module should be created as:

```javascript
const PageName = () => (
...
)
```

## Actual behavior

The module is created as:

```javascript
const Pagename = () => (
  ...
)
```

## Steps to reproduce the problem

1. Run `shopify generate page PageName` in the terminal
2. Within the file /pages/pagename.js the incorrect casing will be found

## Specifications

- Operating System: macOS Mojave 10.14.5
- Shell: zsh
- Ruby version (ruby -v): 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

**Comment by salexzee** [comment]
Here are a few screenshots of what I actually saw.

**Command**
<img width="421" alt="Screen Shot 2019-06-21 at 8 45 26 AM" src="https://user-images.githubusercontent.com/7700131/59934755-20f02d00-9401-11e9-9ce9-f24d806fc99e.png">

**File `/pages/somepage.js`**
<img width="474" alt="Screen Shot 2019-06-21 at 8 45 45 AM" src="https://user-images.githubusercontent.com/7700131/59934759-23eb1d80-9401-11e9-9a0e-3d9e525c8f63.png">

**Comment by katiedavis** [comment]
Hey @salexzee this should be resolved now. Thanks for opening an issue!

**Comment by salexzee** [comment]
Awesome @katiedavis thanks for looking into this one.
