### ISSUE TITLE
Rails create failed

### ISSUE THREAD

**Issue by fujinaga4fracta** [Shopify/shopify-app-cli#191]
# Issue summary

Write a short description of the issue here ↓

Install failed.

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Install failed. with under messages.

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error
<details>
This command ran with ID: 10771
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
	28: from /Users/$USER/.shopify-app-cli/bin/shopify:36:in `<main>'
	27: from /Users/$USER/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:20:in `call'
	26: from /Users/$USER/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:74:in `handle_abort'
	25: from /Users/$USER/.shopify-app-cli/bin/shopify:37:in `block in <main>'
	24: from /Users/$USER/.shopify-app-cli/lib/shopify-cli/entry_point.rb:16:in `call'
	23: from /Users/$USER/.shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
	22: from /Users/$USER/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	21: from /Users/$USER/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	20: from /Users/$USER/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	19: from /Users/$USER/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	18: from /Users/$USER/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	17: from /Users/$USER/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	16: from /Users/$USER/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	15: from /Users/$USER/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	14: from /Users/$USER/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
	13: from /Users/$USER/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	12: from /Users/$USER/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
	11: from /Users/$USER/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	10: from /Users/$USER/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	 9: from /Users/$USER/.shopify-app-cli/lib/shopify-cli/command.rb:14:in `call'
	 8: from /Users/$USER/.shopify-app-cli/lib/shopify-cli/commands/create.rb:12:in `call'
	 7: from /Users/$USER/.shopify-app-cli/lib/shopify-cli/commands/create/project.rb:24:in `call'
	 6: from /Users/$USER/.shopify-app-cli/lib/shopify-cli/app_type_registry.rb:12:in `build'
	 5: from /Users/$USER/.shopify-app-cli/lib/shopify-cli/app_types/rails.rb:46:in `build'
	 4: from /Users/$USER/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/frame.rb:82:in `open'
	 3: from /Users/$USER/.shopify-app-cli/lib/shopify-cli/app_types/rails.rb:47:in `block in build'
	 2: from /Users/$USER/.shopify-app-cli/lib/shopify-cli/context/system.rb:11:in `system'
	 1: from /Users/$USER/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:114:in `system'
/Users/$USER/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:114:in `spawn': No such file or directory - /Users/$USER/.gem/ruby/2.5.1/bin/rails (Errno::ENOENT)
</details>

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- Operating System: Mac 10.14.5
- Shell: Bash
- Ruby version (ruby -v): 2.5.1

**Comment by eliasfeijo** [comment]
I'm also getting this error when running `shopify create project APP_NAME` and selecting `rails embedded app`.

Ruby version: 2.5.1
Rails version: 5.2.3
OS: Ubuntu 18.04.2

How can I get this working?

**Comment by tylerball** [comment]
@eliasfeijo mind running `shopify update` just to make sure and trying again?

**Comment by eliasfeijo** [comment]
@tylerball just tried that, still not working. Any ideas?

**Comment by tanema** [comment]
@eliasfeijo Can you add a `DEBUG=1` variable to your console environment and run the command again? Your output shows that rails was not installed appropriately but it should have been. If you enable Debug, we should be able to see the debug output if rails installed correctly.

**Comment by eliasfeijo** [comment]
@tanema sure, here is the output:

<details>
elias@elias-Lenovo-G400s:~/workspace/trampolin/shopify$ DEBUG=1 shopify create project test-rails
✔︎ ngrok tunnel running at  https://6834bea2.ngrok.io
? What type of app project would you like to create? (Choose with ↑ ↓ ⏎, filter ? What type of app project would you like to create? (You chose: rails embedded app)                                                                            
DEBUG rails installed: true                                                     
DEBUG bundler installed: true
DEBUG rails installed: true
┏━━ Installing bundler… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ DEBUG bundler installed: true
┃ DEBUG bundler installed: true
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0.02s) ━━
┏━━ Generating new rails app project in test-rails... ━━━━━━━━━━━━━━━━━━━━━━━━━━
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0.04s) ━━
This command ran with ID: 18383
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
	28: from /run/user/1000/.shopify-app-cli/bin/shopify:36:in `<main>'
	27: from /run/user/1000/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	26: from /run/user/1000/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	25: from /run/user/1000/.shopify-app-cli/bin/shopify:37:in `block in <main>'
	24: from /run/user/1000/.shopify-app-cli/lib/shopify-cli/entry_point.rb:16:in `call'
	23: from /run/user/1000/.shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
	22: from /run/user/1000/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	21: from /run/user/1000/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	20: from /run/user/1000/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	19: from /run/user/1000/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	18: from /run/user/1000/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:53:in `twrap'
	17: from /run/user/1000/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	16: from /run/user/1000/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	15: from /run/user/1000/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	14: from /run/user/1000/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
	13: from /run/user/1000/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	12: from /run/user/1000/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
	11: from /run/user/1000/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	10: from /run/user/1000/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	 9: from /run/user/1000/.shopify-app-cli/lib/shopify-cli/command.rb:14:in `call'
	 8: from /run/user/1000/.shopify-app-cli/lib/shopify-cli/commands/create.rb:12:in `call'
	 7: from /run/user/1000/.shopify-app-cli/lib/shopify-cli/commands/create/project.rb:23:in `call'
	 6: from /run/user/1000/.shopify-app-cli/lib/shopify-cli/app_type_registry.rb:12:in `build'
	 5: from /run/user/1000/.shopify-app-cli/lib/shopify-cli/app_types/rails.rb:49:in `build'
	 4: from /run/user/1000/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/frame.rb:82:in `open'
	 3: from /run/user/1000/.shopify-app-cli/lib/shopify-cli/app_types/rails.rb:50:in `block in build'
	 2: from /run/user/1000/.shopify-app-cli/lib/shopify-cli/context/system.rb:11:in `system'
	 1: from /run/user/1000/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:114:in `system'
/run/user/1000/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:114:in `spawn': No such file or directory - /home/elias/.gem/ruby/2.5.1/bin/rails (Errno::ENOENT)
</details>

**Comment by diemah77** [comment]
Any update on this? Got the same error.
