### ISSUE TITLE
Expected a valid shop query parameter

### ISSUE THREAD

**Issue by evitaotm** [Shopify/shopify-app-cli#201]
I set up all redirect links and .env file, but when I run Shopify serve and when it says  Ready on http://localhost:8081,  I go to localhost page and it shows this error: Expected a valid shop query parameter.
What does it mean?
Thank you.

**Comment by dan-gamble** [comment]
You'll need to set up your app in the partners dashboard with the ngrok URL you get from `shopify server` like so:

![img](https://i.imgur.com/ld76ZTe.png)

Once you've done that you can either

![img](https://i.imgur.com/epHVEDJ.png)

Install it on your development store or go to your `https://ngrok.url/auth?shop={your-shop-url}`

**Comment by evitaotm** [comment]
Thanks, everything worked!

**Comment by 521lixin** [comment]
> 您需要使用从中获得的ngrok URL在合作伙伴仪表板中设置应用程序，`shopify server`如下所示：
> 
> ![img](https://camo.githubusercontent.com/5bcd1447882cae0822b550658905a2c32c18d3d8/68747470733a2f2f692e696d6775722e636f6d2f6c6437365a54652e706e67)
> 
> 完成后，您可以
> 
> ![img](https://camo.githubusercontent.com/1ae74ac24974afaed06792269d3a12f8e73b34d5/68747470733a2f2f692e696d6775722e636f6d2f6570485645444a2e706e67)
> 
> 将其安装在您的开发商店上或转到 `https://ngrok.url/auth?shop={your-shop-url}`

I followed the instructions you gave, but I still ran into problems.         Expected a valid shop query parameter

**Comment by neil-rubens** [comment]
Had the same error; was able to fix it by going to url  mentioned after `shopify create` was executed:

> ⭑ Run shopify serve to start a local server
> ⭑ Then, visit https://partners.shopify.com/<YOUR-ID>/apps/<YOUR-ID2>/test to install <YOUR-APP> on your Dev Store

**Comment by tanema** [comment]
@neil-rubens you can run `shopify serve` and then `shopify open` in another terminal if you want a shortcut to install

**Comment by neil-rubens** [comment]
@tanema thanks for pointinting `shopify open` quite handy

In my case, the error was caused by the app not being installed.  
I overlooked the installation message from `shopfiy create`:  `https://partners.shopify.com/<ACCOUNT-ID>/apps/<APP-ID>/test`

p.s. revised my previous post to show all of the parts of the url

**Comment by procarrera** [comment]
Hello, I am having the same problem.

1) Installed my app using `shopify create`
2) Then I ran `shopify serve`
3) After server being created I opened the link:` https://partners.shopify.com/<ID>/apps/<ID>/test`
  
The installation occured after some erros, but in the end it appers to be installed:

![image](https://user-images.githubusercontent.com/53456120/104132446-06233780-535c-11eb-9703-cff88d14aab0.png)

![image](https://user-images.githubusercontent.com/53456120/104132519-8a75ba80-535c-11eb-8e82-b89b261a61d3.png)


But, when i try to reach http://localhost:8081 I still get the error:

![image](https://user-images.githubusercontent.com/53456120/104132530-a2e5d500-535c-11eb-8768-fe07dcd9ddd8.png)
