### ISSUE TITLE
Update "you are not in a shopify project" error

### ISSUE THREAD

**Issue by davekilljoy** [Shopify/shopify-app-cli#206]
# Issue summary

Update error state to include more information about how to proceed

## Expected behavior

<img width="1000" alt="Screen Shot 2019-07-03 at 11 46 19 AM" src="https://user-images.githubusercontent.com/1523373/60605916-5d6c4300-9d88-11e9-8513-e6281c2f8ad9.png">

## Actual behavior

What actually happens?

<img width="906" alt="Screen Shot 2019-07-03 at 11 47 07 AM" src="https://user-images.githubusercontent.com/1523373/60605869-4e859080-9d88-11e9-810d-11eba22f2480.png">

**Comment by katiedavis** [comment]
This is no longer running in our current flow so I am going to investigate how to re-implement it
