### ISSUE TITLE
APP::ERROR::INVALID_CONFIG: shopOrigin must be provided

### ISSUE THREAD

**Issue by evitaotm** [Shopify/shopify-app-cli#209]
_app.js file
`static async getInitialProps(server) {
    const shopOrigin = server.ctx.query.shop;
    return { shopOrigin };
  }
`

shopOrigin returns undefined.

.env file

SHOPIFY_API_KEY=xxxx
SHOPIFY_API_SECRET_KEY=xxxx
HOST=https://1d22411q1.ngrok.io
SHOP=xxxx.myshopify.com
SCOPES=write_products,write_customers,write_draft_orders

**Comment by katiedavis** [comment]
Hi @evitaotm I just wanted to ask - are you loading the app within your shop's admin when you get the undefined shopOrigin prop?

**Comment by evitaotm** [comment]
I'm loading it on ngrok.io server.

**Comment by katiedavis** [comment]
Ah yes, you need to install the app on a shop and load it within that admin frame to have the shopOrigin prop available.

To install your app on a development store you can use the following installation address:
HTTPS://yourngrokurl.io/auth?shop=xxx.myshopify.com

That will prompt you to install (you may get an error page, just reload) and after that, when you head to the apps in your xxx.myshopify.com you'll be able to load the app with the shopOrigin available :)

**Comment by katiedavis** [comment]
@evitaotm I've also put in a PR to update our readme as we don't surface this information for you! Sorry about that.

**Comment by MladenJanjetovic** [comment]
Thanks for the info. I succeed with this link, but it's strange why it didn't want to install it with the `Test app on development store` button in partners panel?

**Comment by laptite** [comment]
@katiedavis Thanks! Ditto what @MladenJanjetovic said about it not working from the Stores button. I'm following the shopify node/react tutorial and wasn't able to get the embed to work without this workaround (was getting an app-bridge-react error as well as the ShopOrigin). 

NB. After the workaround I ran into an ERR_NGROK_702 error, which was cleared by clicking the sample app link at the top of the embed.

**Comment by rin0o1** [comment]
I had the same problem and I solved it by adding both API_KEY and shopOrigin as variables.

![img_](https://user-images.githubusercontent.com/30932379/88195115-88496380-cc37-11ea-8302-2f020deefd87.PNG)

**Comment by hgezim** [comment]
@rin0o1 Hard-coding the shop name is not ideal.

**Comment by hardnold** [comment]
> Thanks for the info. I succeed with this link, but it's strange why it didn't want to install it with the `Test app on development store` button in partners panel?

I'm experiencing the same issue. When installing the app via "Test app on development store"-Button I get this App-Bridge Error telling me shopOrigin needs to be provided. But when using the provided link (HTTPS://yourngrokurl.io/auth?shop=xxx.myshopify.com) it works without any problems.

What's the issue here?

**Comment by mroozspace** [comment]
hi, I'm also having this issue. There was a notification in partners dashboard on March 17 with this [link]. I'll analyse it and let you know if I manage to fix that.
