### ISSUE TITLE
Update populate command UX flow

### ISSUE THREAD

**Issue by davekilljoy** [Shopify/shopify-app-cli#219]
# Issue summary

Update `populate` command with default and verbose modes. Am open to discussion on which is preferred though.

## Expected behavior

Default mode
<img width="670" alt="Screen Shot 2019-07-05 at 10 04 02 AM" src="https://user-images.githubusercontent.com/1523373/60727809-ce3c6800-9f0c-11e9-834a-46e1627782af.png">

1. Suppress all output behind a spinner
2. Show process was successful with a summary
3. Link to store product index

--verbose mode
<img width="825" alt="Screen Shot 2019-08-15 at 2 18 57 PM" src="https://user-images.githubusercontent.com/1523373/63116486-c6d69880-bf67-11e9-8295-4e1d57150e44.png">

1. Expose all output individually
2. Show process was successful with a summary
3. Link to store product index

## Actual behavior

Shows all products being created

**Comment by tylerball** [comment]
I think I prefer showing the URLs by default. I think they would be useful to most people and is a bit of evidence that something actually happened. What about flipping it and having a `--silent` or `--quiet` flag instead?

**Comment by katiedavis** [comment]
I still think the verbose mode should be default but having a silent flag seems like a neat idea also.

**Comment by davekilljoy** [comment]
I am ok with flipping it and making the default show URLs and having a `--silent` mode!

**Comment by katiedavis** [comment]
closing this. Opening https://github.com/Shopify/shopify-app-cli/issues/285 for --silent flag
