### ISSUE TITLE
Tunnel not found

### ISSUE THREAD

**Issue by RaphArbuz** [Shopify/shopify-app-cli#230]
# Issue summary

After running "shopify serve", I press Ctrl+T to open the tunnel link in a browser tab but I get in the browser the message "Tunnel aef61a22.ngrok.io not found".

## Expected behavior

The default app should appear in the browser

## Actual behavior

After pressing Ctrt+T I get the following output in the console:

> SIGINFO:
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:131:in `call'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:131:in `select'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:131:in `block in system'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:127:in `loop'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:127:in `system'
> /Users/xxx/.shopify-app-cli/lib/shopify-cli/context/system.rb:11:in `system'
> /Users/xxx/.shopify-app-cli/lib/shopify-cli/commands/serve.rb:21:in `block in call'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/frame.rb:82:in `open'
> /Users/xxx/.shopify-app-cli/lib/shopify-cli/commands/serve.rb:20:in `call'
> /Users/xxx/.shopify-app-cli/lib/shopify-cli/command.rb:14:in `call'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
> /Users/xxx/.shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
> /Users/xxx/.shopify-app-cli/lib/shopify-cli/entry_point.rb:16:in `call'
> /Users/xxx/.shopify-app-cli/bin/shopify:37:in `block in <main>'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
> /Users/xxx/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
> /Users/xxx/.shopify-app-cli/bin/shopify:36:in `<main>'

## Specifications

MacOS 10.14.5
Latest version of shopify-cli

**Comment by evitaotm** [comment]
I had the same problem, I just restarted my computer.

**Comment by RaphArbuz** [comment]
Thanks @evitaotm . It however didn't help in my case.

**Comment by katiedavis** [comment]
Hey @RaphArbuz can you try running `killall -9 ngrok` and then serve again and let me know what happens? You'll have to update the new tunnel url in your partners dash as well.

**Comment by RaphArbuz** [comment]
Thanks Katie. I still get the same error unfortunately.

**Comment by katiedavis** [comment]
Hey @RaphArbuz I just wanted to circle back and see if you were still experiencing this issue? SOrry I missed your last reply!

**Comment by RaphArbuz** [comment]
Thanks Katie! To be fair, I'm doing things differently which works fine for me: I start ngrok in a window and "shopify serve" in another one.

**Comment by tanema** [comment]
What you need to do is run `shopify tunnel stop` and then you can run `shopify serve` again which will start a new tunnel. The problem I think you are running into is that your tunnel had expired and you needed a new one.

**Comment by gmztech** [comment]
> What you need to do is run `shopify tunnel stop` and then you can run `shopify serve` again which will start a new tunnel. The problem I think you are running into is that your tunnel had expired and you needed a new one.

For a node app should use `shopify node tunnel stop`

**Comment by devdarren7** [comment]
> What you need to do is run `shopify tunnel stop` and then you can run `shopify serve` again which will start a new tunnel. The problem I think you are running into is that your tunnel had expired and you needed a new one.

shopify **app** tunnel stop not shopify tunnel stop
