### ISSUE TITLE
Customers GraphQL acting weird.

### ISSUE THREAD

**Issue by meiskv** [Shopify/shopify-app-cli#235]
Hi,

I am having a problem whenever I am querying the customer's data. I am having the errors below on screenshots.

I am following this docs https://help.shopify.com/en/api/getting-started/shopify-and-graphql/queries

But if I try another query for example this. Shop Infos.  It works just fine. 

I hope anyone could help me. Cheers!

query {
  shop {
    id
    name
    email
  }
}

<img width="1245" alt="Screen Shot 2019-07-12 at 4 39 57 AM" src="https://user-images.githubusercontent.com/939470/61094446-49979f80-a460-11e9-928f-f699e0c24130.png">
<img width="506" alt="Screen Shot 2019-07-12 at 4 40 10 AM" src="https://user-images.githubusercontent.com/939470/61094447-4a303600-a460-11e9-9f4b-7b0c3b783b81.png">

**Comment by katiedavis** [comment]
hey @meiskv this might be a good question for the forums! 
https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology
