### ISSUE TITLE
Install script installs to temporary location on Linux

### ISSUE THREAD

**Issue by michaelfiber** [Shopify/shopify-app-cli#246]
# Issue summary
On Linux the install script defaults to a temporary location.

## Expected behavior
The "shopify" command should continue to work after a system restart.

## Actual behavior
On Ubuntu the install script targets /run/usr/$uid which is a temp folder for non-essential runtime files and its contents are wiped once there are no active sessions. So the shopify command stops working after a log out or restart.

`install_dir="${XDG_RUNTIME_DIR:-$HOME}/.shopify-app-cli"`

XDG_RUNTIME_DIR is for temp files and on systemd based systems at least it points to /run/usr/$uid by default.

## Specifications

- Operating System: Ubuntu 18.04
- Ruby version (ruby -v): 2.5.1p57

**Comment by tanema** [comment]
Hey @michaelfiber thanks for letting us know about this. I will get a fix in for this pretty soon. I just gotta find the right env var 😄

**Comment by michaelfiber** [comment]
Happy to help! I changed it to target $HOME instead for myself since that's the fallback if the other value doesn't exist anyway, but was hesitant to do a PR because I haven't released an install script that targets the whole Linux world and figure there's probably some best practices I don't know.

I edited .bash_profile and .bashrc to target the new location and noticed that when the install script writes to .bashrc it actually doesn't expand install_dir so it ends up writing this:

`if [[ -f "${install_dir}/shopify.sh"  ]] && [[ $- == *i* ]]; then`

**Comment by tanema** [comment]
Thanks on two counts! I have opened PR #247 to change it to only use HOME so it is good to hear that falls in line with what you would prefer, and also thanks for the note one the bashrc I will look into that next.

**Comment by tanema** [comment]
okay @michaelfiber I have updated #247 to include a fix for the bash_profile shim. It was just not using the correct quotes for string interpolation. Hopefully I can deploy it soon I just have to get some reviews.
