### ISSUE TITLE
Embedded App does not redirect to Shopify frame if opened at the app url directly even after setting forceRedirect to true

### ISSUE THREAD

**Issue by amardeep9911** [Shopify/shopify-app-cli#248]
# Issue summary

I am using Shopify App CLI to build a node.js project. It is an embedded app and when I open it from within the Installed Apps section of a merchant store, it works fine and App bridge <Provider> works fine but when I visit the App url directly (ngrok url along with shop parameter), it opens outside Shopify without redirecting inside Shopify frame and the <Provider> doesn't set shopOrigin properly and does not work.

## Expected behavior

I expected it to redirect and open inside Shopify and set App Bridge <Provider> properly since it is an embedded app and I have set forceRedirect to true

## Actual behavior

What actually happens?
The app is opening outside Shopify frame and app bridge <Provider> is not setting shopOrigin properly (it is null)

## Steps to reproduce the problem

1. Open an embedded app project by directly visiting the provided ngrok url (and passing in the shop parameter)
2. See that while it authenticates properly but does not get redirected inside Shopify frame.

**Comment by katiedavis** [comment]
hey @amardeep9911 the shopOrigin will not be set until you're inside the IFrame (because it doesn't know what the ShopOrigin is) but I there's also an issue right now with ForceRedirect upon installation. If you reload your app within the Iframe (by logging into the store, and clicking apps) you'll be able to see the ShopOrigin parameter set. 

This isn't ideal, but I'll loop back around and let you know when the ForceRedirect issue has been fixed upon installation.

**Comment by amardeep9911** [comment]
Is there a workaround for this? Because if it does not redirect to iFrame then App Store will not approve it and also the merchants will have a very bad installation experience.

On a separate note, any tips on deploying this to serverless platforms (like Zeit Now)? I tried but Oauth does not seem to be tuned for serverless. I am very keen on it but need some direction. 
Thanks.

**Comment by katiedavis** [comment]
Hey @amardeep9911 ! I am looking into this and I'll let you know when I come up with a solution :)

For deploying to serverless, you'd have to do a bit of digging. We do have it on our roadmap to work on a serverless deployment option, but that will be an enhancement after we're out of beta.

Here's an article that might help? https://medium.com/typeforms-engineering-blog/dance-through-oauth-headaches-with-serverless-d492e0a6e1ee 

I'll ping you about the forceredirect thing.

**Comment by katiedavis** [comment]
Hi again @amardeep9911  You can go ahead and copy this pattern until it gets merged:

Set a cookie in your server.js file:
 ```
const { shop, accessToken } = ctx.session;
ctx.cookies.set("shopOrigin", shop, { httpOnly: false });
ctx.redirect("/");
```



Get it in your _app.js file: 
```
import ApolloClient from "apollo-boost";
import { ApolloProvider } from "react-apollo";
import App, { Container } from "next/app";
import { AppProvider } from "@shopify/polaris";
import { Provider } from "@shopify/app-bridge-react";
import Cookies from "js-cookie";
import "@shopify/polaris/styles.css";

const client = new ApolloClient({
  fetchOptions: {
    credentials: "include"
  }
});
class MyApp extends App {
  render() {
    const { Component, pageProps } = this.props;
    const shopOrigin = Cookies.get("shopOrigin");
    return (
      <Container>
        <AppProvider>
          <Provider
            config={{
              apiKey: API_KEY,
              shopOrigin: shopOrigin,
              forceRedirect: true
            }}
          >
            <ApolloProvider client={client}>
              <Component {...pageProps} />
            </ApolloProvider>
          </Provider>
        </AppProvider>
      </Container>
    );
  }
}

export default MyApp;
```

You'll need to install js-cookie to use it in this manner

**Comment by amardeep9911** [comment]
Thanks for the suggestions :).. And serverless Shopify app would be really awesome! Keeping my fingers crossed.
--
I had already implemented the cookie based workaround after seeing it in one of the older examples of Shopify Node React App. It is working for now; just want to test what happens when a user opens up 2 instances of the app in the same browser but through different shops. 

Thanks again.

**Comment by egillanton** [comment]
@katiedavis When you create another Page, lets say I name it SettingsPage

How do I retrieve the context in the constructor of the class component? 

```js
import { Context } from "@shopify/app-bridge-react";

class SettingsPage extends React.Component {
    static context = Context;
    constructor(props) {
      super(props);
      this.state = {
        shopOrigin: "/**GET shopOrigin from the context ***/",
      };
    }
  ...
}

export default SettingsPage;
```
