### ISSUE TITLE
Ask if we should run tunnel

### ISSUE THREAD

**Issue by katiedavis** [Shopify/shopify-app-cli#250]
# Issue summary

We currently start a tunnel on app create and assume the user wants it. Often they have tunnels running on their own it causes it to error out, or they need to update an address in the admin and they may not want to. We should ask before we run the ngrok tunnel.

**Comment by tylerball** [comment]
We could add a `--no-tunnel` option to server to handle this.

**Comment by katiedavis** [comment]
I think `--host` is pretty great. That way we could write their input to the `.env` file and stuff. I'll do that.
