### ISSUE TITLE
How do I uninstall this? I don't think it installed properly and would like to go a different route.

### ISSUE THREAD

**Issue by forrestblade** [Shopify/shopify-app-cli#255]

**Comment by tanema** [comment]
You can delete the line from your bash profile, zshrc or whatever shell config you have that looks like this `[ -f "/Users/timanema/.shopify-app-cli/shopify.sh" ] && source "/Users/timanema/.shopify-app-cli/shopify.sh"` That will also show you where it is currently installed and you can delete that directory.
