### ISSUE TITLE
Missing case for ubuntu

### ISSUE THREAD

**Issue by Tobjoern** [Shopify/shopify-app-cli#261]
# Issue summary
The install script (https://raw.githubusercontent.com/Shopify/shopify-app-cli/master/install.sh) is missing a case check for ubuntu in the function "check_linux_prerequisites".

Write a short description of the issue here ↓
I run linux mint (e.g a flavor of ubuntu) and I tried installing shopify cli via the aforementioned script, however it always gave me the following error message:

> ┃ ✗ Only apt (e.g. Ubuntu, Debian) and yum (e.g. CentOS, Fedora) are supported
> ┃ ✗ in this install script. To proceed, figure out how to install the equivalent
> ┃ ✗ of: build-essential, git-core, and ruby. Then, export SKIP_PREREQS=1 and run
> ┃ ✗ this script again. At the end, /usr/bin/ruby must exist and be >= 2.0.0

## Expected behavior

What do you think should happen?
Install shopify cli successfully

## Actual behavior

What actually happens?
Installation fails

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. Run Linux mint / any version that is not debian or fedora

## Specifications

- Operating System: Linux Mint 19.1
- Ruby version (ruby -v): ruby 2.5.1p57

## Fix
In order to fix this problem a further case for ubuntu has to be added to the function 'check_linux_prerequisites', as there is currently no way to install shopify on ubuntu with the current script. I temporily fixed the problem by commenting out the error messages, which are sent if the operating system is neither debian nor fedora. With thix 'fix' I was able to install the cli.

##Edit
I also needed to add `alias shopify='/run/user/1000/.shopify-app-cli/bin/shopify'` to my .bash_aliases, as shopify was not added to the path by default.

**Comment by tanema** [comment]
Hey @Tobjoern thanks for reporting this, we are still sorting out our installation process so thanks for helping us make it betting. I will see what I can do to fix this.

**Comment by knsakib** [comment]
same here! In ubuntu also.

**Comment by arialblack14** [comment]
I also tried this script today and having the same issue.
Linux mint as well.

**Comment by arialblack14** [comment]
How I solved this...
First I did what the error message suggested. I upgraded `git` from `2.17.1` to the latest one (which at the time of writing is  `2.24.1` ).
Then I run `SKIP_PREREQS=1`
and exported it `export SKIP_PREREQS`.
After these I was able to run the script.

**Comment by mkevinosullivan** [comment]
As of v1.0.0 of the CLI, we no longer install via that installation script but instead support `apt` or `yum` on Linux (as well as `gem install`). https://shopify.github.io/shopify-app-cli/getting-started/install/
