### ISSUE TITLE
Invalid API key or access token

### ISSUE THREAD

**Issue by evitaotm** [Shopify/shopify-app-cli#263]
I added SHOPIFY_API_KEY in my .env file  and I was trying to run shopify generate webhook, but it shows me an error:

`block in request': 401 (ShopifyCli::Helpers::API::APIRequestUnauthorizedError)
{"errors":"[API] Invalid API key or access token (unrecognized login or wrong password)"}

**Comment by katiedavis** [comment]
hey @evitaotm can you run `shopify authenticate` and let me know how that goes? which app did you try to create webhooks in?

**Comment by evitaotm** [comment]
shopify authenticate worked! Thanks!

**Comment by katiedavis** [comment]
🎉

**Comment by tanema** [comment]
As a follow up note, we should be able to make this better in the future to auto-call authenticate if we get a 401-403 from admin.
