### ISSUE TITLE
Updating to resolve deprecation changes Page behaviour 

### ISSUE THREAD

**Issue by mattAux** [Shopify/shopify-app-cli#270]
# Issue summary

I may be missing something here, but I haven't been able to find the solution using the cli & following the shopify tutorial.

After resolving the deprecation error ```Deprecation: Using /`apiKey/` and `shopOrigin` on `AppProvider` to initialize the Shopify App Bridge is deprecated. Support for this will be removed in v5.0. Use `Provider` from `@shopify/app-bridge-react` instead```
AppProvider & Provider moves the Polaris Page "primaryAction" button out of the Shopify app header ( next to Embed App Navigation )

## Expected behavior

When updating app root to resolve depreciation issues - using Provider within AppProvider.
The primary action button for a page element should not move.

## Actual behavior
This is prior to updating the app root:
![image](https://user-images.githubusercontent.com/44592071/62587892-efcbad80-b917-11e9-82f5-13ad46ae4559.png)
After updating the app root:
![image](https://user-images.githubusercontent.com/44592071/62588005-50f38100-b918-11e9-888a-0d8164257278.png)

## Reduced test case

Before update:
```
import ApolloClient from "apollo-boost";
import { ApolloProvider } from "react-apollo";
import App, { Container } from "next/app";
import Head from 'next/head';
import { AppProvider } from "@shopify/polaris";
import { Provider, Context } from "@shopify/app-bridge-react";
import "@shopify/polaris/styles.css";
import Cookies from 'js-cookie';

const client = new ApolloClient({
  fetchOptions: {
    credentials: "include"
  }
});

class MyApp extends App {

  state = {
    shopOrigin: Cookies.get('shopOrigin'),
  };

  static async getInitialProps(server) {
    const shopOrigin = server.ctx.query.shop;
    return { shopOrigin };
  }

  render() {
    const { Component, pageProps, shopOrigin } = this.props;
    return (
        <Container>
            <AppProvider
              shopOrigin={this.state.shopOrigin}
              apiKey={API_KEY}
              forceRedirect
            >
              <ApolloProvider client={client}>
                <Component {...pageProps} />
              </ApolloProvider>
          </AppProvider>
        </Container>
    );
  }
}

export default MyApp;
```
After Update:
```
import ApolloClient from "apollo-boost";
import { ApolloProvider } from "react-apollo";
import App, { Container } from "next/app";
import { AppProvider } from "@shopify/polaris";
import { Provider } from "@shopify/app-bridge-react";
import Cookies from "js-cookie";
import "@shopify/polaris/styles.css";

const client = new ApolloClient({
  fetchOptions: {
    credentials: "include"
  }
});
class MyApp extends App {
  render() {
    const { Component, pageProps } = this.props;
    const shopOrigin = Cookies.get("shopOrigin");
    return (
      <Container>
        <AppProvider>
          <Provider
            config={{
              apiKey: API_KEY,
              shopOrigin: shopOrigin,
              forceRedirect: true
            }}
          >
            <ApolloProvider client={client}>
              <Component {...pageProps} />
            </ApolloProvider>
          </Provider>
        </AppProvider>
      </Container>
    );
  }
}

export default MyApp;
```
I apologise if this isn't an issue, but I can't seem to resolve.

**Comment by katiedavis** [comment]
Hi @mattAux! Thanks for bringing this up! It looks like the embedded page component has been depreciated with the switch to `app-bridge-react`, users should now use the `titleBar` component from `app-bridge-react`: https://help.shopify.com/en/api/embedded-apps/app-bridge/react-components/titlebar

I'm going to update our resources to use this component, but in the mean time those docs should help :)

**Comment by katiedavis** [comment]
@mattAux The guide is updated here: https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris#add-the-title-bar

**Comment by mattAux** [comment]
Thank you for that @katiedavis!
