### ISSUE TITLE
Define page templates for generate command

### ISSUE THREAD

**Issue by davekilljoy** [Shopify/shopify-app-cli#275]
# Issue summary
Generating a page today in the CLI is not that helpful because the page generated is too generic and has no UI or opinion. This issue is to come up with a set of basic page templates that mirror Shopify page concepts in the admin. 

Examples like Index pages with resource pickers, settings pages with annotated layout, etc

# Page types

Figma designs https://www.figma.com/file/EFofSCyASYC8ZnA6hwacaD/Page-template-designs?node-id=0%3A1

**Empty state/onboarding**
https://polaris.shopify.com/components/structure/empty-state
The empty state is a common pattern used by apps as an onboarding opportunity.

![Empty state2](https://user-images.githubusercontent.com/1523373/63371882-ee0bdc00-c352-11e9-8b1c-201477804f5f.png)

**List/Index page**
https://polaris.shopify.com/components/lists-and-tables/resource-list
Similar to standard Shopify pages like Products or Customers, this page is common for app developers to list a set of resources.

![Index](https://user-images.githubusercontent.com/1523373/63372375-ef89d400-c353-11e9-9c3d-38700fa8475b.png)

**Details page**
https://polaris.shopify.com/components/structure/layout#navigation
Page that generally gets coupled with a resource list page type, shows the details of the selected resource with more in depth information. Similar to the Product index -> Product details relationship.

Single column
![1 column](https://user-images.githubusercontent.com/1523373/63354054-bccee400-c331-11e9-9e6e-36cc174a84e6.png)

2 column with primary and secondary cards
![2 Col](https://user-images.githubusercontent.com/1523373/63354072-c48e8880-c331-11e9-886d-581641f661a5.png)

2 column with equal sizes
![2 colum equal](https://user-images.githubusercontent.com/1523373/63354116-d839ef00-c331-11e9-9d83-c6521a525173.png)

3 column layout
![3 column](https://user-images.githubusercontent.com/1523373/63354093-ca846980-c331-11e9-91cb-5931454258b0.png)

**Settings page**
Settings in Shopify use a unique layout with text on the left to describe the setting, and a card on the right to enable/input values.

![Settings](https://user-images.githubusercontent.com/1523373/63354209-0a4b5100-c332-11e9-9655-dc84381b67c1.png)

**Comment by davekilljoy** [comment]
Put together a list of what I believe are the core 4 page types we could generate for our users, would love your opinions @tylerball @nwtn @tanema @katiedavis

**Comment by nwtn** [comment]
should we have the account connection component (https://polaris.shopify.com/components/actions/account-connection) on the settings page? probably a pretty common thing for a lot of apps where users need to integrate with another service

**Comment by davekilljoy** [comment]
Account connection to me is actually a card in the settings page, not a page by itself. Almost the empty state of the settings page?

**Comment by nwtn** [comment]
right that’s what i meant. when we generate a settings page, should it include that card/component?

**Comment by davekilljoy** [comment]
Right I can read. Sorry, yes I think we should have that card baked in. Should I make another issue for contents of the templated pages or keep it in this issue?

**Comment by davekilljoy** [comment]
Actually I think I take it back @nwtn, except for the Index page I don't think we should be prescriptive on what contents go inside each card. The Index is an exception because the resource list is the main layout and function of the page. For settings, we cant assume every page would need a connect account component.

**Comment by katiedavis** [comment]
how would we write the command for this? 
would it be `shopify generate empty-state-page` ? should the page have a 'name'? what should we message for rails apps? they can't have these pages. I have questions.

**Comment by davekilljoy** [comment]
Yea I was going to make a new issue to define the commands, this issue was more to outline the layouts we could use @katiedavis.

Top of my head though I would say the command may be something like
`shopify generate page empty-state`
`shopify generate page index`
`shopify generate page details 1-col`

or something like that but I think we should all discuss together first.

**Comment by nwtn** [comment]
imo:

1. trying to define memorable shorthands for page types is probably not worth it and won’t scale well, similar to shorthands for project types. i think we should handle this the same way we do for `shopify create project`, e.g.

    ````
    $ shopify generate page --name daves-page
    What kind?
      * Empty state
      * Index
      * Details
    ```

    (also like `generate page daves-page` could work, where `name` is a positional argument instead of a flag)

2. For Rails (also considering #225), I think we should do something like this:

    ````
    $ shopify generate page --name daves-page
    What kind?
    …
    Which controller?
      * ApplicationController
      * Whatever
      * new controller
    ````

    …and then hook into `rails generate` with that info

**Comment by nwtn** [comment]
oh also for rails — i know we can’t use polaris rails to generate these templates, but we _can_ use polaris html + css (https://polaris.shopify.com/components/get-started)

**Comment by katiedavis** [comment]
I think having it exactly the same as project makes sense 
`shopify generate page pagename` (positional argument)

**Comment by davekilljoy** [comment]
I like going with the same structure as project, and having arguments for page types as a shortcut
`shopify generate page [pagename]`
`What kind?`
  `* Empty state`
 ` * Index`
  `* Details`

`shopify generate page [pagename] --type=index`
