### ISSUE TITLE
`found 15965 high severity vulnerabilities` after creating project

### ISSUE THREAD

**Issue by philschoefer** [Shopify/shopify-app-cli#294]
# Issue summary

After running `shopify project create <app_name>` I see the following message. To me this sounds somewhat alarming. Like a bunch of vulnerabilities just were installed.

<img width="790" alt="Screen Shot 2019-09-05 at 9 12 58 AM" src="https://user-images.githubusercontent.com/4960217/64344998-85ad3380-cfbd-11e9-8b34-9b5c6454eff6.png">

## Expected behavior

Ideally just an information that packages were installed but no mentioning of almost 16000 vulnerabilities.

## Steps to reproduce the problem

1. Install `shopify-app-cli`
1. Run `shopify project create <app_name>`

## Specifications

- App type: -
- Operating System: MacOS 10.14.6
- Shell: `/bin/zsh`
- Ruby version (ruby -v): -

**Comment by katiedavis** [comment]
hey @philschoefer! this is due to lodash needing to be upgraded. I have a PR that removes lodash from the node app completely, and we're also working on suppressing output on the create command. Thank you!
