### ISSUE TITLE
generate webhook webhook name format

### ISSUE THREAD

**Issue by RaphArbuz** [Shopify/shopify-app-cli#301]
# Issue summary

Write a short description of the issue here ↓

On the list of supported webhooks in Shopify docs, webhooks are named in the "slash format" (i.e.: app/uninstalled) whereas to make the webhook registration work you need to time the webhook name in the "underscore format" (i.e.: APP_UNINSTALLED). I think it would be good if the command line would accept both formats. Shall I do a pull request for that?

**Comment by tanema** [comment]
Thanks @RaphArbuz I that is a good idea and if you are interested in contributing please go ahead!

**Comment by katiedavis** [comment]
Hi @RaphArbuz!

Our GraphQL API expects `underscore format` and our REST api expects the `/` format. I'm going to close this one for now.
