### ISSUE TITLE
Can't register the APP_SUBSCRIPTIONS_UPDATE webhook

### ISSUE THREAD

**Issue by RaphArbuz** [Shopify/shopify-app-cli#302]
# Issue summary

Write a short description of the issue here ↓

I cannot register the APP_SUBSCRIPTIONS_UPDATE webhook.
I'm getting a "Argument 'topic' on Field 'webhookSubscriptionCreate' has an invalid value. Expected type 'WebhookSubscriptionTopic!' error when the code runs.

Many thanks for any help

Raphael

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by RaphArbuz** [comment]
This is an API version issue. This webhook only started to be available with the 2019-07 API.
I fixed that by changing the code of koa-shopify-webhooks:
in register.js line 12 replace:
"/admin/api/graphql.json" by "/admin/api/2019-07/graphql.json"
There must be a better way to do it though!

**Comment by RaphArbuz** [comment]
Reading the doc of koa-shopify-webhooks, it seems like these lines of the server.js file: "
`  server.use(
    graphQLProxy({
      version: ApiVersion.July19
    })
  );
`
should set the version of the GraphiQL version used by koa-shopify-webhooks: to 2019-07 but it does not seem to. Any idea why?

**Comment by tanema** [comment]
This might be a better question for the team that maintains https://github.com/Shopify/quilt/tree/master/packages/koa-shopify-webhooks as we only delegate our commands to them. It seems like that is a bug because that line you changed is calling the unversioned api directly.

**Comment by RaphArbuz** [comment]
Thanks Tim. I've reached out to them and will update here if a solution shows up.

**Comment by amardeep9911** [comment]
@katiedavis Can you please look into this. This is a real issue. Unable to register webhooks available with the graphql 2019-07 API. 
As pointed out by @RaphArbuz, it just needs one single line change in the koa-shopify-webhooks  package to fix this issue. This package is also going in the official Shopify Node App as well as the Shopify App CLI.

> This is an API version issue. This webhook only started to be available with the 2019-07 API.
> I fixed that by changing the code of koa-shopify-webhooks:
> in register.js line 12 replace:
> "/admin/api/graphql.json" by "/admin/api/2019-07/graphql.json"
> There must be a better way to do it though!

**Comment by tanema** [comment]
@amardeep9911 Your comment is inappropriate. It is not okay to call out Katie directly, a developer with no current activity in this issue, about an issue on another repo.

You are also unaware of any work we are doing on this. Your belief that this is a single line fix is incorrect because that change is a hack. It does not comply with our future API versioning work.

If you behave in this way in the future, your access to open issues or comment on issues will be revoked.

**Comment by amardeep9911** [comment]
@tanema Buddy, I didn't know my suggestion would offend you so much. I had fixed it for myself and wanted to help fix for others. You won't need to revoke my access, I myself won't be commenting further in this repo.
Keep up the good work and have a great weekend ahead. 👍🏼

**Comment by katiedavis** [comment]
This has been fixed in the newest release of koa-shopify-webhooks. https://www.npmjs.com/package/@shopify/koa-shopify-webhooks
