### ISSUE TITLE
Can we use with rails 6 ?

### ISSUE THREAD

**Issue by karimgarcia** [Shopify/shopify-app-cli#303]
# Issue summary

Write a short description of the issue here ↓
The ruby version is 2.5.1 and I don't know how is it possible to upgrade it, to install rails 6 

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by karimgarcia** [comment]
thanks for these clarifications, I can't understand my problem, being in ruby 2.6.0, my "shopify serve" runs in 2.5.1 and I must to install all my gem with this version too otherwise the "shopify serve" doesn't launch. So I can't switch to rails 6 version....

➜  karim git:(master) ✗ ruby -v
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]

➜  karim git:(master) ✗ shopify serve
✓ ngrok tunnel running at  https://xxxxxxx.ngrok.io, with account Karim KG GARCIA
⭑ Press  Control-T to open this project in your browser
┏━━ Running server... ━━
┃ => Booting Puma
┃ => Rails 5.2.3 application starting in development 
┃ => Run `rails server -h` for more startup options
┃ Puma starting in single mode...
┃ * Version 3.12.1 (**ruby 2.5.1-p57**), codename: Llamas in Pajamas
┃ * Min threads: 5, max threads: 5
┃ * Environment: development
┃ * Listening on tcp://localhost:8081
┃ Use Ctrl-C to stop

**Comment by tanema** [comment]
Do you have `rvm` or `chruby` installed on your system? What ruby version is specified in your Gemfile? Do you have a `.ruby-version` file in the project?

**Comment by karimgarcia** [comment]
I have rvm installed, 
I can't specified my ruby version 2.6.0 in my gemfile because when I put it, I had this error when i launch shopify serve : 
 /Users/karimgarcia/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/definition.rb:495:in `validate_ruby!': Your Ruby version is 2.5.1, but your Gemfile specified 2.6.0 (Bundler::RubyVersionMismatch)
My .ruby-version is 2.6.0 in my project
Thank you

**Comment by tanema** [comment]
I would suggest you run gem install bundler or gem update bundler while using 2.6 and then try specifying your ruby version again in the Gemfile

**Comment by karimgarcia** [comment]
always the same error ..``` Your Ruby version is 2.5.1, but your Gemfile specified 2.6.0  ```
Even if we do that, it does not work. I was able to install rails 6 locally with ruby 2.5.1 and on my remote server I am in ruby 2.6.3, and it works because I don't use Shopify serve on my remote server.
That's fine with me, thank you Tim for helping me

**Comment by martinbottanek** [comment]
I'm also getting this error 

> Your Ruby version is 2.5.1, but your Gemfile specified 2.7.0 (Bundler::RubyVersionMismatch)

"shopify serve" won't run with Ruby version set to something other than 2.5.1

**Comment by tanema** [comment]
@martinbottanek Please open a new ticket
