### ISSUE TITLE
Allow flags to be passed to the underlying "rails new" command

### ISSUE THREAD

**Issue by dan-gamble** [Shopify/shopify-app-cli#312]
# Issue summary

Currently, I've been going [here](https://github.com/Shopify/shopify-app-cli/blob/master/lib/project_types/rails/commands/create.rb#L87) and following these steps but adding my own flags like `-d postgresql -T`, etc.

I'm relatively new to Ruby and Rails so maybe these things are actually really trivial to add on a freshly created app. Just figured it would be a nice to have.

**Comment by tanema** [comment]
Thanks, @dan-gamble this is a great suggestion. Switching from mysql to posgres after the app has already been generated is not hard but it is annoying! We will try to figure out how to accomodate this.
