### ISSUE TITLE
Rails generator problems

### ISSUE THREAD

**Issue by tanema** [Shopify/shopify-app-cli#323]
# Issue summary
There are some current issues with creating a rails app. Here are the following issues I found while working with @davidmuzi 

- We need to add the ngrok host to the config.hosts. config.hosts << “ngrok”, hosts accepts domains so we need to process ENV[‘HOST’]
~- secret was misnamed in the the initializer there is a mismatch between the cli and the gem. Our cli generates an env file that has SHOPIFY_API_SECRET_KEY and the gem is looking for ENV['SHOPIFY_API_SECRET']~
~- /auth should be /login in the docs~
- we don’t change the root path maybe we should generate a home controller as well to get them started on a shopify controller
- We should generate shop model as well during install so that they have something to track installs.

**Comment by katiedavis** [comment]
@tanema We do generate a home controller! we also generate a shop modal :)

**Comment by katiedavis** [comment]
I'm going to close this as all the issues have been addressed 🎉
