### ISSUE TITLE
undefined method `page_types' for ShopifyCli::AppTypes::Rails:Class

### ISSUE THREAD

**Issue by korakotlee** [Shopify/shopify-app-cli#327]
shopify generate page ProductList got error 
<details>
Traceback (most recent call last):
	21: from /home/korakot/.shopify-app-cli/bin/shopify:36:in `<main>'
	20: from /home/korakot/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	19: from /home/korakot/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	18: from /home/korakot/.shopify-app-cli/bin/shopify:37:in `block in <main>'
	17: from /home/korakot/.shopify-app-cli/lib/shopify-cli/entry_point.rb:16:in `call'
	16: from /home/korakot/.shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
	15: from /home/korakot/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	14: from /home/korakot/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	13: from /home/korakot/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	12: from /home/korakot/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	11: from /home/korakot/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:53:in `twrap'
	10: from /home/korakot/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	 9: from /home/korakot/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	 8: from /home/korakot/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	 7: from /home/korakot/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
	 6: from /home/korakot/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	 5: from /home/korakot/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
	 4: from /home/korakot/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	 3: from /home/korakot/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	 2: from /home/korakot/.shopify-app-cli/lib/shopify-cli/command.rb:16:in `call'
	 1: from /home/korakot/.shopify-app-cli/lib/shopify-cli/sub_command.rb:11:in `call'
/home/korakot/.shopify-app-cli/lib/shopify-cli/commands/generate/page.rb:15:in `call': undefined method `page_types' for ShopifyCli::AppTypes::Rails:Class (NoMethodError)
</details>

## Steps to reproduce the problem

1. shopify generate page ProductList
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: Rails
- Operating System: Ubuntu
- Shell: bash
- Ruby version (ruby -v): ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

**Comment by katiedavis** [comment]
Hi @korakotlee Thanks for opening this! Page generation is not currently available for Rails Apps.
