### ISSUE TITLE
Error on launch Shopify serve : SmartProperties::InitializationError

### ISSUE THREAD

**Issue by karimgarcia** [Shopify/shopify-app-cli#332]
# Issue summary

I got this error after updating  shopify-cli today.
smart_properties.rb:154:in `initialize': ShopifyCli::Helpers::EnvFile requires the following properties to be set: secret (SmartProperties::InitializationError)

Thank you for your help!

## Actual behavior

<detail>
onemorething_lite git:(master) shopify serve                                                                                        
Traceback (most recent call last):
	12: from /Users/karimgarcia/.shopify-app-cli/bin/shopify:36:in `<main>'
	11: from /Users/karimgarcia/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	10: from /Users/karimgarcia/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	 9: from /Users/karimgarcia/.shopify-app-cli/bin/shopify:37:in `block in <main>'
	 8: from /Users/karimgarcia/.shopify-app-cli/lib/shopify-cli/entry_point.rb:16:in `call'
	 7: from /Users/karimgarcia/.shopify-app-cli/lib/shopify-cli/executor.rb:12:in `call'
	 6: from /Users/karimgarcia/.shopify-app-cli/lib/shopify-cli/executor.rb:12:in `each'
	 5: from /Users/karimgarcia/.shopify-app-cli/lib/shopify-cli/executor.rb:13:in `block in call'
	 4: from /Users/karimgarcia/.shopify-app-cli/lib/shopify-cli/task.rb:7:in `call'
	 3: from /Users/karimgarcia/.shopify-app-cli/lib/shopify-cli/tasks/ensure_env.rb:8:in `call'
	 2: from /Users/karimgarcia/.shopify-app-cli/lib/shopify-cli/helpers/env_file.rb:18:in `read'
	 1: from /Users/karimgarcia/.shopify-app-cli/lib/shopify-cli/helpers/env_file.rb:18:in `new'
/Users/karimgarcia/.shopify-app-cli/vendor/deps/smart_properties/lib/smart_properties.rb:154:in `initialize': ShopifyCli::Helpers::EnvFile requires the following properties to be set: secret (SmartProperties::InitializationError)
</detail>

## Specifications

- App type: rails 6.0.0
- Operating System: MacOs
- Shell: Unix
- Ruby version (ruby -v): ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]

**Comment by PezCo** [comment]
Also getting this error on Windows using WSL Bash.

**Comment by tanema** [comment]
Hey, sorry about this but we introduced a breaking change. Of you change your `SHOPIFY_API_SECRET_KEY` to `SHOPIFY_API_SECRET` in your `.env` file it will work again!

**Comment by karimgarcia** [comment]
👌it's fine for me
