### ISSUE TITLE
Latest Release breaks existing build (ShopifyCli::OAuth::Error)

### ISSUE THREAD

**Issue by PezCo** [Shopify/shopify-app-cli#337]
# Issue summary

Latest shopify-cli update breaks an existing project build

## Actual behavior

<details>*****@DESKTOP-******:/mnt/d/Checkouts/08631-amrita-nutrition-app$ shopify serve
/home/*****/.shopify-app-cli/bin/support/load_shopify.rb:12: warning: Insecure world writable dir /mnt/c/ProgramData in PATH, mode 040777
✓ ngrok tunnel running at https://d8d170d6.ngrok.io
✓ ngrok tunnel running at https://d8d170d6.ngrok.io
open: ioctl(VT_GETSTATE): Inappropriate ioctl for device
This command ran with ID: 52941
Please include this information in any issues/report along with relevant logs
#<Thread:0x00007fffc237a518@/home/*****/.shopify-app-cli/lib/shopify-cli/oauth.rb:87 aborting> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        1: from /home/*****/.shopify-app-cli/lib/shopify-cli/oauth.rb:103:in `block in listen_local'
/home/*****/.shopify-app-cli/lib/shopify-cli/oauth.rb:102:in `ensure in block in listen_local': undefined method `close_write' for nil:NilClass (NoMethodError)
Traceback (most recent call last):
        33: from /home/*****/.shopify-app-cli/bin/shopify:36:in `<main>'
        32: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        31: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        30: from /home/*****/.shopify-app-cli/bin/shopify:37:in `block in <main>'
        29: from /home/*****/.shopify-app-cli/lib/shopify-cli/entry_point.rb:16:in `call'
        28: from /home/*****/.shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
        27: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        26: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
        25: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
        24: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
        23: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:53:in `twrap'
        22: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
        21: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        20: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
        19: from /home/*****/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
        18: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
        17: from /home/*****/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
        16: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
        15: from /home/*****/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
        14: from /home/*****/.shopify-app-cli/lib/shopify-cli/command.rb:22:in `call'
        13: from /home/*****/.shopify-app-cli/lib/shopify-cli/commands/serve.rb:15:in `call'
        12: from /home/*****/.shopify-app-cli/lib/shopify-cli/task.rb:7:in `call'
        11: from /home/*****/.shopify-app-cli/lib/shopify-cli/tasks/update_whitelist_url.rb:9:in `call'
        10: from /home/*****/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:34:in `query'
         9: from /home/*****/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:42:in `authenticated_req'
         8: from /home/*****/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:35:in `block in query'
         7: from /home/*****/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:53:in `api_client'
         6: from /home/*****/.shopify-app-cli/lib/shopify-cli/helpers/pkce_token.rb:6:in `read'
         5: from /home/*****/.shopify-app-cli/lib/shopify-cli/helpers/store.rb:37:in `get'
         4: from /home/*****/.shopify-app-cli/lib/shopify-cli/helpers/pkce_token.rb:7:in `block in read'
         3: from /home/*****/.shopify-app-cli/lib/shopify-cli/task.rb:7:in `call'
         2: from /home/*****/.shopify-app-cli/lib/shopify-cli/tasks/authenticate_identity.rb:14:in `call'
         1: from /home/*****/.shopify-app-cli/lib/shopify-cli/oauth.rb:57:in `authenticate'
/home/*****/.shopify-app-cli/lib/shopify-cli/oauth.rb:111:in `receive_access_code': Timed out while waiting for response from shopify (ShopifyCli::OAuth::Error)</details>

## Specifications

- Operating System: Windows 10
- Shell: WSL Bash
- Ruby version (ruby -v): ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

**Comment by PezCo** [comment]
Also getting same error when creating a new project.

After the cli asks What is your Application URL? what ever i put in gives the same error as above.

**Comment by riezahughes** [comment]
Having issues as well related to the latest update. On node when creating a new project It's asking for the application URL, but obviously i havn't been given it yet. Trying to serve an existing project hangs as well.

**Comment by riezahughes** [comment]
@tanema I am at least. I'm using the linux subsystem for it.

**Comment by tanema** [comment]
This does not seem to be fixed yet

**Comment by riezahughes** [comment]
Can confirm this still isn't working. My cli updated, but it's just erroring still.

**Comment by tanema** [comment]
Hey everyone, small update. I have made it now print out the authentication URL for you to click on or copy/paste into your browser to get you rolling again. Sorry about this. We will have a better implementation in the future. I am tracking it here: https://github.com/Shopify/shopify-app-cli/issues/343

**Comment by katiedavis** [comment]
Closing in favour of #343
