### ISSUE TITLE
shopify command not added to $PATH

### ISSUE THREAD

**Issue by SeanDez** [Shopify/shopify-app-cli#349]
# Issue summary

Write a short description of the issue here ↓

Running the install command only temporarily allows shopify CLI to work on my system. I must re-run the command each time I switch terminal sessions. I am also copying my $PATH output:

```
eval "$(curl -sS https://raw.githubusercontent.com/Shopify/shopify-app-cli/master/install.sh)"

owner@G700:~$ echo $PATH
/home/owner/.nvm/versions/node/v12.4.0/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/owner/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

## Expected behavior

shopify cli commands are available globally when using the shopify keyword, eg `shopify serve, shopify help`

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

```
shopify: command not found
```

## Steps to reproduce the problem

1. On Lubuntu 18.04 I run the install command that starts with eval "$(curl
2. I run shopify help to confirm it works
3. I switch directories or close/open a new terminal.
4. I rerun `shopify help` and see the `not found` message

## Specifications

- App type: When I attempt to find this I see:
```
owner@G700:~/PhpstormProjects/shopify/scriptTagEx$ shopify update
Development version of shopify in use. Run shopify load-system first.
owner@G700:~/PhpstormProjects/shopify/scriptTagEx$ shopify load-system
✓ Reloading Shopify App CLI from /run/user/1000/snap.phpstorm/.shopify-app-cli
bash: /run/user/1000/snap.phpstorm/.shopify-app-cli/shopify.sh: No such file or directory
```
- Operating System: Lubuntu 18.04
- Shell:
- Ruby version (ruby -v): ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

**Comment by tanema** [comment]
The line in your bash profile (it seems like you are using bash? please fill in that information in the future) Should be 

```
[ -f "~/.shopify-app-cli/shopify.sh" ] && source "~/.shopify-app-cli/shopify.sh"
```
 
If you add that to your shell config, you should be able to use the cli. Was there an error during installation?

**Comment by SeanDez** [comment]
Yes it is bash, I tried copy/pasting that line but it didn't do anything. Where should it be entered exactly?

```
owner@G700:~/PhpstormProjects/shopify/scriptTagEx$ [ -f "~/.shopify-app-cli/shopify.sh" ] && source "~/.shopify-app-cli/shopify.sh"
owner@G700:~/PhpstormProjects/shopify/scriptTagEx$ shopify
shopify: command not found

```

**Comment by SeanDez** [comment]
I tried to add it but still shopify app cli doesn't persist past a terminal session:

```
owner@G700:~$ sudo nano ~/.profile

// inside the file
# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

# shopify cli permanent $PATH addition
[ -f "~/.shopify-app-cli/shopify.sh" ] && source "~/.shopify-app-cli/shopify.sh"

// back to terminal
owner@G700:~$ shopify help
shopify: command not found
owner@G700:~$ eval "$(curl -sS https://raw.githubusercontent.com/Shopify/shopify-app-cli/master/install.sh)"
┏━━ 🦄  1/2: Installing Prerequisites ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ ✔︎ Successfully installed shopify-app-cli prerequisites
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┏━━ 🦄  2/2: Installing shopify-app-cli ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ ✔︎ already have shopify-app-cli
┃ ✔︎ shell set up for shopify-app-cli
┃ ✔︎ NOTE: added lines to the end of ~/.bash_profile and ~/.bashrc
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ shopify-app-cli is installed!
┃ Run shopify help to see what you can do, or read https://github.com/Shopify/shopify-app-cli.
┃ To start developing on shopify, for example:
┃   * run shopify create project <appname>
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
owner@G700:~$ shopify update
Development version of shopify in use. Run shopify load-system first.
owner@G700:~$ shopify load-system
✓ Reloading Shopify App CLI from /run/user/1000/.shopify-app-cli
bash: /run/user/1000/.shopify-app-cli/shopify.sh: No such file or directory
```

Could there be another issue stopping it from persisting? I still see the same issues when trying to update and then run `load-system`

**Comment by tanema** [comment]
- Do you get an error when you start your shell?
- Why is your home directory `/run/user/1000/`  does `/run/user/1000/.shopify-app-cli` exist? 
- Does Lubuntu do some sort of sandboxing to separate the user from tools?

**Comment by SeanDez** [comment]
No initial error, I believe my home directory is /home. The directory I am dropped into in a new session is /home/owner. No, the folder exists but I don't see that file. I am not aware of any sandboxing.

```
owner@G700:~$ pwd
/home/owner
owner@G700:~$ cd /run/user/1000/
owner@G700:/run/user/1000$ ls
bus     dconf  gvfs     menu-cached-:0     pulse          systemd
dbus-1  gnupg  keyring  pcmanfm-socket--0  snap.phpstorm  update-notifier.pid

```

**Comment by tanema** [comment]
okay well for some reason `~` in your bash profile does not refer to your home directory. Make sure
that `/home/owner/.shopify-app-cli` exists and then you can add the following line and it should work 

```
[ -f "/home/owner/.shopify-app-cli/shopify.sh" ] && source "/home/owner/.shopify-app-cli/shopify.sh"
```

**Comment by SeanDez** [comment]
I can see that hidden folder in my file manager. I then modified the bash
profile to replace ~ with /home/owner/ but it still doesn't seem to work.

```
owner@G700:~$ sudo nano ~/.profile
[sudo] password for owner:
owner@G700:~$ shopify help
shopify: command not found
```

**Comment by tanema** [comment]
I am sorry, there is something with your environment that I cannot understand. It may be how your OS operates that I am unfamiliar with. 

If you run `source "/home/owner/.shopify-app-cli/shopify.sh"` in your console. Does the shopify command work after that?

**Comment by SeanDez** [comment]
Looks like some kind of shell incompatibility. No worries, I can still manually run that eval command and it will always work after that, for that session. Here is what I saw when trying to execute the file with the absolute path:

```
owner@G700:~$ /home/owner/.shopify-app-cli/shopify.sh
shopify-cli is not compatible with your shell (shopify.sh)
owner@G700:~$ /home/owner/.shopify-app-cli/shopify.sh help
shopify-cli is not compatible with your shell (shopify.sh)

owner@G700:~$ shopify
shopify: command not found

owner@G700:~$ eval "$(curl -sS https://raw.githubusercontent.com/Shopify/shopify-app-cli/master/install.sh)"
┏━━ 🦄  1/2: Installing Prerequisites ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ ✔︎ Successfully installed shopify-app-cli prerequisites
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┏━━ 🦄  2/2: Installing shopify-app-cli ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ ✔︎ already have shopify-app-cli
┃ ✔︎ shell set up for shopify-app-cli
┃ ✔︎ NOTE: added lines to the end of ~/.bash_profile and ~/.bashrc
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ shopify-app-cli is installed!
┃ Run shopify help to see what you can do, or read https://github.com/Shopify/shopify-app-cli.
┃ To start developing on shopify, for example:
┃   * run shopify create project <appname>
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
owner@G700:~$ shopify

Available commands
Use shopify help [command] to display detailed information about a specific command.

shopify authenticate
Request a new access token from the Shopify Admin API.
  Usage: shopify authenticate

// rest of CLI output removed

```

**Comment by tanema** [comment]
Sorry hopefully we will have better console support in the near future but for now we are limited while in beta.

**Comment by BobbyCGD** [comment]
@SeanDez @tanema 

Hi guys,
So I experienced the exact same problem, running fresh install of Fedora 31. 

This command does make the 'shopify' command to work in terminal session only.
> `source "/home/owner/.shopify-app-cli/shopify.sh"`

So to make it permant I went ahead to update my 'bashrc' file

> `vim $HOME/.bashrc`

PLOT TWIST: 
The command is already at the bottom of the file but is wrapped with an IF statement to check:
> # load shopify-app-cli, but only if present and the shell is interactive
Deleting the IF statement altogether fixes the issue and the 'shopify' command is available with every any new terminal session!

**Comment by aisflat439** [comment]
Found the same thing running PopOS 18

> The command is already at the bottom of the file but is wrapped with an IF statement to check:
> 
> > # load shopify-app-cli, but only if present and the shell is interactive
> 
> Deleting the IF statement altogether fixes the issue and the 'shopify' command is available with every any new terminal session!

**Comment by mkevinosullivan** [comment]
As of v1.0.0 of the CLI (released mid July 2020), we no longer install via the `install.sh` script and no longer use the shell shim.  The new installation process (via `brew` or `apt` or `yum` or `gem`) should make `shopify` available via `PATH` and no longer modifies `.bashrc` or `.zshrc` or `.profile`, etc.
