### ISSUE TITLE
Can't have custom variables in .env file

### ISSUE THREAD

**Issue by fmontes** [Shopify/shopify-app-cli#362]
# Issue summary
I add AWS keys and secret to my `.env` but now wiht the latest update I can't because the `.env` file gets overwritten everytime we run `shopify serve`.

## Expected behavior
It should update the Shopify related variables.

## Actual behavior
Remove extra non-shopify variables

## Steps to reproduce the problem

1. Add some custom variable to `.env` file
2. Run `shopify serve`
3. See how your custom variable disappear.

## Reduced test case
N/A

## Specifications

- App type: NodeJS
- Operating System: OSX
- Shell: Bash
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

**Comment by tanema** [comment]
Hey, @fmontes thanks for the report. We are aware of this current behavior and we will be fixing this soon.

**Comment by fmontes** [comment]
Hi @tanema thank you very much.

**Comment by jasontll** [comment]
Hi guys, I am having the same issue too. 

For the moment I am doing below as a workaround, put this code block in your next.config file or in the server.js file.

```
if (fs.existsSync(".env.local")) {
  const envConfig = dotenv.parse(fs.readFileSync(".env.local"));
  for (const k in envConfig) {
    process.env[k] = envConfig[k];
  }
}
```

**Comment by tanema** [comment]
A fix has been merged! You should not have a problem any more
