### ISSUE TITLE
Default project - endless loop

### ISSUE THREAD

**Issue by notchris** [Shopify/shopify-app-cli#367]
# Issue summary

Write a short description of the issue here ↓

When installing the default project, I press Control+T to bring up up the app installation window. Then it constantly redirects between the hosted app page and shopify until it gives a warning about enabling third party cookies (which are enabled)."

## Expected behavior

What do you think should happen?

The app should install and the "Example React App" message should appear.

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by katiedavis** [comment]
Hi Chris,

Are you on Catalina using Chrome? Users have been having issue with Chrome and third party cookies (Chrome issue, not a CLI issue :) )
Try following these steps to purge your chrome data: 
https://crunchify.com/how-to-purge-all-your-google-chrome-user-data-on-mac-os-x/

Other users have reported deleting and uninstalling chrome, and reinstalling works as well.

**Comment by katiedavis** [comment]
Hey @notchris I'm going to close this issue but let me know if you have anymore issues with Chrome.
