### ISSUE TITLE
shopify generate webhook is adding "SHOPIFY_API_SECRET_KEY" instead of "SHOPIFY_API_SECRET"

### ISSUE THREAD

**Issue by abhinavpanse** [Shopify/shopify-app-cli#387]
# Issue summary
shopify generate webhook command in shopify cli is adding const
```
webhook = receiveWebhook({
      secret: SHOPIFY_API_SECRET_KEY
});
```

## Expected behavior

But it should add 
```
webhook = receiveWebhook({
      secret: SHOPIFY_API_SECRET
});
```
because it uses SHOPIFY_API_SECRET by default

## Specifications

- App type: Shopify app
- Operating System: Windows Ubuntu subsystem
- Shell: tmux
- Ruby version (ruby -v): 2.5.1

**Comment by katiedavis** [comment]
Hi @abhinavpanse!
We updated that const throughout the node app awhile ago, so I'm guessing you cloned your app about a month ago or before that?
In the newest version of the node app we use the `SHOPIFY_API_SECRET_KEY` const. On your end if you plan on generating webhooks just update your const in your `env` and `server` to match.
