### ISSUE TITLE
create project error

### ISSUE THREAD

**Issue by 0RaymondJiang0** [Shopify/shopify-app-cli#394]
I can't create any project using this cli, errors as below:

![image](https://user-images.githubusercontent.com/501182/68818741-e5f8d980-06c0-11ea-9620-421ec73d780e.png)

**Comment by tylerball** [comment]
Hey, it looks like your system ruby is up to date but you have `rvm` installed and that's selecting a really old version of ruby. If you don't use rvm anymore I would recommend uninstalling it with `rvm implode` or you could just remove that old ruby version with `rvm remove ruby-2.1.0`

**Comment by katiedavis** [comment]
I'm going to go ahead and close this but if you have any more issues selecting your version of ruby let us know.
