### ISSUE TITLE
Router Confusion

### ISSUE THREAD

**Issue by riezahughes** [Shopify/shopify-app-cli#399]
Node JS and Windows Linux.

I wasn't sure on the best way to ask about this, as it's information i've been missing. I understand it's not entirely related to the project but i feel a lot of people nonetheless may ask about it.

This project is great for straight up base url's using next. Being able to just make a page called products and go to the url /products is an amazing boon for building and saves a lot of time. 

The problem i'm having, however, is how to pass along url params to these. I'm unsure if there's a standardised way of doing this with this cli, if i need to use next router or if i need to use koa router. By default koa router wildcards to everything, so do i need to adjust the default koa calls to add ctx.query? 

One of shopifys most robust features for apps is the admin links, and as this passes these along i feel like this is a neccessary step that should at the very least have an example somewhere. If someone could explain this to me quickly here it would be doubly grand.

With all of these new technologies involved with this CLI it's quite easy to get lost.

Sorry for the hassle.

**Comment by ekwholesale** [comment]
This is correct in that it's easy to get lost. I've found adding this to your component works: 

```js
  static getInitialProps({query}) {
    return {query}
  }
```

Then you can call the query information using this.props.query. eg (this.props.query.id)

**Comment by riezahughes** [comment]
Sorted 👍
