### ISSUE TITLE
Using graphQL correctly with the CLI

### ISSUE THREAD

**Issue by ekwholesale** [Shopify/shopify-app-cli#401]
I've tried using the below code with the cli on a simple regular page. However each time i do it it's returning a 406?

```js
import { Component } from "react";
import { Query } from 'react-apollo';
import gql from "graphql-tag";

const CHECK_SHOP = gql`
query {
  shop {
    name
  }
}`;

export default class Product extends Component {
  render() {

    return (
      <div>
      <Query query={CHECK_SHOP}>
          {({ loading, error, data }) => {
            if (loading) return <div>Loading...</div>;
            if (error) return <div>Error :(</div>;
            return (
              <p>passed</p>
            );
          }}
        </Query>
      </div>
    );
  }
}
```

Additionally, what's the recommended way of working with graphql with what's generated by the CLI? I couldn't find any examples other than the mutations in the handler folder, but that doesn't explain too much either.

From a little bit of googling it looks like i just have to do react-apollo as normal as everythings already wrapped and set up. 

Let me know if i'm wrong though and that's why i'm getting this error.

**Comment by katiedavis** [comment]
Hi @ekwholesale,

You're right, we should provide a bit more information about working with GraphQL in the node app. You are using it correctly! I just generated an app and plunked your code into the index file and its displaying appropriately and I can fetch the shop name.
<img width="577" alt="Screen Shot 2019-11-15 at 2 05 15 PM" src="https://user-images.githubusercontent.com/15366319/68968702-3ea79f80-07b1-11ea-9f97-5d128941bc82.png">

Can you try clearing your cookies and reinstalling the app?

**Comment by ekwholesale** [comment]
So i ended up just making a new project overall and it seems to be fine now. Very strange. I'm making leaps and bounds now. Thank you for confirming it's working for me though.
