### ISSUE TITLE
`generate page` command fails

### ISSUE THREAD

**Issue by ErinRenNumber1** [Shopify/shopify-app-cli#409]
# Issue summary
I tried `generate page` command with different template types, and I get the same error below:
```
MacBook-Pro-99:server erinren$ shopify generate page configuration
? Which template would you like to use? (You chose: empty-state)
⠋ Generating empty-state page...
#<Thread:0x00007fa5e09a5168@/Users/erinren/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/spinner/spin_group.rb:43 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/spinner/spin_group.rb:46:in `block in initialize'
	4: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:120:in `run'
	3: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:91:in `with_stdin_masked'
	2: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:132:in `block in run'
	1: from /Users/erinren/.shopify-app-cli/lib/shopify-cli/commands/generate/page.rb:42:in `block in call'
/Users/erinren/.shopify-app-cli/lib/shopify-cli/commands/generate.rb:63:in `run_generate': {{x}} Error (CLI::Kit::Abort)
```
✗ Error

## Specifications

- App type: node
- Operating System: macos
- Shell: bash
- Ruby version (ruby -v): ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]

**Comment by tanema** [comment]
For some reason this is only an issue on your version of ruby. If you use a newer version of ruby this will succeed. I am not sure why though, because it seems like in ruby 2.5.1 the exit status of the generate command is 2. It should also have a better error message, and I am fixing that

**Comment by tanema** [comment]
I merged a fix for the errors message formatting. Can your run your command again so that we can see the actual error output?

**Comment by ErinRenNumber1** [comment]
I think I realize the problem.  I wasn't in the project directory.  Instead I was under the server directory.  Once I am in the project directory, it was fine.  I think this is where we could improve on making commands more context aware (ie, if not directly under a project directory, the `generate` command shouldn't exist, or should print some more useful errors).
