### ISSUE TITLE
The tool is installed, but any command within the app-cli tool fails with the same error

### ISSUE THREAD

**Issue by toneymathews** [Shopify/shopify-app-cli#411]
# Issue summary

Write a short description of the issue here ↓

I have been using this tool for the past two days. It worked well for creating apps, populating data etc.

As of now, any command fails with an invalid argument error. (shopify serve, shopify create project, shopify tunnel start)

Toneys-MacBook-Pro:app-projects toneymathews$ shopify help
/Users/toneymathews/.shopify-app-cli/lib/shopify-cli/log.rb:24:in `seek': Invalid argument @ rb_io_seek - /Users/toneymathews/.config/shopify/logs/events.log (Errno::EINVAL)
        from /Users/toneymathews/.shopify-app-cli/lib/shopify-cli/log.rb:24:in `tail'
        from /Users/toneymathews/.shopify-app-cli/lib/shopify-cli/monorail.rb:36:in `send_events'
        from /Users/toneymathews/.shopify-app-cli/lib/shopify-cli/entry_point.rb:23:in `before_resolve'
        from /Users/toneymathews/.shopify-app-cli/lib/shopify-cli/entry_point.rb:11:in `call'
        from /Users/toneymathews/.shopify-app-cli/bin/shopify:37:in `block in <main>'
        from /Users/toneymathews/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from /Users/toneymathews/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from /Users/toneymathews/.shopify-app-cli/bin/shopify:36:in `<main>'

## Expected behavior

What do you think should happen?

Ideally, it should create new projects or start a tunnel

## Actual behavior

What actually happens?

I did try uninstalling the application, clearing out the bash profile and reinstalling it. But all app-cli commands still fail with the same error.

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. Install the app-cli tool
2. run any command defined within the tool (shopify serve, shopify create project etc)

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: App-Cli
- Operating System:  Mac OS X. ProductVersion: 10.14.6. BuildVersion:   18G103
- Shell: GNU bash, version 5.0.11(1)-release
- Ruby version (ruby -v): I tried with 2.5.1 and 2.3.7

**Comment by tanema** [comment]
This has happened before: https://github.com/Shopify/shopify-app-cli/issues/408#issuecomment-558222281

The solution being `rm /Users/username/.config/shopify/logs/events.log`

We will fix this in a moment

**Comment by toneymathews** [comment]
Thanks a lot. that worked.
