### ISSUE TITLE
SHOPIFY_API_SECRET_KEY is not defined in server.js

### ISSUE THREAD

**Issue by codixir** [Shopify/shopify-app-cli#413]
SHOPIFY_API_SECRET_KEY is not defined in server.js.

The following error is thrown on the terminal, when a webhook is activated, 

`UnhandledPromiseRejectionWarning: ReferenceError: SHOPIFY_API_SECRET_KEY is not defined`

  const webhook = receiveWebhook({
    secret: SHOPIFY_API_SECRET_KEY
  });

This is found in `server.js`. And the SHOPIFY_API_SECRET_KEY does not match with the auto generated key that is in the `.env` file. 

The variable name should be `SHOPIFY_API_SECRET`.

**Comment by katiedavis** [comment]
Hi @codixir ! There was as breaking change introduced while we were in beta. The variable name is now SHOPIFY_API_SECRET_KEY. Please see this issue: 
https://github.com/Shopify/shopify-app-cli/issues/387
