### ISSUE TITLE
Update relevant Build an App pages with CLI callouts

### ISSUE THREAD

**Issue by davekilljoy** [Shopify/shopify-app-cli#42]
When the CLI launches to the public, we should update the Build an App tutorial with callouts to use the tool when it can replace manual work.

![Artboard](https://user-images.githubusercontent.com/1523373/56925244-e15e3200-6a9c-11e9-813a-c862fc9999e7.png)

- Set up your app
- Billing
- any others?

**Comment by katiedavis** [comment]
Closing this for now, we're going to evaluate this again soon.
