### ISSUE TITLE
The CLI tool does not prompt user to update the app url each time a new ngrok tunnel is started

### ISSUE THREAD

**Issue by toneymathews** [Shopify/shopify-app-cli#422]
# Issue summary

Each time a new ngrok tunnel is started, the cli tool does not prompt me to update the app url. 

## Expected behavior

What do you think should happen?

The tool should prompt me to update the new app url

## Actual behavior

What actually happens?

There is no prompt.
The whitelisted urls are updated though app url is not in the partners dashboard.
As of now, I have to manually go to the partners dashboard and update it.

<img width="753" alt="Screen Shot 2019-12-13 at 9 25 44 AM" src="https://user-images.githubusercontent.com/19610799/70808251-472dce80-1d8d-11ea-9e8a-5df7c70bb36f.png">

## Steps to reproduce the problem

1. each time a tunnel gets expired, I start a new one using 'shopify tunnel stop' and 'shopify tunnel start'
1. start the server in 'shopify serve'
1. Update the app url in the partners dashboard

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: Shopify App CLI
- Operating System: macOS 10.14.6 (18G103)
- Shell: GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0)
- Ruby version (ruby -v): ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18

**Comment by gbossh** [comment]
It also duplicated the whitelisted ngrok url to me:
![image](https://user-images.githubusercontent.com/22305677/70821259-9df4d180-1da8-11ea-9227-27b83016801f.png)
