### ISSUE TITLE
shopify generate webhook ... "SHOPIFY_API_SECRET_KEY" instead of "SHOPIFY_API_SECRET"

### ISSUE THREAD

**Issue by oneezy** [Shopify/shopify-app-cli#427]
I saw the other 3 issues related to this: #387, #395 and #413 

however, it's still an issue w/ the newest version of Shopify App CLI, as I just installed the latest version a few days ago.

> NOTE: I'm using the node/react starter

**Comment by tanema** [comment]
Sorry can you give us some more information. The key should have nothing to do with you generating webhooks. If this error happened then it means you generated an app while the CLI was in beta and we have since then changed the name on the environment variable.

What is your actual error, and where is it coming from?

**Comment by oneezy** [comment]
thanks for your response @tanema 

when i create a new project with `shopify create project my-new-app`, the secret api key variable that it creates everywhere is `SHOPIFY_API_SECRET` _(as opposed to `SHOPIFY_API_SECRET_KEY`)_.

when i run `shopify generate webhook` and select any option, it creates and references the variable `SHOPIFY_API_SECRET_KEY`, and it doesn't have any reference to that. 

so I'm guessing the `shopify create project` needs to be updated with the `SHOPIFY_API_SECRET_KEY` variables?

**Comment by tanema** [comment]
No, the create project command has it correct, it is the webhook generation that has it wrong however. I found the issue here https://github.com/Shopify/app-cli-node-generator-helper/blob/82c7732c3c5dbd67d25745d1ad6c9b93196b7a9b/webhook/generate-webhook-environment.js#L6 in our support library

**Comment by oneezy** [comment]
ahh i see. that makes sense. So I guess that just needs to be patched on your guys end and i'll wait for an update 😃

**Comment by tanema** [comment]
Okay if you update the app-cli-node-generator-helper package this should be fixed now
