### ISSUE TITLE
Issues deploying to Zeit Now, Netlify

### ISSUE THREAD

**Issue by joshgosse** [Shopify/shopify-app-cli#431]
# Issue summary

Deploying to Zeit Now and Netlify both seem to fail during the build phase. Running the app works for me locally. 

-- EDIT: Looks like this was because I was using `next-optimized-images` and for whatever reason it wasn't pulling it's own dependencies properly --

Two basic issues which are resolved (maybe?) by adding `url-loader` and `file-loader` to `package.json`:

`Module not found: Can't resolve 'url-loader' in '/opt/build/repo'`
`Module not found: Can't resolve 'file-loader' in '/opt/build/repo'`

After adding these two dependencies I then get:

-- End edit --

```
> Build error occurred
--
07:36:34 AM | { Invariant Violation:
07:36:34 AM | fetch is not found globally and no fetcher passed, to fix pass a fetch for
07:36:34 AM | your environment like https://www.npmjs.com/package/node-fetch.
07:36:34 AM | For example:
07:36:34 AM | import fetch from 'node-fetch';
07:36:34 AM | import { createHttpLink } from 'apollo-link-http';
07:36:34 AM | const link = createHttpLink({ uri: '/graphql', fetch: fetch });
07:36:34 AM | at new InvariantError (/zeit/5b3a87e2/.next/serverless/pages/index.js:263:28)
07:36:34 AM | at Object.module.exports.mqhy.exports.checkFetcher (/zeit/5b3a87e2/.next/serverless/pages/index.js:62840:15)
07:36:34 AM | at Object.module.exports.v7Jj.exports.createHttpLink (/zeit/5b3a87e2/.next/serverless/pages/index.js:67526:31)
```

Now, I think I have fixed this issue, by configuring both instances of ApolloClient simply by doing the following:
```
import fetch from "isomorphic-fetch"; 
...
const client = new ApolloClient({
  fetch,
  ...
});
```

After you apply these fixes to your app, deploys to Zeit Now actually work, however attempting to visit its URL just spins indefinitely and nothing happens. To get the deploy working on Netlify I also had to add `"export": "npm run build && next export"` to `package.json` and update the build parameter in their admin. After deploying to Netlify, the same thing happens (infinite spinning)

Thanks a lot team! Otherwise local development has been pretty breezy minus the slight learning curve around learning Next, but otherwise things have been enjoyable!

## Expected behavior

Deploys to Zeit Now and Netlify should/could work out of the box.

## Actual behavior

See above description.

## Steps to reproduce the problem

See above description.

**Comment by joshgosse** [comment]
Never mind, just realized there's a `shopify deploy heroku` command and it only supports Heroku, so there's that!

**Comment by tomgs** [comment]
Sidenote: The `shopify-app-cli` (in its `node`-mode) creates a [custom Next.js server](https://nextjs.org/docs/advanced-features/custom-server).
AFAIK, `now` does not support custom Next.js servers: 
https://github.com/zeit/next.js/issues/9397#issuecomment-556215227

**Comment by jamescrowley** [comment]
Just linking this to https://github.com/Shopify/shopify-app-node/issues/108 as they're related (if we use the NextJS routes rather than a custom server then I think ^^ would work)
