### ISSUE TITLE
"Select a Development Store" caps at 20 stores

### ISSUE THREAD

**Issue by carlosreyes** [Shopify/shopify-app-cli#434]
# Issue summary

Write a short description of the issue here ↓

When creating a new project, after selecting the project type (node) and choosing my organisation, only the first page worth of stores (sorted by last login) are loaded and it is not possible to access further pages

I have worked around this by logging into said development store and trying again, however we have many developers working on many stores so it's not a guarantee that a project is in the last 20 logged in stores when I am creating an app for it

## Expected behavior

What do you think should happen?

The CLI should pull in all stores or allow me to switch between pages manually

## Actual behavior

What actually happens?
It loads the latest 20 logged in stores and the one I am trying to target is inaccessible

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. `shopify create project xxxxxxxx`
2. Choose project type
3. Choose organisation

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: node
- Operating System: osx 10.14.4
- Shell: `fish`
- Ruby version (ruby -v): `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]`

**Comment by tanema** [comment]
Hey @carlosreyes thanks for reporting this. This is interesting because I dont think we put a limit on the shops but I will take a look soon.

**Comment by carlosreyes** [comment]
> Hey @carlosreyes thanks for reporting this. This is interesting because I dont think we put a limit on the shops but I will take a look soon.

I don't believe it is explicitly capped, it's just only pulling in the first page worth of results.

**Comment by tanema** [comment]
Okay I expanded the amount we request in our queries. Let me know if this has not fixed your issues.

**Comment by carlosreyes** [comment]
Thanks for the fast turnaround on this @tanema !

Unfortunately, it seems it has not fixed the issue - I can confirm that I have updated the app - I can see your commit in a `git log` of my `~/.shopify-app-cli` and a quick peek at the changed files can confirm your changes are in my local version. There are still only 20 stores being pulled in.

I am assuming it is the same query that is being ran at https://partners.shopify.com/xxxxxx/stores to populate that ResourceList - the gql query running on that page includes `"pageInfo":{"hasNextPage":true,"hasPreviousPage":false,"__typename":"PageInfo"},` - not sure why requesting the first 500 hasn't worked, my gql isn't that strong, but hopefully this is helpful to debug things on your end!

**Comment by tanema** [comment]
Okay I will take a further look, the problem may lay within the partners API instead then

**Comment by tanema** [comment]
Okay I have expanded the page limit on the API this should be fixed now

**Comment by ginagregory** [comment]
I am only getting 30 stores, and the dev store I want to use is not listed. What can I do?
