### ISSUE TITLE
Choice between "Public" and "Custom" app type?

### ISSUE THREAD

**Issue by ezmiller** [Shopify/shopify-app-cli#448]
# Issue summary

When you run `shopify create project` you are given some choices, but whether you'd like the script to create a "Custom" or "Public" app type in your partner account does not appear to be  one of them.

## Expected behavior

When you run `shopify create project` you should be able to specify what type of Shopify app you are intending to develop, `Custom` or `Public`.

## Steps to reproduce the problem

1. Run `shopify create project <some-app-name>`
1. Locate the new app it has created in Shopify's app list for your partner account
1. Note that it is a "Public" app

**Comment by tanema** [comment]
Hey @ezmiller thanks for opening the issue. We are working on this currently!

**Comment by ezmiller** [comment]
@tanema thanks for letting me know. Is there any temporary hack available?

**Comment by tanema** [comment]
create an app with the command line, then create and app in the Partners dash of the type that you want and then switch the api key and secret in your local app config

**Comment by tanema** [comment]
This has been added as part of our most recent release.
