### ISSUE TITLE
[Error] shopify create project - domain cannot contain "Shopify"

### ISSUE THREAD

**Issue by eni9889** [Shopify/shopify-app-cli#452]
# Issue summary

Write a short description of the issue here ↓

I am running `shopify create project` and using rails backend and am getting the following error:

```
✗ ["input", "application_url"] domain cannot contain "Shopify", ✗ ["input", "redirect_url_whitelist"] domain cannot contain "Shopify"
```

## Specifications

- App type: rails embedded app
- Operating System: Macos
- Shell: zsh
- Ruby version (ruby -v): 2.5.1p57

**Comment by eni9889** [comment]
To get it to work I had to get rid of 
```
app_url: 'https://shopify.github.io/shopify-app-cli/getting-started'
```

As well as 

```
REDIRECT_HOST = "http://app-cli-loopback.shopifyapps.com:#{DEFAULT_PORT}"
```

**Comment by katiedavis** [comment]
Hi @eni9889, there was a change to an API that has been reverted. Can you let me know if you see this error again? Thanks!
