### ISSUE TITLE
Values in `.env` aren't loaded into Rails' `ENV` global

### ISSUE THREAD

**Issue by mattdrose** [Shopify/shopify-app-cli#453]
# Issue summary

None of the `.env` values are available after authentication with your Partner account. This means certain steps, like oauth, which require these values, like `client_id`, throw errors.

## Expected behavior

The `.env` values should be available. This can be done by having 'dotenv-rails' installed with the Rails app.

## Steps to reproduce the problem

1. Go through the process of setting up a Rails app
1. Choose your Partner account and development store
1. Try to install the app with the store

## Specifications

- App type: Rails
- Operating System: macOS Catalina: 10.15.1 (19B88)
- Shell: iTerm2 (bash)
- Ruby version (ruby -v): 2.6.5p114

**Comment by katiedavis** [comment]
Thanks Matt!

**Comment by katiedavis** [comment]
Matt was having issues due to running the internal 'dev' command, we inject the env variables in the serve command. If you choose to run the app outside of shopify serve, you'll need to install dot env.
