### ISSUE TITLE
[Request] SPA React with Rails API backend

### ISSUE THREAD

**Issue by eni9889** [Shopify/shopify-app-cli#457]
I wasn't sure where how to post this but I was wondering if there are any plans to add the ability for this tool to generate an SPA app using polaris and react for the frontend and rails api only for the backend. If not are there any guides or tutorials out there on how to best do this? My biggest confusion is around authentication and I think an official template would be very helpful.

**Comment by katiedavis** [comment]
Hi @eni9889 at this time we don't have any plans to add a Rails/React app type. You can most likely create a rails app with the shopify-app-cli and add react. Something like this might help!
https://www.freecodecamp.org/news/how-to-create-a-rails-project-with-a-react-and-redux-front-end-8b01e17a1db/

That way you can use the built in auth in the shopify_app gem.

All the best!
