### ISSUE TITLE
CLI Polish-Error message-Generate command

### ISSUE THREAD

**Issue by kwringe** [Shopify/shopify-app-cli#460]
# Issue summary
Low priority
The word **abort** appears in the output that is returned as part of an error message for the Generate command. If I were to guess, the output for this error is accidentally showing internal commands and content.

``` `run_generate': ✗ A page with this name kate already exists. **(CLI::Kit::Abort)**
✗ A page with this name kate already exists.```

Write a short description of the issue here ↓

How to reproduce:
1) Run the generate command and create a page with the name mypage.
2)After the page is created, rerun the same command. 

What you'll see:

A) Weird output that I think should be suppressed from the CLI

 ```#<Thread:0x00007fc1b590f0f0@/Users/katewringe/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/spinner/spin_group.rb:43 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /Users/katewringe/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/spinner/spin_group.rb:46:in `block in initialize'
	4: from /Users/katewringe/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:120:in `run'
	3: from /Users/katewringe/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:91:in `with_stdin_masked'
	2: from /Users/katewringe/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:132:in `block in run'
	1: from /Users/katewringe/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/commands/generate/page.rb:42:in `block in call'
/Users/katewringe/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/commands/generate.rb:63:in `run_generate':
```

B) Duplicate error messages. The first contains the word abort (from the internal CLI kit )
 
``` `run_generate': ✗ A page with this name kate already exists. **(CLI::Kit::Abort)**
✗ A page with this name kate already exists.```

## Expected behavior

What do you think should happen?
The "weird output" and the first error message (that includes the reference to the CLI kit should not appear).

## Specifications

Shopify App CLI
Node app
Generate command

**Comment by ErinRenNumber1** [comment]
I don't think this fix is needed for the internal preview.

**Comment by ErinRenNumber1** [comment]
I am going to close it, as it's to be addressed in CLI framework.
