### ISSUE TITLE
Bundler version error when running `shopify serve`

### ISSUE THREAD

**Issue by andrewhassan** [Shopify/shopify-app-cli#466]
# Issue summary

After creating a new Rails app using `shopify create app myappname`, I get an error saying that I must use Bundler 2.

## Expected behavior

The Rails server should run successfully.

## Actual behavior

What actually happens?

I get the following error:
![image](https://user-images.githubusercontent.com/1742857/76459119-035d5c00-63b2-11ea-82b0-377a4fa3cfc9.png)

## Steps to reproduce the problem

1. Create a new app: `shopify create app myapp`
2. Select Rails as the app type in the prompt
3. Run `shopify serve`

## Specifications

- App type: Rails
- Operating System: Mac OS 10.15.3
- Shell: zsh
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

## Note

After installing Bundler with `gem install bundler:2.1.4`, I get the error described [here](https://github.com/Shopify/shopify-app-cli/issues/461) except it is **not** successful running in a new terminal instance.

**Comment by tanema** [comment]
I am not sure this is an issue and I am not sure we *should* solve this. You got output what was wrong and then you ran the command it was fixed. This would be a problem if you were running `rails s` as well.
