### ISSUE TITLE
`shopify serve` fails to run

### ISSUE THREAD

**Issue by andrewhassan** [Shopify/shopify-app-cli#467]
# Issue summary

After creating a new Rails app using `shopify create app my-app-name`, I run `shopify serve` and get the following error:
```
/Users/andrew/.gem/ruby/2.6.3/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize': Could not find nio4r-2.5.2 in any of the sources (Bundler::GemNotFound)
```

## Expected behavior

The Rails server should run successfully.

## Actual behavior

What actually happens?

I get the following error output:
![image](https://user-images.githubusercontent.com/1742857/76529741-18d19500-6449-11ea-955d-38f27ac39635.png)

## Steps to reproduce the problem

1. Create a new app: `shopify create app myapp`
2. Select Rails as the app type in the prompt
3. Run `shopify serve`

## Specifications

- App type: Rails
- Operating System: Mac OS 10.15.3
- Shell: zsh
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

**Comment by katiedavis** [comment]
hey @andrewhassan we're tracking this issue [here](https://github.com/Shopify/shopify-app-cli/issues/461) I'm going to close this one but please see the comments in #461

**Comment by andrewhassan** [comment]
@katiedavis, yeah it looks similar except the chruby workaround doesn't seem to work for me. I'll comment in the issue you linked 😄
