### ISSUE TITLE
shopify generate produces error

### ISSUE THREAD

**Issue by Werbelow** [Shopify/shopify-app-cli#468]
# Issue summary

I added the cli to an existing project by adding the `.shopify-cli.yml` file to my project with this in it:
```---
app_type: :node
```
I saw that somewhere that was how to do it. 

`shopify serve` works just fine, however, when I go to generate a page or billing, it throws the same error.

I have tried re-authenticating the cli with no luck.

## Expected behavior

It should generate the billing/page code and file(s)

## Actual behavior

I run `shopify generate billing`, I am able to choose which type of billing I want, and then it throws the following error: (same error no mater the type of thing being generated)

```
shopify generate billing 
? How would you like to charge for your app? (You chose: recurring-billing)
⠋ Generating recurring-billing code ...
#<Thread:0x00007ffd0087e560@/Users/Travis/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/spinner/spin_group.rb:43 run> terminated with exception (re
port_on_exception is true):
Traceback (most recent call last):
        5: from /Users/Travis/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/spinner/spin_group.rb:46:in `block in initialize'
        4: from /Users/Travis/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:120:in `run'
        3: from /Users/Travis/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:91:in `with_stdin_masked'
        2: from /Users/Travis/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:132:in `block in run'
        1: from /Users/Travis/.shopify-app-cli/lib/shopify-cli/commands/generate/billing.rb:27:in `block in call'
/Users/Travis/.shopify-app-cli/lib/shopify-cli/commands/generate.rb:63:in `run_generate': ✗ Error (CLI::Kit::Abort)
```

## Steps to reproduce the problem

1. add shopify-cli to existing project 
1. run shopify generate billing
1. select either billing method

## Specifications

- App type: Node
- Operating System: macOS 10.15.3
- Shell: Hyper
- Ruby version (ruby -v): ruby 2.6.3p62

**Comment by katiedavis** [comment]
Hi! Is this app our shopify-app-node? The CLI isn’t set up currently to hook into preexisting projects

**Comment by Werbelow** [comment]
@katiedavis it's a slightly older version of the Shopify Nextjs tutorial. I was hoping to use the CLI to update my project's billing and webhooks. 

Ah gotcha. My bad. It's a great CLI for creating a new project, I made a test one and it worked great. I'll use that generated code as an example for updating my project then.

Thanks!
