### ISSUE TITLE
caniuse-lite is outdated

### ISSUE THREAD

**Issue by theoldbarn** [Shopify/shopify-app-cli#481]
# Issue summary

Write a short description of the issue here ↓
When running the server, I run into the following error:

┃ Browserslist: caniuse-lite is outdated. Please run next command `npm update`
┃ > Ready on http://localhost:8081
┃ [ wait ]  compiling ...
┃ [ event ] build page: /
┃ [ wait ]  compiling ...

## Expected behavior

What do you think should happen?
Prompted to then enter in API key etc.

## Actual behavior

What actually happens?
Error message - see above.

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by tanema** [comment]
please open this issue on https://github.com/Shopify/shopify-app-node
