### ISSUE TITLE
Not being asked for Shopify Key or Secret Key

### ISSUE THREAD

**Issue by theoldbarn** [Shopify/shopify-app-cli#483]
# Issue summary

Write a short description of the issue here ↓
Under 'getting started' you will see the following text:

> Create a new app project
> The create command will scaffold a new Shopify app in your current active directory and generate all the necessary starter files.
> 
> $ shopify create project APP_NAME
> The CLI will ask what type of app you want to create. Two languages are currently supported:
> 
> Node.js and React
> Ruby
> The CLI will also ask for your app’s API key and API secret, which you can find in your Partner Dashboard (see “Requirements” above).

However, upon installation "The CLI will also ask for your app’s API key and API secret, which you can find in your Partner Dashboard (see “Requirements” above)" does not happen... instead the `shopify serve` command just goes on forever.

## Expected behavior

What do you think should happen?
I should be asked for my Shopify Key and Secret Key

## Actual behavior

What actually happens?
Timeout.

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by tanema** [comment]
Sorry we will fix the help message however when you create the app with the cli it now creates the configuration for you. You can find it in your `.env` file. You will not be prompted for it unless your .env file is missing

**Comment by theoldbarn** [comment]
Thank you tanema, for your assistance.

So when I'm running the server and see the following:

> Browserslist: caniuse-lite is outdated. Please run next command `npm update`
> Ready on http://localhost:8081
> [ wait ]  compiling ...

Aside from just wait, what should I do? This seems to be something that takes a very long time to compile.

Thanks, again :)

**Comment by tanema** [comment]
Does it complete? It usually takes a little while at start up.

**Comment by theoldbarn** [comment]
Not yet, but that's perhaps because of my impatience.
When you say a while, is that 5 minutes or like 50?

**Comment by tanema** [comment]
Try running `npm run dev` and check the output from that.

**Comment by neil-rubens** [comment]
I had the same problem.  This what happened to work for me.

execute `shopify serve`  see the link to ngrok:

> ✓ ngrok tunnel running at https://<YOUR_HASH>.ngrok.io

you need to open it in your browser; you'll probably see a message "Expected a valid shop query parameter"

you may want to terminate shopify cli; and then restart it again; then hopefully it will work
