### ISSUE TITLE
shopify-cli: can't create project - authentication error?

### ISSUE THREAD

**Issue by adamfaryna** [Shopify/shopify-app-cli#484]
# Issue summary

The command `shopify create project` doesn't work as expected. After choosing an account it shows an error in the browser and in the local console.

## Expected behavior

The command should create new project workspace, and work as expected.

## Actual behavior

When I run command:
`shopify create project app2`

The browser opens, I choose the account and later I get error page `An error occurred during a connection to app-cli-loopback.shopifyapps.com:3456. PR_END_OF_FILE_ERROR`.
And the console shows:

    ? What type of app project would you like to create? (You chose: node embedded app)
    #<Thread:0x00007f96110b75f8@/Users/devil/.shopify-app-cli/lib/shopify-cli/oauth.rb:89 run> terminated with exception (report_on_exception is true):
    Traceback (most recent call last):
    1: from /Users/devil/.shopify-app-cli/lib/shopify-cli/oauth.rb:93:in `block in listen_local'
    /Users/devil/.rbenv/versions/2.6.3/lib/ruby/2.6.0/uri/common.rb:455:in `decode_www_form': the input of URI.decode_www_form must be ASCII only string (ArgumentError)
    This command ran with ID: 12848
    Please include this information in any issues/report along with relevant logs
    Traceback (most recent call last):
    1: from /Users/devil/.shopify-app-cli/lib/shopify-cli/oauth.rb:93:in `block in listen_local'
    /Users/devil/.rbenv/versions/2.6.3/lib/ruby/2.6.0/uri/common.rb:455:in `decode_www_form': the input of URI.decode_www_form must be ASCII only string (ArgumentError)

## Steps to reproduce the problem

1. Create new Private App in shop admin panel
1. Allow all priviledges and permissions to admin API
1. run `shopify create project app2`

## Specifications

- App type: Private, Custom app,
- App priviledges: all priviledges selected and granted 
- Operating System: Mac OS 10.14.6
- Shell: bash & zsh
- Ruby version (ruby -v): 2.6.3

**Comment by adamfaryna** [comment]
@tanema thanks for fast reply.

Here is the url https://app-cli-loopback.shopifyapps.com:3456/?code=code_content&state=68f855b73ee3ed35ff8b12d93bb8ddcbd976b075ac6e93c50ed279fe0507

**Comment by tanema** [comment]
Interesting, I expected to see something different in there. The error seems to imply that the response URL has utf8 in it but I don't see anything problematic. I just checked that URL just in case and it is all ascii.

Can you just verify the code is ASCII? It all *should* be because URLs are supposed to be ascii only

**Comment by adamfaryna** [comment]
@tanema yes, it is ASCII.

**Comment by tanema** [comment]
Yup! It is running an OAuth authentication flow. It opens your browser to check that you are authenticated, and if you are then you are redirected to that loopback URL which actually points at your own computer. That is how we communicate that code and state back to the commandline.

So upon receiving a 

```
GET /?code=code_content&state=68f855b73ee3ed35ff8b12d93bb8ddcbd976b075ac6e93c50ed279fe0507 HTTP/1.0
```

It tried to then parse out those parameters. That is where it is going wrong. Let me see if I can find out why this is happening.

**Comment by tanema** [comment]
Hey! I just merged a fix that I think will work. try running `shopify update` and then trying again.

**Comment by adamfaryna** [comment]
@tanema Thank you very much!

I updated and I have another error. This happens when I click my profile to login:
```
adam-macBook:shopify devil$ shopify create project warmwanted2
? What type of app project would you like to create? (You chose: node embedded app)
This command ran with ID: 85844                                                                                                                                                                             
Please include this information in any issues/report along with relevant logs                                                                                                                               
Traceback (most recent call last):
	41: from /Users/devil/.shopify-app-cli/bin/shopify:36:in `<main>'
	40: from /Users/devil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	39: from /Users/devil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	38: from /Users/devil/.shopify-app-cli/bin/shopify:37:in `block in <main>'
	37: from /Users/devil/.shopify-app-cli/lib/shopify-cli/entry_point.rb:15:in `call'
	36: from /Users/devil/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:28:in `invocation'
	35: from /Users/devil/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:44:in `event'
	34: from /Users/devil/.shopify-app-cli/lib/shopify-cli/entry_point.rb:16:in `block in call'
	33: from /Users/devil/.shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
	32: from /Users/devil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	31: from /Users/devil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	30: from /Users/devil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	29: from /Users/devil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	28: from /Users/devil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	27: from /Users/devil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	26: from /Users/devil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	25: from /Users/devil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	24: from /Users/devil/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
	23: from /Users/devil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	22: from /Users/devil/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
	21: from /Users/devil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	20: from /Users/devil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	19: from /Users/devil/.shopify-app-cli/lib/shopify-cli/command.rb:16:in `call'
	18: from /Users/devil/.shopify-app-cli/lib/shopify-cli/sub_command.rb:12:in `call'
	17: from /Users/devil/.shopify-app-cli/lib/shopify-cli/commands/create/project.rb:15:in `call'
	16: from /Users/devil/.shopify-app-cli/lib/shopify-cli/forms.rb:14:in `ask'
	15: from /Users/devil/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:13:in `ask'
	14: from /Users/devil/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:45:in `organization'
	13: from /Users/devil/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:37:in `organizations'
	12: from /Users/devil/.shopify-app-cli/lib/shopify-cli/helpers/organizations.rb:6:in `fetch_all'
	11: from /Users/devil/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:34:in `query'
	10: from /Users/devil/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:42:in `authenticated_req'
	 9: from /Users/devil/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:35:in `block in query'
	 8: from /Users/devil/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:53:in `api_client'
	 7: from /Users/devil/.shopify-app-cli/lib/shopify-cli/helpers/pkce_token.rb:6:in `read'
	 6: from /Users/devil/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `get'
	 5: from /Users/devil/.shopify-app-cli/lib/shopify-cli/helpers/store.rb:37:in `get'
	 4: from /Users/devil/.shopify-app-cli/lib/shopify-cli/helpers/pkce_token.rb:7:in `block in read'
	 3: from /Users/devil/.shopify-app-cli/lib/shopify-cli/task.rb:7:in `call'
	 2: from /Users/devil/.shopify-app-cli/lib/shopify-cli/tasks/authenticate_identity.rb:15:in `call'
	 1: from /Users/devil/.shopify-app-cli/lib/shopify-cli/oauth.rb:60:in `authenticate'
/Users/devil/.shopify-app-cli/lib/shopify-cli/oauth.rb:134:in `receive_access_code': Anti-forgery state token does not match the initial request. (ShopifyCli::OAuth::Error)
```

And the in the Firefox:
```
Secure Connection Failed

An error occurred during a connection to app-cli-loopback.shopifyapps.com:3456. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

```

**Comment by tanema** [comment]
Hrm! I will have to talk to our DNS people to figure out why that would happen! Can you also try logging out of all Shopify services and trying again? The state token not matching is really confusing.

**Comment by adamfaryna** [comment]
Ok, I logged out from all the services. I had to login in the browser window when requested, but after that exactly the same error occurs.

**Comment by AbdulRafay** [comment]
Any fix to this issue? I am trying to setup shopify-app-cli on my Ubuntu VM and running into similar issue.

**Comment by tanema** [comment]
You can try working around it by changing the `app-cli-loopback.shopifyapps.com:3456` URL to just `localhost:3456`

**Comment by sdn90** [comment]
Ran into this problem using NextDNS. Using my ISP's DNS works fine.

**Comment by thomfoolery** [comment]
+1

I'm running into this same problem.

<img width="1493" alt="Screen Shot 2020-04-07 at 4 49 29 PM" src="https://user-images.githubusercontent.com/188110/78718145-c2dcf980-78ef-11ea-8a6e-a879b199bacd.png">

<img width="955" alt="Screen Shot 2020-04-07 at 4 48 38 PM" src="https://user-images.githubusercontent.com/188110/78718094-a771ee80-78ef-11ea-9ad8-4ac8952ec191.png">

**Comment by tanema** [comment]
Did 2 browser windows open by any chance? Or any chance you ran the command twice? I can understand how to state would get lost or not match. I will check with the authentication team about this, maybe there are restrictions on the state token that I have not matched. Sorry about the inconvienience

**Comment by thomfoolery** [comment]
@tanema No it just opened in my default browser FireFox. I tried switching my default browser Chrome and trying again but no luck, I've switched back now. I should have mentioned I'm trying out Scripts V2 internal beta and have installed https://github.com/Shopify/temp-shopify-app-cli and initialized it with `shopify load-dev ~/src/github.com/Shopify/temp-shopify-app-cli`

**Comment by tanema** [comment]
Okay I worked on this for a while with @thomfoolery and we figured it out. I should have noticed before that your callback URL was https. The CLI cannot handle an SSL request. If you have an extension that is auto-redirecting traffic to https you may have to add an exception for `app-cli-loopback.shopifyapps.com:3456`

**Comment by thomfoolery** [comment]
Note: 
this seems to be a FireFox thing. I do not have any extensions for the purpose of redirecting traffic to https.

<img width="702" alt="Screen Shot 2020-04-08 at 11 49 44 AM" src="https://user-images.githubusercontent.com/188110/78805145-0cc8ec80-798f-11ea-8d51-a2ff64b67d1e.png">

<img width="695" alt="Screen Shot 2020-04-08 at 11 49 55 AM" src="https://user-images.githubusercontent.com/188110/78805165-13576400-798f-11ea-9c10-ba4dd86b2530.png">

**Comment by tanema** [comment]
It seems pretty strictly tied into firefox. I might have to just distribute self signed certs to account for this

**Comment by maximebedard** [comment]
Any update on this one? I'm also getting the same issue, and using firefox too. What did you end up using locally to make this work?

**Comment by thomfoolery** [comment]
I ended up switching my default browser to chrome, and then back afterwards

**Comment by tanema** [comment]
We are looking at distributing certs for the loopback domain so that our local instance can handle SSL requests.
If we cannot do this, we may just have to fallback to deploying a service that has SSL and displays the token for the user to copy and paste. Not, ideal

**Comment by damianed** [comment]
I just ran into a similar issue using firefox seems to work fine with chrome, this is the stack trace
```
Traceback (most recent call last):
        43: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/bin/shopify:32:in `<main>'
        42: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        41: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        40: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/bin/shopify:33:in `block in <main>'
        39: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/core/entry_point.rb:42:in `call'
        38: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/core/monorail.rb:20:in `log'
        37: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
        36: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/core/executor.rb:15:in `call'
        35: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        34: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        33: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        32: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        31: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        30: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        29: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        28: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        27: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-ui/lib/cli/ui.rb:172:in `log_output_to'
        26: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        25: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        24: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        23: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        22: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/commands/create.rb:8:in `call'
        21: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/command.rb:19:in `call'
        20: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/sub_command.rb:12:in `call'
        19: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/project_types/node/commands/create.rb:16:in `call'
        18: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/form.rb:13:in `ask'
        17: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/project_types/node/forms/create.rb:13:in `ask'
        16: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/task.rb:7:in `call'
        15: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/tasks/select_org_and_shop.rb:11:in `call'
        14: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/tasks/select_org_and_shop.rb:38:in `get_organization'
        13: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/tasks/select_org_and_shop.rb:27:in `organizations'
        12: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api/organizations.rb:6:in `fetch_all'
        11: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api.rb:48:in `query'
        10: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api.rb:56:in `authenticated_req'
         9: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api.rb:49:in `block in query'
         8: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api.rb:67:in `api_client'
         7: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api.rb:73:in `access_token'
         6: from /usr/lib/ruby/2.7.0/forwardable.rb:235:in `get'
         5: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/db.rb:87:in `get'
         4: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api.rb:74:in `block in access_token'
         3: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api.rb:86:in `authenticate'
         2: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/oauth.rb:43:in `authenticate'
         1: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/oauth.rb:148:in `request_exchange_token'
/var/lib/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/oauth.rb:169:in `post_token_request': Invalid 'subject_token' value: invalid (ShopifyCli::OAuth::Error)
```
