### ISSUE TITLE
React dev tools with embedded app

### ISSUE THREAD

**Issue by chris-geelhoed** [Shopify/shopify-app-cli#492]
# Issue summary

I could be missing something, but I can't figure out how to view an app with React dev tools if it is embedded. Having this available would really help out my dev workflow!

This issue may be more relevant to the Shopify app bridge package.

## Expected behavior

It would be nice if I could inspect my React app components and state with the dev tools.

## Actual behavior

What actually happens?

React dev tools doesn't have access to my apps code. It just shows the native Shopify admin React components that exist outside my app's embedded iframe.

The general procedure for inspecting a react app inside an iframe is shown at https://github.com/facebook/react-devtools/issues/76, but this method currently throws an error as JavaScript from within the iframe is of different origin.

My app also uses Redux. Using the redux dev tools currently gives some visibility to what is happening with App bridge, but I'm more interested in what is happening within my own Redux store.

**Comment by tanema** [comment]
This is not a CLI issue

**Comment by alexormrod** [comment]
@chris-geelhoed Did you ever find a work around for this?

All the solutions I've come across get hit with CORS issues (require the parent to be same domain as the iframe).

**Comment by ltakens** [comment]
Use the [standalone version](https://www.npmjs.com/package/react-devtools) for embedded apps.
