### ISSUE TITLE
Plus Sandboxes not supported for public apps

### ISSUE THREAD

**Issue by iflam** [Shopify/shopify-app-cli#493]
# Issue summary

Write a short description of the issue here ↓
When connecting a new app via `shopify create` you can choose a plus sandbox store... but then when you go to install it, it denies the oauth as public apps need to be approved first. As well, when you try to click 'Add to Development Store' within the app interface, none of the Plus Sandboxes appear.

## Expected behavior

What do you think should happen?
Since Plus Sandboxes are development stores, they should be listed in the 'Add to development stores' list, and you should be able to add it to the sandbox.

## Actual behavior

What actually happens?
Oauth denies authentication.

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error
<details>This app needs to be reviewed by Shopify before it can be installed. Contact the app developer for more information about this app.</details>

## Steps to reproduce the problem

1. Run `shopify create project <name>`
2. Select a sandbox store when it prompts you.
3. Run `shopify serve`
4. Press Control-T to open the project on the sandbox store
5. Error.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: Public
- Operating System: Mac OS
- Shell: zshell
- Ruby version (ruby -v): Node 10+

**Comment by tanema** [comment]
This was just fixed as part of our most recent release.
