### ISSUE TITLE
Heroku Deployment Fails on Fresh Project

### ISSUE THREAD

**Issue by andrewhassan** [Shopify/shopify-app-cli#495]
# Issue summary

On a fresh project, I made an initial commit, and ran `shopify deploy heroku`. A new app on Heroku was created as expected, but the CLI failed to set the `heroku` remote, which caused the code to **not** get deployed.

## Expected behavior

The app should get deployed to Heroku.

## Actual behavior

A Heroku app gets created but the code is not deployed.

![image](https://user-images.githubusercontent.com/1742857/78040941-1ffc0c80-733e-11ea-9c6b-4849a7d2a5ba.png)

## Steps to reproduce the problem

1. Create a new Shopify project: `shopify create project myapp`
2. Make an initial commit: `git add . && git commit -m "Initial commit"`
3. Deploy to Heroku: `shopify deploy heroku`
4. Choose "Create a new Heroku app"

## Specifications

- App type: Rails
- Operating System: Mac OS 10.15.4
- Shell: zsh
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]
- Heroku version: heroku/7.39.2 darwin-x64 node-v12.13.0

**Comment by andrewhassan** [comment]
I took a look at this and found what's causing it. When you have a new repo (no `heroku` remote) and you attempt to create a new Heroku app, the CLI will attempt to:

1. Create a Heroku app with the Heroku tools
2. Add the `heroku` remote

The issue is that the Heroku tools add the `heroku` remote, which causes the CLI to fail on the second step since the remote is already created.

**Comment by ayronshopify** [comment]
This should now be resolved. New deploys should no longer fail on the first run due to `remote heroku already exists`
