### ISSUE TITLE
Can't create new app

### ISSUE THREAD

**Issue by dave-pelletier** [Shopify/shopify-app-cli#507]
# Issue summary

I'm getting an error `Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib` whenever I run the `shopify create app` command:

```
MacBook-Pro:scripts-v2 davepelletier$ shopify create app scripts-test
? What type of app project would you like to create? (You chose: rails embedded app)
[Note] You cannot use gems in shopify-cli.                                                                                                                                                                             
[LoadError] dlopen(/usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/x86_64-darwin18/digest/sha2.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib                                               
  Referenced from: /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/x86_64-darwin18/digest/sha2.bundle
  Reason: image not found - /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/x86_64-darwin18/digest/sha2.bundle
       They are disabled.
       If you are modifying /opt/shopify-cli, please don't.
       TODO with contribution instructions
```

## Specifications

- App type: rails
- Operating System: mac os 10.15.4
- Shell: bash
- Ruby version (ruby -v): 2.6.3p62

**Comment by tanema** [comment]
Please contact the scripts team. It looks like they have added a gem and this looks like an issue with their non-public functionality

**Comment by ErinRenNumber1** [comment]
Sorry, I don't think it's related to any non-public functionalities specific to scripts commands.  This occurred after he installed CLI, and any `shopify` command resulted in this error.  Just adding more info here from what I saw on Slack.  He got a new Mac, and doesn't have everything installed yet, and therefore `dev up` on `shopify` doesn't even work yet.  
<img width="1028" alt="Screen Shot 2020-04-13 at 5 53 55 PM" src="https://user-images.githubusercontent.com/39379964/79164956-26639d00-7db0-11ea-8ab3-04f4d09844dd.png">
As you can see, after installing CLI, `load-dev` doesn't even work to be able to point to the `temp-shopify-app-cli` yet.

**Comment by tanema** [comment]
Okay, we will take another look. @dave-pelletier do you have an issue with OpenSSL on any other project? Are you using your system ruby version?

**Comment by dave-pelletier** [comment]
Thanks @tanema . I haven't had any issues with other projects so far. How do I know if I'm using the system ruby version? Here's what `ruby -v` and `chruby` tell me:
```
MacBook-Pro:~ davepelletier$ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
MacBook-Pro:~ davepelletier$ chruby
   2.5.1
   2.5.3
   2.5.5
   2.6.3
   2.6.5
```

**Comment by tanema** [comment]
Yeah that is the system ruby (the darwin postfix gives it away) I recommend switching ruby versions. The system ruby often will work but often will not based on permissions. It also is harder to fix because you are unable to re-install gems without the use of `sudo` which if you are having openssl problems, it probably started after a system update and you would need to reinstall the SSL gems with the `--pristine` option.

**Comment by dave-pelletier** [comment]
Got it, thanks Tim. I'll give this a try

**Comment by dave-pelletier** [comment]
Worked, thanks!
