### ISSUE TITLE
Selecting browser windown on create app workflow

### ISSUE THREAD

**Issue by ttonelli** [Shopify/shopify-app-cli#509]
# Issue summary

If I issue a `shopify create app name` command, I am prompted with some questions and then the cli tries to open a browser for me to authenticate with partners. There are 2 issues:

1) I cannot choose which browser window to use. If I have various profiles in Firefox, Chrome and Safari, I may want to use a specific one to authenticate (I don't want to mix personal, work and testing sessions).

2) there's no indication whatsoever on why I need to authenticate with partners at all. By looking a bit at source code I figured the first part was just trying to get my `organization_id` and `shop_domain` (which I can pass as arguments to the command), but at the end it tries to auth again and there's no clue why (maybe something related to `api_client_id`?).

## Expected behavior

A) I would expect to be told what's going on before trying to open a tab on my browser.

B) I would expect to be able to provide all the information needed as arguments, to avoid having to open a browser at all.

C) If there's no other way than to open a browser, I would expect to be able to select which window to open (or at the very least get a link that I can copy and past to the window I want). 

## Actual behavior

1) the cli tries to open a tab in a browser I don't want to use to authenticate with partners, and then it times out. If I pass `organization_id` and `shop_domain` on the command line I can at least finish the scaffolding of the app, but at the end it tries to auth again.

2) there's no feedback on what is being done.

## Steps to reproduce the problem

1. open a few browser windows with different profiles (e.g Firefox and Chrome)
2. `shopify create app foo`
3. one of the browsers will open the tab, not necessarily the one you want

## Workaround

There is a workaround for some cases. The https://www.choosyosx.com/ app allows you to select a browser when opening a link in OSX. However, it cannot select specific profiles for Firefox, and it is paid after 44 days. Also, it does not solve the lack of feedback issue.

**Comment by tanema** [comment]
I think since a lot of people are having this problem and it really only works to auto-open the URL on MacOS I will just disable auto-opening. Most people can click URLs in their consoles these days and copy them to a different browser if they wish.

**Comment by tanema** [comment]
> A) I would expect to be told what's going on before trying to open a tab on my browser.
Fair, we can add an `authenticating` message

>B) I would expect to be able to provide all the information needed as arguments, to avoid having to open a browser at all.
You can, but the CLI creates the ApiClient for you. We cannot do that without authentication.

> C) If there's no other way than to open a browser, I would expect to be able to select which window to open (or at the very least get a link that I can copy and past to the window I want). 
This is incredibly complicated especially cross platform. We will just disable it and make you click a link

**Comment by ttonelli** [comment]
Cool, thanks. I like the idea of just giving me the link :-)!

I don't think just saying `authenticating` is enough. Why are you authenticating me? In my personal opinion we should not dumb this down. The target audience is developers, so we should give more details because they understand. I would love to understand, for example, that the ApiClient is being created for me and that's why I need to authenticate.

**Comment by ayronshopify** [comment]
Hi @ttonelli, I've made an update to not auto-open the authentication window anymore. You may need to run `shopify update` to see that change. We opted for the time being not to add specific messaging around the reason for authentication as the calls are currently coming from a lot of different places in the code, but we're looking at refactoring some of this so that we can make it more transparent to the user in the future.
