### ISSUE TITLE
Heroku Deploy Fails Due to SQLite

### ISSUE THREAD

**Issue by andrewhassan** [Shopify/shopify-app-cli#513]
# Issue summary

When deploying a generated Rails app to Heroku, the deployment fails because the app uses SQLite, which is unsupported in Heroku.

Heroku has [instructions](https://devcenter.heroku.com/articles/sqlite3) on how to use PostgreSQL instead of SQLite. Perhaps these steps could be automated by the CLI. If not, I think the user should at least be made aware that it won't work **before** starting the deploy since it takes a while to install a bunch of dependencies before failing.

## Expected behavior

It should deploy to Heroku.

## Actual behavior

The deploy fails due to SQLite not being support in Heroku.

## Log
[heroku-fail.txt](https://github.com/Shopify/shopify-app-cli/files/4458701/heroku-fail.txt)

## Steps to reproduce the problem

1. Create a new Rails app: `shopify create project yourapp`
2. Deploy to Heroku: `shopify deploy heroku` (it may fail the first time, but should work the second time)

## Specifications

- App type: Rails
- Operating System: Mac OS 10.15.4
- Shell: zsh
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

**Comment by tanema** [comment]
> Perhaps these steps could be automated by the CLI. 

This is making design decisions for the developer that we would end up supporting. I don't think this is the best decision.

>If not, I think the user should at least be made aware that it won't work before starting the deploy since it takes a while to install a bunch of dependencies before failing.

I think we might be able to check the configuration for sqlite before trying to deploy.

**Comment by tanema** [comment]
Also, did you find the root of your problems with https://github.com/Shopify/shopify-app-cli/issues/495

**Comment by andrewhassan** [comment]
I just had a chance to look into it. I figured out the issue and will leave a comment in there :)
