### ISSUE TITLE
`msgpack` incompatible library version error when running `shopify serve`

### ISSUE THREAD

**Issue by dmcvittie** [Shopify/shopify-app-cli#515]
# Issue summary

When using `temp-shopify-app-cli` locally, trying to run `shopify serve` results in the following error occuring. Error below.

## Expected behavior

The server should run

## Actual behavior

```
/Users/ttonelli/.gem/ruby/2.6.3/gems/msgpack-1.3.3/lib/msgpack.rb:11:in `require': incompatible library version - /Users/ttonelli/.gem/ruby/2.6.3/gems/msgpack-1.3.3/lib/msgpack/msgpack.bundle (LoadError)
┃ 	from /Users/ttonelli/.gem/ruby/2.6.3/gems/msgpack-1.3.3/lib/msgpack.rb:11:in `rescue in <top (required)>'
┃ 	from /Users/ttonelli/.gem/ruby/2.6.3/gems/msgpack-1.3.3/lib/msgpack.rb:8:in `<top (required)>'
┃ 	from /Users/ttonelli/.gem/ruby/2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/store.rb:4:in `require'
┃ 	from /Users/ttonelli/.gem/ruby/2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/store.rb:4:in `block in <top (required)>'
┃ 	from /Users/ttonelli/.gem/ruby/2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/explicit_require.rb:44:in `rescue in with_gems'
┃ 	from /Users/ttonelli/.gem/ruby/2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/explicit_require.rb:40:in `with_gems'
┃ 	from /Users/ttonelli/.gem/ruby/2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/store.rb:4:in `<top (required)>'
┃ 	from /Users/ttonelli/.gem/ruby/2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache.rb:74:in `require_relative'
┃ 	from /Users/ttonelli/.gem/ruby/2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache.rb:74:in `<top (required)>'
┃ 	from /Users/ttonelli/.gem/ruby/2.6.3/gems/bootsnap-1.4.6/lib/bootsnap.rb:4:in `require_relative'
┃ 	from /Users/ttonelli/.gem/ruby/2.6.3/gems/bootsnap-1.4.6/lib/bootsnap.rb:4:in `<top (required)>'
┃ 	from /Users/ttonelli/.gem/ruby/2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/setup.rb:2:in `require_relative'
┃ 	from /Users/ttonelli/.gem/ruby/2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/setup.rb:2:in `<top (required)>'
┃ 	from /Users/ttonelli/src/github.com/Shopify/ttb-scripts-preview/config/boot.rb:4:in `require'
┃ 	from /Users/ttonelli/src/github.com/Shopify/ttb-scripts-preview/config/boot.rb:4:in `<top (required)>'
┃ 	from bin/rails:3:in `require_relative'
┃ 	from bin/rails:3:in `<main>'
```

## Steps to reproduce the problem

1. `shopify load-dev <path-to-temp-cli>`
2. Create an app
3. `shopify serve`

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by dmcvittie** [comment]
I was able to get my local environment running again by doing the following in a new tab:

1. `shopify load-dev <path-to-temp-cli>`
2. `dev update`
3. `gem install bundler:1.17.3`
4. `bundle install`
5. `shopify serve`

However, this didn't work for @ttonelli

**Comment by tanema** [comment]
This seems like an issue with the generated scripts code and not the CLI. Please contact the scripts team about this.

**Comment by jacobsteves** [comment]
No I don't think this is related to scripts. We don't touch any of the app generation code. `msgpack` is a dependency used by `bootsnap` which is specified in new rails 5.2 projects. So I think this is dependency issue related to generating a new rails app type.

**Comment by ErinRenNumber1** [comment]
Yes, sorry, I am not sure how this is specific to Scripts.  None of those commands above is related to scripts code.  I would really appreciate some more help with this one!  ❤️

**Comment by tanema** [comment]
@jacobsteves @ErinRenNumber1 scripts do no implement the serve command? If this is case then @dmcvittie please run `rails s` and if that raises the same issue then open the issue on shopify_app

**Comment by ErinRenNumber1** [comment]
@tanema: no Scripts doesn't implement the `serve` command.  @dmcvittie was trying to serve up an app from within an app project context.  Thank you!

**Comment by tanema** [comment]
@dmcvittie Have you confirmed if this is shopify_app or not?

**Comment by tanema** [comment]
I am closing this for now because it is stale and has not been witnessed again. Please open a new issue if this appears again.
