### ISSUE TITLE
Heroku Pipelines: when promoting, staging SHOPIFY_API_KEY is passed into production

### ISSUE THREAD

**Issue by patryk-smc** [Shopify/shopify-app-cli#516]
# Issue summary

Hi everyone!
I have set up Heroku pipeline with staging and production dynos. Whenever I promote from staging to production, SHOPIFY_API_KEY is passed into production, as Heroku doesn't rebuild app during promotion. This causes Shopify App Bridge error: APP::ERROR::INVALID_CONFIG. Is there any way around this?

Related issue: https://stackoverflow.com/questions/45064842/heroku-pipeline-staging-env-variable-carried-into-production

## Expected behavior

Environment variables should always match the environment. 

## Actual behavior

What actually happens?

Staging SHOPIFY_API_KEY env variable is passed into production. That causes Shopify App Bridge error:

<details>
APP::ERROR::INVALID_CONFIG: Provided apiKey `xxx` is incorrect. Expecting `yyy`
</details>

## Steps to reproduce the problem

1. Create two Shopify node apps (staging, production)
2. Create Heroku dyno for each app
3. Create Heroku pipeline
4. Add apps to pipeline
5. Promote app from dyno 1 to dyno 2
6. Dyno 2 will use SHOPIFY_API_KEY of dyno 1, Shopify App Bridge will return error

## Specifications

- App type: node
- Operating System: macOS
- Shell: zsh
- Ruby version (ruby -v): 2.7

**Comment by tanema** [comment]
If the app does not rebuild during promotion, do you not have other issues with environment variables like database hosts and secrets? If it does not rebuild, I would expect that you stage a production build and then promote that instead of using a different set of variables. I have not used pipelines that much so I am no expert but that is my impression.

**Comment by patryk-smc** [comment]
@tanema All other variables are pulled directly from the runtime, so everything else works. Next.js is hard-coding the SHOPIFY_API_KEY with its build, as you can see it here: https://github.com/Shopify/shopify-app-node/blob/master/next.config.js

**Comment by patryk-smc** [comment]
Got this sorted out by using [Next Runtime Configuration](https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration)
