### ISSUE TITLE
Generate Billing not available as documentation suggests

### ISSUE THREAD

**Issue by lemonadecreative** [Shopify/shopify-app-cli#533]
The `shopify generate billing` command does not work in a new rails app, and outputs message "Generate code in your app project. Currently supports generating new webhooks."

Is this deprecated or called by a different name? 

Can the ReadMe file be updated or a a link posted to get current info?

**Comment by Mohaiyo** [comment]
+1

**Comment by tanema** [comment]
`shopify generate billing` is only currently supported on node apps and not rails apps. We will update the readme to reflect this.

**Comment by paulbaudrier** [comment]
Any update schedule for support generate billing on rails apps ?

**Comment by tanema** [comment]
Not for a while. Generating code to add billing to a rails app is not as straightforward as rails. We have an issue here https://github.com/Shopify/shopify-app-cli/issues/115 tracking this.

**Comment by felixmpaulus** [comment]
Running `shopify generate billing` inside a node app returns 

`Command not found 
shopify create was not found`

Cant find anything in the documentation either. Does the command still exist?

**Comment by heyFahad** [comment]
> Nope, I don't think so - where did you hear about this command (outside of this issue)?

I saw this command on this [HackerNoon blog](https://hackernoon.com/how-to-setup-shopifys-billing-api-6r1q3udr) today. But this command does not seem to work for me either. Does this mean that we can no longer generate sample code?
