### ISSUE TITLE
Show current project context for help command

### ISSUE THREAD

**Issue by attaboy** [Shopify/shopify-app-cli#557]
When running `shopify help`, it would be good to have a reminder of what context you're in so it's clearer why the list of commands changes. So if you're inside a project, it should say something like:

```console
$ shopify help
CLI to help build Shopify apps faster.

Use shopify help <command> to display detailed information about a specific command.

Project: my_project (Node app)
Available commands for Node app projects:
```

/cc @gfscott @iainmcampbell 

We may also went to extend this contextual reminder to other commands besides help if their behavior differs across project types or depending on whether you're in a project or not.

**Comment by iainmcampbell** [comment]
How would we show the division between 'global' and 'local' commands?

```
$ shopify help
CLI to help build Shopify apps faster.

Use shopify help <command> to display detailed information about a specific command.

Project: my_project (Node app)
Available commands for Node app projects:

shopify connect
Connect a Shopify-App-Cli project. Restores the ENV file
  Usage: shopify connect

...

Available global commands:

shopify update
Update Shopify App CLI.
  Usage: shopify update

...
```

**Comment by iainmcampbell** [comment]
`core` sounds great!

**Comment by gfscott** [comment]
I suggest dropping `CLI to help build Shopify apps faster.` — they're already using the thing, I don't think we need to keep selling them on it, and we can save two lines of screen real estate.

**Comment by attaboy** [comment]
@gfscott Yeah, I could get behind that. 👍

**Comment by andyw8** [comment]
How does this look? 

<img width="601" alt="Screen Shot 2020-05-04 at 11 48 02 AM" src="https://user-images.githubusercontent.com/13400/80985388-2843dd80-8dfd-11ea-964f-66c2c75179ac.png">

(I'm not displaying the project path yet).

**Comment by gfscott** [comment]
I believe we decided on `core` over `global`, so:

- `Available core commands`
- `Available commands for Rails app projects`

Also we should be consistent in using a colon (or not) after those headings. I prefer **with**!

**Comment by andyw8** [comment]
Ah, sorry, I thought `core` meant the Rails or Node commands... I'll update that, and the punctuation.
