### ISSUE TITLE
Supported Ruby versions?

### ISSUE THREAD

**Issue by andyw8** [Shopify/shopify-app-cli#595]
In #594 I tried to update RuboCop. The build is failing because we're testing against 2.3 but the latest RuboCop needs Ruby 2.4.

What's our policy on which Ruby versions to support?

Ruby 2.3 and 2.4 are both EOL:
https://www.ruby-lang.org/en/downloads/

**Comment by andyw8** [comment]
@tanema

**Comment by tanema** [comment]
I think we have had this discussion before and said yes 2.5+ but a few things need to be updated to reflect that.

**Comment by andyw8** [comment]
I see we're already enforcing `~>2.4` here, but only for Rails:

https://github.com/Shopify/shopify-app-cli/blob/1ccd307bfbdeb1132fc80457ac625b1de32e20e1/lib/project_types/rails/commands/create.rb#L26-L27

**Comment by andyw8** [comment]
Closed by #606
