### ISSUE TITLE
Populate command relies on undocumented .env setting

### ISSUE THREAD

**Issue by ow** [Shopify/shopify-app-cli#650]
# Issue summary
After creating a new app with the CLI, I wanted to populate my dev store with some products. I ran the `shopify populate` command for the first time. It spat out a URL with no domain to visit:
```
❯ shopify populate products
𝒾 Authentication required. Login to the URL below with your development store credentials to continue.
Please open this URL in your browser:
https:/admin/oauth/authorize?client_id=[redacted]&scope=write_products%2Cwrite_customers%2Cwrite_draft_orders&redirect_uri=http%3A%2F%2F127.0.0.1%3A3456&state=[redacted]&response_type=code&grant_options%5B%5D=per+user
``` 

This was confusing, so I went hunting, and discovered that there is supposed to be a `SHOP` key in my `.env` file with the URL of my development store. This isn't documented on the CLI guide, and the format is very specific: `SHOP=owens-test-store-is-great.myshopify.com` (no HTTP etc).

I believe this happened because I didn't have a dev store when I generated my app, so it didn't add one to the `.env` file, but the lack of documentation on this would also trip people up as it's likely folks will want to use this on projects *not* generated by the CLI.

## Expected behavior

Document that there needs to be a `SHOP` key with the development store URL in the `.env` file to run `shopify populate`

What do you think should happen?
Not needing to read the code to find the magical key :)

**Comment by tanema** [comment]
This should actually just be a validation that we have a development store and prompt the user to pick on then.
