### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by tylerball** [Shopify/shopify-app-cli#71]
If we can serialize all the help text into translated YAML we could probably provide a configuration setting for language and read from it based on that. I think command names and arguments will have to remain in English since these are defined in code and I think would be too confusing otherwise anyway.

**Comment by paulomarg** [comment]
This was addressed by https://github.com/Shopify/shopify-app-cli/pull/587, so now all the messages printed by the CLI are centralized in a single file per module.
