### ISSUE TITLE
Shopify CLI doesn't work after sudden update, returns undefined method `report_on_exception=' for Thread:Class (NoMethodError)

### ISSUE THREAD

**Issue by Petar-np** [Shopify/shopify-app-cli#714]
# Issue summary

Shopify CLI doesn't work after updating

Write a short description of the issue here ↓

I tried to run Shopify CLI command accidentally passing wrong argument `shopify --help` and an automatic update was triggered. After that Shopify CLI stopped working because of some Ruby problem,

## Expected behavior

When running Shopify CLI commands everything should work fine

What do you think should happen?

`shopify help` should return help output, and `shopify create` should create new project

## Actual behavior

Whatever the command is output is the same, error message about undefined method in `.shopify-app-cli/lib/shopify_cli.rb`

What actually happens?

```
/Users/developera/.shopify-app-cli/lib/shopify_cli.rb:5:in `<top (required)>': undefined method `report_on_exception=' for Thread:Class (NoMethodError)
	from /Users/developera/.shopify-app-cli/bin/shopify:9:in `require'
	from /Users/developera/.shopify-app-cli/bin/shopify:9:in `require'
	from /Users/developera/.shopify-app-cli/bin/support/load_shopify.rb:16:in `<top (required)>'
	from /Users/developera/.shopify-app-cli/bin/shopify:27:in `require_relative'
	from /Users/developera/.shopify-app-cli/bin/shopify:27:in `<main>'
```

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. Update Shopify CLI
2. Run any command

## Specifications

- Operating System: macOS Mojave 10.14.5
- Shell: zsh 5.7.1 (x86_64-apple-darwin18.2.0)
- Ruby version (ruby -v): ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]

**Comment by mkevinosullivan** [comment]
Hi, the version of Ruby required should be at least 2.4.0 in order to support the `report_on_exception=` method. Please update your version of Ruby.

**Comment by Petar-np** [comment]
Thanks @mkevinosullivan, you were right. That solved the "problem"
