### ISSUE TITLE
"shopify populate was not found"

### ISSUE THREAD

**Issue by guillaume-chevalier** [Shopify/shopify-app-cli#721]
# Issue summary

I tried to do: 
```
shopify populate products --count 17
```

## Expected behavior

My dev store to be populated

## Actual behavior

```
$ shopify populate products --count 17
┏━━ Command not found ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ shopify populate was not found
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

<details>
```
$ shopify populate products --count 17
┏━━ Command not found ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ shopify populate was not found
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```
</details>

## Steps to reproduce the problem

1. Install the shopify cli on Linux Mint (related issue: https://github.com/Shopify/shopify-app-cli/issues/261 it worked for me by updating git then by doing `SKIP_PREREQS=1` before running the script, and also updating npm). 
2. Manually do `source "/home/gui/.shopify-app-cli/shopify.sh"` because my ~/.bashrc didn't enter the "if" that was appended at its end for some unknown reason. The if is like this: `if [[ -f "/home/gui/.shopify-app-cli/shopify.sh"  ]] && [[ hB == *i* ]]; then`. 
3. Create new node app with the `shopify` CLI and link it to a dev store.
4. Try to populate it.

## Reduced test case

?

## Specifications

- App type: custom development app for testing before launch
- Operating System: Linux Mint 19.1 Tessa
- Shell: /bin/bash
- Ruby version (ruby -v): using node not ruby. But I get: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]`.

**Comment by andyw8** [comment]
@guillaume-chevalier are you running the command from inside the project's directory? Could you please share the output from `shopify help`?

**Comment by guillaume-chevalier** [comment]
@andyw8 Thanks, I was just not in the good directory. I assumed the shopify-cli was available system-wide rather than on a per-project basis. Closing this issue !

**Comment by andyw8** [comment]
@guillaume-chevalier Ok, good to hear it's solved.

@attaboy @Nupur-Mukherjee This might be an area for improving the interface or messaging.
