### ISSUE TITLE
Inconsistent .env file creation through ensure_env.rb

### ISSUE THREAD

**Issue by erik-shopify** [Shopify/shopify-app-cli#743]
# Issue summary

I'm concerned about the UX for creating an .env file when it's done through `ensure_env.rb` because it's inconsistent with other ways that the .env file is created. For example, when `shopify connect` is run it prompts the user to select from a list of organizations, but when it's done through ensure_env the user must manually input their `api_key`, `api_secret_key`, and `shop_domain` which makes me wonder if it's more difficult for users to use. I think we should instead have `ensure_env.rb` create the env file the same way as `shopify connect`.

This image is when someone runs the `shopify connect` command.
<img width="552" alt="Screen Shot 2020-07-15 at 9 24 50 AM" src="https://user-images.githubusercontent.com/64974039/87570195-0ed0d480-c67d-11ea-8da9-63e29705e381.png">

This image is when `ensure_env.rb` is called to create the env file.
<img width="540" alt="Screen Shot 2020-07-13 at 9 02 58 PM" src="https://user-images.githubusercontent.com/64974039/87385518-172cf080-c553-11ea-9e82-69da67d810d4.png">

**Steps to create a .env file through `ensure_env.rb`**

1. Create a new app
2. Delete the .env file
3. run 'shopify serve'

**Comment by ErinRenNumber1** [comment]
We will implement this to be more consistent with the `connect` command as per discussion [here](https://shopify.slack.com/archives/GQ17PT9EU/p1595512860006300).
