### ISSUE TITLE
Unable to locate package shopify-cli-1.0.1.deb

### ISSUE THREAD

**Issue by jezsung** [Shopify/shopify-app-cli#753]
I can't install the cli through Windows Subsystem for Linux. Looks like it's not available. How do I install it?

![image](https://user-images.githubusercontent.com/45475169/87612972-f4632d80-c746-11ea-909f-6cf4c3b4ebfe.png)

**Comment by mkevinosullivan** [comment]
@jezung Did you download the `.deb` file from https://github.com/Shopify/shopify-app-cli/releases/tag/v1.0.1?

If not, you need to download the file and then run the install command, giving the command the location of the downloaded file.

**Comment by abhiMascotShopify** [comment]
still it is not going to work , why ?

**Comment by andyw8** [comment]
@abhiMascotShopify Can you give some more detail? Are you still seeing an error message?

**Comment by leojeff** [comment]
I've got the same issue on WSL2 Ubuntu 18.04

> 
❯ sudo apt install shopify-cli-1.0.2.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package shopify-cli-1.0.2.deb
E: Couldn't find any package by glob 'shopify-cli-1.0.2.deb'
E: Couldn't find any package by regex 'shopify-cli-1.0.2.deb'

❯ sudo dpkg -i shopify-cli-1.0.2.deb
Selecting previously unselected package shopify-cli.
(Reading database ... 45178 files and directories currently installed.)
Preparing to unpack shopify-cli-1.0.2.deb ...
/var/lib/dpkg/tmp.ci/preinst: 1: /var/lib/dpkg/tmp.ci/preinst: gem: not found
dpkg: error processing archive shopify-cli-1.0.2.deb (--install):
 new shopify-cli package pre-installation script subprocess returned error exit status 127
Errors were encountered while processing:
 shopify-cli-1.0.2.deb

❯ gem -v
3.1.3

**Comment by leojeff** [comment]
I had to replaced gem in preinst with the actual path of my gem ~/.rbenv/shims/gem and rebuild the debian package

**Comment by paulomarg** [comment]
@leojeff, does it work if you try `sudo apt install <path>/shopify-cli-1.0.2.deb`? Some versions of `apt` only attempt to install the local .deb package if you give it a path rather than just the file name.

As for the dpkg attempt, it may be that `gem` isn't set up for your `sudo` environment where apt / dpkg run. Does `sudo gem -v` work for you?

**Comment by leojeff** [comment]
@paulomarg I tried it again and apt was finally able locate the package when I used the full path from root

**Comment by dchavours** [comment]
Why would you guys make it so unfair for windows users? Disapprove.

**Comment by dchavours** [comment]
Poor effort.

**Comment by dchavours** [comment]
Windows > macOS

**Comment by benwainaina** [comment]
Using full path from root seems to work as @paulomarg pointed out.

Just do this in **Ubuntu**

In the folder where you downloaded the **.deb** file, do this:

1. type _pwd_
2. you will get the full path of where you are at the moment.
3. Then copy the path.
4. Now, on the same terminal or a different one do this: **sudo apt install {path you copied in step 3}/name_of_file.deb** and hit enter.
5. Then that is it.

**IF YOU ARE DOING THIS FOR THE FIRST TIME, YOU MAY GET AN ERROR LIKE THIS**

_ERROR: Failed to build gem native extension._
----more errors----
_You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example._

In this case, simply do this:

**sudo apt install ruby-full** and hit enter.

Now repeat step 4 and then hit enter and all should be well now!

Happy coding!

**Comment by vinay-chaturvedi-vajro** [comment]
For all those who still need an answer, just open a new terminal and change directory to the one containing the .deb file and type:
sudo apt install ./shopify-cli-x.y.z.deb

where x,y,z are version details.
Cheers!

**Comment by minhlong** [comment]
> Using full path from root seems to work as @paulomarg pointed out.
> 
> Just do this in **Ubuntu**
> 
> In the folder where you downloaded the **.deb** file, do this:
> 
> 1. type _pwd_
> 2. you will get the full path of where you are at the moment.
> 3. Then copy the path.
> 4. Now, on the same terminal or a different one do this: **sudo apt install {path you copied in step 3}/name_of_file.deb** and hit enter.
> 5. Then that is it.
> 
> **IF YOU ARE DOING THIS FOR THE FIRST TIME, YOU MAY GET AN ERROR LIKE THIS**
> 
> _ERROR: Failed to build gem native extension._
> ----more errors----
> _You might have to install separate package for the ruby development environment, ruby-dev or ruby-devel for example._
> 
> In this case, simply do this:
> 
> **sudo apt install ruby-full** and hit enter.
> 
> Now repeat step 4 and then hit enter and all should be well now!
> 
> Happy coding!

It work with me.

Thank you so much,

**Comment by arielaco** [comment]
The ```ERROR: Failed to build gem native extension.``` was a little misleading for me. I think this should be added to the .deb installation docs.
