### ISSUE TITLE
Highlight need to run `rails webpacker:install` during `shopify create rails`

### ISSUE THREAD

**Issue by mkevinosullivan** [Shopify/shopify-app-cli#766]
Per feedback from #762 

> Missing guidance on webpacker install
> Perhaps the implicit assumption is that the developer has node.js and Yarn installed, but this was another debug flow where some upfront guidance could have been helpful.
> 
> ```
> ✓ Whitelist URLS updated in Partners Dashboard
> ┏━━ Running server... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> ┃ => Booting Puma
> ┃ => Rails 6.0.3.2 application starting in development
> ┃ => Run `rails server --help` for more startup options
> ┃ Exiting
> ┃ /Users/igrigorik/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:95:in `rescue in load': Webpacker configuration file not found /Users/igrigorik/git/vitals/config/webpacker.yml. Please run rails webpacker:install Error: No such file or directory @ rb_sysopen - /Users/igrigorik/git/vitals/config/webpacker.yml (RuntimeError)
> 
> ```
> Heading to Google yielded that I need to install nodejs, Yarn, and then run rails webpacker:install. After all that was done, the app booted successfully. Ideally, the CLI should have interrogated my environment and given me guidance on what is missing and how to install it.

**Comment by tanema** [comment]
This I think is a problem that only exists if the user does not already have node/npm installed. If it is already installed I believe it will happen automatically
]

**Comment by mkevinosullivan** [comment]
PR #815 adds checks for `node` and `yarn` to `shopify create rails`; also, checks if `webpacker:install` ran successfully as part of `rails new` and, if not, tries again before finishing
