### ISSUE TITLE
Add check to see if stored ngrok tunnel is still active or timed-out

### ISSUE THREAD

**Issue by mkevinosullivan** [Shopify/shopify-app-cli#767]
Per feedback from #762 

> ngrok onboarding is nice, but falls down once it times outs
> The bundled ngrok binary is a nice touch and works great on first install, but the experience falls apart once the tunnel times out: the CLI doesn't prompt for ngrok auth on first run and doesn't warn you that the tunnel will timeout; once the tunnel times out there is no liveness check in shopify serve and it keeps pulling the same (dead) persisted (in .env) ngrok url when starting the server. After a bunch of poking around, you finally realize that you have to manually start and stop the tunnel.
> 
> The onboarding is nice, but there should be built-in liveness checks for the tunnel to avoid the above pain.

**Comment by tanema** [comment]
I think @fredriculrich added a change to be able to track this.
