### ISSUE TITLE
Seeing missing activeresource gem after fresh install and update of CLI

### ISSUE THREAD

**Issue by ErinRenNumber1** [Shopify/shopify-app-cli#799]
# Issue summary
The Scripts team is doing end to end testing using CLI to create apps and Scripts.  I did a fresh install of CLI, and saw this error:
<img width="758" alt="Screen Shot 2020-08-05 at 2 18 36 PM" src="https://user-images.githubusercontent.com/39379964/89449820-a16a0e00-d727-11ea-82a8-d23a5ca7fc7d.png">

I think this shouldn't happen?  Everything should just work after an install.  In any case `gem install activeresource` fixed it.

## Specifications

- App type:
- Operating System: macos
- Shell: bash
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

**Comment by paulomarg** [comment]
This error did not come from the CLI `shopify` executable, but rather from the old one from the `shopify_api` gem which actually depends on `activeresource`. That executable was removed on `shopify_api@9.2.0` - we also mention this dependency in the migration docs page, so reinstalling `shopify_api` before installing the new CLI should solve this.
