### ISSUE TITLE
Creating rails app hangs

### ISSUE THREAD

**Issue by ErinRenNumber1** [Shopify/shopify-app-cli#800]
# Issue summary
Tried to create a rails app with SQLite.  The process hung for several minutes without completion:
<img width="1635" alt="Screen Shot 2020-08-05 at 2 36 09 PM" src="https://user-images.githubusercontent.com/39379964/89451220-d7a88d00-d729-11ea-867e-ece75022d5d0.png">

## Specifications

- App type: rails
- Operating System: MacOS
- Shell: bash
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

**Comment by paulomarg** [comment]
It seems that we're failing to detect that a dir already exists when creating a rails project - so there is a conflict (which I believe leads to a prompt that we're omitting) and it leads to the hanging effect.

I'll fix this by making sure we don't even get started if the dir already exists.
