### ISSUE TITLE
Can't upgrade shopify version from 1.0.2 to 1.0.4

### ISSUE THREAD

**Issue by erik-shopify** [Shopify/shopify-app-cli#801]
# Issue summary

`shopify version` prints 1.0.2 but I want it to be 1.0.4, so I followed the guide [here](https://shopify.github.io/shopify-app-cli/getting-started/upgrade/) to do so. After running both commands for macOS (`brew upgrade` and `brew upgrade shopify-cli`) and re-opening the terminal, the version is still 1.0.2.

When I re-run `brew upgrade shopify-cli` I see `Warning: shopify/shopify/shopify-cli 1.0.4 already installed`, but it's not clear to me how to actually change to this version in the case that it is installed. I wonder if the guide should be updated if there is another step after what's listed.

I have also checked all of these files to see if there was anything strange in my shell configuration, but nothing seemed relevant (nothing mentions `shopify`)

<img width="485" alt="Screen Shot 2020-08-05 at 11 58 06 AM" src="https://user-images.githubusercontent.com/64974039/89452810-1a129f80-d713-11ea-980c-2fb705820fc8.png">

## Specifications

- App type: 1.0.2
- Operating System: macOS Catalina 10.15.4
- Shell: mac terminal
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

## Additional Info:

Output of `shopify system all` and `which -a shopify`

<img width="1753" alt="Screen Shot 2020-08-05 at 12 23 20 PM" src="https://user-images.githubusercontent.com/64974039/89455075-9490ee80-d716-11ea-882b-07dd8fcd631e.png">

Running `ls -la /usr/local/bin/shopify` I get `lrwxr-xr-x 1 root admin 74 20 Jul 08:34 /usr/local/bin/shopify -> /Users/erikryhorchuk/.gem/ruby/2.6.3/gems/shopify-cli-1.0.2/bin/shopify.sh`

**Comment by tanema** [comment]
try `which shopify` to make sure which version you are calling.

**Comment by mkevinosullivan** [comment]
Hi Erik, it looks like you previously installed the shopify cli using `gem install`?  If using brew, the location of the installation should be `/usr/local/Cellar/shopify-cli/1.0.x/`
From the output you shared, it seems to be installed in your home gem directory `~/.gem/ruby/2.6.3` which would indicate a gem installation.

Can you share the output of `ls -la /usr/local/bin/shopify`? If it's pointing to something like `~/.gem/ruby/2.6.3/gems/shopify-cli-1.0.2/bin/shopify.sh`, then the current installation is from a `gem install`, not a `brew install`

The best course of action would be to:
- Uninstall the gem version, i.e., while in some directory where you have `2.6.3` of the `/opt/rubies` ruby, not the system ruby, run `gem uninstall shopify-cli`
- Then uninstall and install the brew-based version again
