### ISSUE TITLE
shopify create failing to clone repository

### ISSUE THREAD

**Issue by Danny-UKDM** [Shopify/shopify-app-cli#821]
# Issue summary

Using `shopify create node` in BoUoW, after authenticating and syncing with my account, claims to have cloned the template repository but seems to have not.

## Expected behavior

The template repository has been cloned within the directory my BoUoW points at.

## Actual behavior

![image](https://user-images.githubusercontent.com/16237974/90398574-93a27a00-e091-11ea-9e60-ac417788521a.png)

<details>IO:0x00007fffc60a4bf0</details>

## Steps to reproduce the problem

1. Use BoUoW
2. Use the 1.0.4 Shopify CLI Debian package
3. Use latest Node and NPM
4. Run `shopify create node --name=SomeName`, choosing a public application
5. See the clone allegedly complete but no directories created

## Specifications

- App type: Public app
- Operating System: Windows 10 Pro
- Shell: BoUoW
- Ruby version (ruby -v): `ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]`

**Comment by paulomarg** [comment]
Based on the error it looks like the CLI is having trouble writing the git files at the destination. Can you please make sure your user has write permissions to the dir where you're running the CLI?

Also, you mentioned that the git clone claims to have worked, but the progress bar is actually at 0% in the screenshot - did it work on a subsequent run?

**Comment by Danny-UKDM** [comment]
> Based on the error it looks like the CLI is having trouble writing the git files at the destination. Can you please make sure your user has write permissions to the dir where you're running the CLI?

This is being run in a directory where I manage all of my git repositories, certainly no permission issues on the directory.

> Also, you mentioned that the git clone claims to have worked, but the progress bar is actually at 0% in the screenshot - did it work on a subsequent run?

I actually think that's a "percent remaining" rather than a "percent completed", you can see the solid progress bar span across the screen.

**Comment by paulomarg** [comment]
Thanks for the info, we will investigate this!

As for the progress bar, it goes from 0 - 100%, changing colours, so I'd guess the failure is coming up when the CLI attempts to create the repo directory.

**Comment by Danny-UKDM** [comment]
Thanks @paulomarg happy to give further info if needed. There really wasn't much of a hint at exactly what had happened (if anything) so I was at a bit of a loss for what to share as part of this issue.

**Comment by paulomarg** [comment]
Hey @Danny-UKDM! I am digging into this, and I noticed that the error you're seeing is because we're not properly catching the git error output (which seems to be failing in this case). I set up PR #862 to address this by making sure we can see the git error in this scenario.

Unfortunately, it's not very likely that we'll have a new release this week, which would allow us to see the actual error message you're getting. However, if you don't want to wait for one, you can debug this right away by going to that dir and running:

```
git clone --single-branch https://github.com/Shopify/shopify-app-node.git <dir_name_here> --progress
```

That should show us the error message that's being hidden and might enlighten us on how to fix it.

**Comment by paulomarg** [comment]
Also, @rightroad - your case looks similar, but it seems like the git command might be hanging instead of failing. You could also try the command above to see if it gives us any more information.

**Comment by Danny-UKDM** [comment]
Thanks @paulomarg 

After running the clone command you suggested, all seems to be well:
![image](https://user-images.githubusercontent.com/16237974/92008502-2a805f00-ed3f-11ea-884a-a4ae76e07a79.png)

And I can see the directory created with the files I expect.

**Comment by paulomarg** [comment]
Interesting, so the command itself works. And in that case, it is only failing when running within the context of the CLI, so it's likely doing something wrong. I will make sure to ping you as soon as the next release is out and we can retry this.

Just to check off all the boxes, are there any special characters in your app name (other than spaces, letters and numbers)?

**Comment by Danny-UKDM** [comment]
@paulomarg Confirming that I'm using no special characters in the app name. Just something simple like `shopify-test-app`

**Comment by Danny-UKDM** [comment]
> @paulomarg Confirming that I'm using no special characters in the app name. Just something simple like `shopify-test-app`

Unless we consider `-` to be a special character, of course 😅

**Comment by paulomarg** [comment]
No, that would have failed in the last test, so I think we're good 😅

**Comment by paulomarg** [comment]
@Danny-UKDM we've just released version 1.1.2 of the CLI which includes this change. Could you please upgrade your installation and retest?

**Comment by Danny-UKDM** [comment]
@paulomarg confirming that the latest release appears to have solved the issue! 🥇 

![image](https://user-images.githubusercontent.com/16237974/92585886-75452e00-f28d-11ea-8132-8e2049cdda31.png)

**Comment by paulomarg** [comment]
Great to hear the issue is gone! For future reference, if we hit some error like this again we should get a detailed explanation of the error so it should also be easier to solve.
