### ISSUE TITLE
shopify connect doesn't create the .shopify-cli.yml file

### ISSUE THREAD

**Issue by mkevinosullivan** [Shopify/shopify-app-cli#824]
# Issue summary

`shopify connect` doesn't create the `.shopify-cli.yml` file, as stated in its help output:
```
Connect (or re-connect) an existing project to a Shopify partner organization and/or a store. Creates or updates the .env file, and creates the .shopify-cli.yml file.
  Usage: shopify connect
```

## Expected behavior

`shopify connect` is supposed to create/update the `.env` file and create the `.shopify-cli.yml` file.

## Actual behavior

The `.env` file is created but then the CLI aborts with a message saying "not in a Shopify app project" (which is a check for the `.shopify-cli.yml` file!)

## Steps to reproduce the problem

1. Create a shopify app (use `shopify create ...`)
1. Delete or rename the `.env` and `.shopify-cli.yml` files
1. Run `shopify connect`

## Specifications

- App type: Node
- Operating System: Linux
- Shell: Bash
- Ruby version (ruby -v): 2.7.1

**Comment by paulomarg** [comment]
Closing this as it was fixed by #834.
