### ISSUE TITLE
shopify connect prints previous env variables rather than the newly updated ones

### ISSUE THREAD

**Issue by jacobsteves** [Shopify/shopify-app-cli#825]
# Issue summary

When connecting an existing app, `shopify connect` uses the previous env values when informing the user what they selected. However, the values could have changed during the command when `EnsureEnv` is called. 

## Expected behavior

It should print the new env values. 

## Actual behavior

<img width="596" alt="jacobsteves@Jacobs-MBP: ~:src:misc:authoring:aug18 2020-08-18 11-22-57" src="https://user-images.githubusercontent.com/28009669/90543938-61a61c00-e154-11ea-909f-d7bda2e5bbd6.png">

## Steps to reproduce the problem

1. Create a new app
2. run `shopify connect`, choose different values than the ones provided at creation
3. Check output

## Specifications

- App type: Node
- Operating System: MacOS
- Shell: zsh
- Ruby version (ruby -v): 2.6.3

cc @erik-shopify since I think you worked on this and you might know about it?

**Comment by erik-shopify** [comment]
Solved by https://github.com/Shopify/shopify-app-cli/pull/834
