### ISSUE TITLE
How to update OAuth scopes for app that has been created and installed using shopify-app-cli?

### ISSUE THREAD

**Issue by derrickrc** [Shopify/shopify-app-cli#829]
Is it possible to update OAuth scopes for an already-installed app that was created using shopify-app-cli? I know I can manually create my own permission URL and add the scope (and am happy to do that), but I am not sure what the OAuth library is doing in this case and don't want to break anything if I go about it this way. 

I am using the Ruby version, thank you.

**Comment by tanema** [comment]
You will need to re-authenticate with the new scopes to upgrade your users to use that scope. There is no way to automatically upgrade your scoped because youre merchants need to approve your usage of that new scope.

**Comment by derrickrc** [comment]
@tanema  Sorry, I should have clarified - I am still in development mode using ngrok and I am the only user of my app at the moment. Is the right move here still to re-authenticate using a web browser with an updated permission URL that includes the new scope? It won't break anything with my current OAuth access token, etc.? Thank you.

**Comment by tanema** [comment]
You will get a new OAuth access token after you re-auth

**Comment by derrickrc** [comment]
Thank you. Sorry if I'm being slow here, but just to clarify, what do you mean when you say "re-auth"? I just attempted to re-auth my development store using a manually generated permission URL where I updated the URL with my desired scopes: 

https://{my dev store}.myshopify.com/admin/oauth/authorize?client_id={client_id}&scope=write_products,write_orders&redirect_uri={my ngrok url}/auth/shopify/callback

And as I anticipated, something with the library didn't like me doing that and I got this error on the redirect (see attached). FWIW, I am familiar with OAuth2 and have another live app in the app store where I'm using a different OAuth2 library and have coded everything by hand, but this is my first time working on an app that I've created via shopify-app-cli, so I don't know what the omniauth.rb file is doing. How do I get this working with updated scopes? Thank you. 

![Screen Shot 2020-08-19 at 2 21 31 PM](https://user-images.githubusercontent.com/46724607/90691177-c7170d00-e227-11ea-84ee-da20b7eac701.png)

**Comment by derrickrc** [comment]
I've created [issue 92](https://github.com/Shopify/omniauth-shopify-oauth2/issues/92) in that repo asking my question, but if you also know how to resolve this I'd welcome the help. Thank you.
