### ISSUE TITLE
shopify serve command not working

### ISSUE THREAD

**Issue by mbasnillo** [Shopify/shopify-app-cli#849]
# Issue summary

I ran `shopify serve` right after creating a project, and it showed a check for installing ngrok, but came up with an error right after. I previously had ngrok installed via npm globally on my machine, and that doesn't seem to work anymore as well.

## Expected behavior

It should properly start an ngrok server hosting my app.

## Actual behavior

An error message occurs, and the server does not seem to run.

`PS C:\Users\Miles Lawrence\Documents\oms-test> shopify serve
√ Installing ngrok...                                                                                                                                                                      This command ran with ID: 24727
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        27: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/bin/shopify:32:in `<main>'
        26: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        25: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        24: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/bin/shopify:33:in `block in <main>'
        23: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/lib/shopify-cli/core/entry_point.rb:39:in `call'
        22: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/lib/shopify-cli/core/monorail.rb:20:in `log'
        21: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/lib/shopify-cli/core/entry_point.rb:40:in `block in call'
        20: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/lib/shopify-cli/core/executor.rb:15:in `call'
        19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/vendor/deps/cli-ui/lib/cli/ui.rb:172:in `log_output_to'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/lib/shopify-cli/command.rb:25:in `call'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/lib/project_types/node/commands/serve.rb:15:in `call'
         4: from C:/Ruby26-x64/lib/ruby/2.6.0/forwardable.rb:230:in `start'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/lib/shopify-cli/tunnel.rb:66:in `start'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/lib/shopify-cli/tunnel.rb:160:in `start_ngrok'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/lib/shopify-cli/process_supervision.rb:70:in `start'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.1.0/lib/shopify-cli/process_supervision.rb:70:in `spawn': No such file or directory - C:/Users/Miles Lawrence/AppData/Local/shopify/ngrok http -inspect=false -log=stdout -log-level=debug 8081 (Errno::ENOENT)`

Subsequent attempts at running `shopify serve` are met with the same error messages, minus the "√ Installing ngrok..."

## Steps to reproduce the problem

1. Run `shopify create`, then fill out the necessary information. I selected Custom App and chose my dev store.
2. Run `shopify serve` right after

## Reduced test case

N/A

## Specifications

- App type: Custom App
- Operating System: Windows 10
- Shell: Windows PowerShell 5.1.18362.752
- Ruby version (ruby -v): ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32]
- Node version: v12.11.1
- npm version: 6.11.3

Shopify CLI was installed via RubyGems

**Comment by paulomarg** [comment]
It seems that the space in your user name is preventing it from finding the executable. Thank you for the report, we'll look into this.

**Comment by paulomarg** [comment]
We've released version 1.1.1 which should fix this bug. Could you please upgrade your gem and retest?

I've reopened the issue until we can get confirmation that this is no longer failing.

**Comment by mbasnillo** [comment]
Hey there @paulomarg, thanks for getting on this. I've confirmed that shopify serve is now working properly and the issue is fixed. I really appreciate the help!
