### ISSUE TITLE
Make it possible to opt in/out of analytics gathering after the first run

### ISSUE THREAD

**Issue by paulomarg** [Shopify/shopify-app-cli#861]
Currently, when the CLI is run for the first time, it asks if you wish to provide anonymous data. However, if you change your mind after that point there are no means to update your settings.

On initial discussion, a few ideas were surfaced:

1. Add a brand new command that allows one to:
    - Check the current setting
    - Enable / disable it
1. Make the `config` command visible, and add the option of turning analytics on / off using it.
1. Add a new `settings` command that allows one to generically perform the actions from point 1.

**Comment by andyw8** [comment]
I'm trying to imagine a use case where someone would opt out then change their mind...

**Comment by tiffanytse** [comment]
I think this is more for when someone opts in, and then changes their mind @andyw8

**Comment by andyw8** [comment]
Ah, yes that's make more sense.
