### ISSUE TITLE
Shopify form submission is not working as expected

### ISSUE THREAD

**Issue by pramodShehan5** [Shopify/shopify-app-cli#879]
I used below tutorial to create a form.

[https://polaris.shopify.com/components/forms/form#navigation](url)

When I clicked on submit button, it is redirected to [ https://0b7cfcae77bf.ngrok.io/?hmac=dae06163f8b615954d2f088bc96b677b71b17ecaf58a74cabdf5427ae44c2ebd&locale=en&session=5f95713c2a5591322bd0f11e02e8f1a0aea29d6a73bad5e30278fea551dd9a2b&shop=my-pramod-test-app.myshopify.com&timestamp=1600495672 405](url) .

So there is an error called method not allowed (post)

![Screenshot from 2020-09-19 11-40-28](https://user-images.githubusercontent.com/9468378/93660483-05912900-fa6d-11ea-8350-bf30a6220ad9.png)

**Comment by tanema** [comment]
This is not the context to get support for polaris. Please use the forums for this kind of support
