### ISSUE TITLE
Improve support for working a local partners app

### ISSUE THREAD

**Issue by andyw8** [Shopify/shopify-app-cli#880]
# Issue summary

We currently have `partners.shopify.com` hardcoded in several messages, which results in incorrect links when running a development version of the partners app locally.

I'm considering extracting this out, and then changing the behaviour to use the correct hostname.

Any thoughts/concerns? @tanema @paulomarg @mkevinosullivan 

cc @mllemango

**Comment by paulomarg** [comment]
I think that's a good idea, ideally IMHO it should also be tied with the `SHOPIFY_APP_CLI_LOCAL_PARTNERS` env var. 

Perhaps we could expose `PartnersAPI::auth_endpoint` and `endpoint` and hook that into the message, what do you think?
