### ISSUE TITLE
Different behaviours for duplicate new apps/themes

### ISSUE THREAD

**Issue by carmelal** [Shopify/shopify-app-cli#885]
# Issue summary

Currently, there are different behaviours for Rails apps, Node apps, and Themes when making an app with the same name as an existing directory. 

**Rails** - asks for confirmation before overwriting each individual file that is different from the existing one of the same name in the existing directory
**Node** - raises an error, does not clone
**Theme** - raises an error, does not create Theme

Should the behaviour be the same across all project creation? And is raising an error always the way to go (applicable to `pull` command for Themes as well)? @gfscott @jgray7019

**Comment by paulomarg** [comment]
Does it still fail even with https://github.com/Shopify/shopify-app-cli/pull/867?

**Comment by gfscott** [comment]
To me, simply refusing to overwrite an existing directory is acceptable in the case of a name collision. The benefit seems like a dubious convenience at best, while the risk of irretrivable data loss is potentially pretty high.

IMO we should consistently error out and simply tell them to pick a new directory name.

Curious to hear any counter-arguments though!

**Comment by paulomarg** [comment]
I definitely agree - Rails won't really care what is there to begin with so it will try to bootstrap a new project on top of anything that's there, so I'd say the dangers of that outweigh any benefit that re-creating the project might offer.

**Comment by jgray7019** [comment]
I am also in agreement that raising an error seems like the best way to go in this case 👍
