### ISSUE TITLE
koa-session is out of date in CLI generated node app

### ISSUE THREAD

**Issue by kanehara** [Shopify/shopify-app-cli#895]
# koa-session is out of date in CLI generated node app

The `koa-session` node module in the CLI generated node app is out of date and breaks cookie based authentication / parsing.  It works fine locally through ngrok for whatever reason but was failing in our deployed staging environment.  None of our session cookies and most importantly the `shopOrigin` cookie were being set after the oauth flow.  We were scratching our heads trying to figure this out and tried tweaking various settings from nginx configuration to source code.  We finally noticed that `koa-session` was out of date and updating that immediately fixed the issue.

## Expected behavior

What do you think should happen?
The CLI should generate updated `koa-session` dependency.

## Actual behavior

CLI generates outdated `koa-session` dependency and breaks cookie behavior in deployed environments.

## Steps to reproduce the problem

1. Generate node app with CLI
2. Deploy the app on a web server
3. Configure a sales channel Shopify app with deployed server
4. Try installing the app
5. Cookies are not set
6. Update `koa-session` to latest (6.0.0)
7. Try installing the app again
8. Cookies are set and app works

## Specifications

- Shopify CLI version: 1.2.0
- Node version: v12.16.2

**Comment by paulomarg** [comment]
Thanks for reporting this. We will update that dependency!
