### ISSUE TITLE
Shopify Serve Crashes On Initial Run

### ISSUE THREAD

**Issue by PrateekGoyal18** [Shopify/shopify-app-cli#901]
# Issue summary
When running shopify serve I ran in to this error message.
![image](https://user-images.githubusercontent.com/15648366/95238873-c530f980-0827-11eb-8518-59e76ed7c563.png)

## Expected behavior

What do you think should happen?

It should properly start an ngrok server hosting my app.

## Actual behavior

What actually happens?

ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32]

C:\Users\akhil>cd load

C:\Users\akhil\load>shopify serve
This command ran with ID: 31807
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        27: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/bin/shopify:32:in `<main>'
        26: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        25: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        24: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/bin/shopify:33:in `block in <main>'
        23: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/lib/shopify-cli/core/entry_point.rb:42:in `call'
        22: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/lib/shopify-cli/core/monorail.rb:20:in `log'
        21: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
        20: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/lib/shopify-cli/core/executor.rb:15:in `call'
        19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/vendor/deps/cli-ui/lib/cli/ui.rb:172:in `log_output_to'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/lib/shopify-cli/command.rb:25:in `call'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/lib/project_types/node/commands/serve.rb:15:in `call'
         4: from C:/Ruby26-x64/lib/ruby/2.6.0/forwardable.rb:230:in `start'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/lib/shopify-cli/tunnel.rb:66:in `start'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/lib/shopify-cli/tunnel.rb:162:in `start_ngrok'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/lib/shopify-cli/process_supervision.rb:70:in `start'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-1.3.0/lib/shopify-cli/process_supervision.rb:70:in `spawn': Exec format error - "C:/Users/akhil/AppData/Local/shopify/ngrok" http -inspect=false -log=stdout -log-level=debug 8081 (Errno::ENOEXEC)

## Steps to reproduce the problem

1.Install app once
2. Create a new project in the CLI
3. Run serve

**Comment by mkevinosullivan** [comment]
Hi, do you mind running `shopify system all` from inside your project folder, please?

That command should be attempting to run `ngrok.exe` on Windows, not just `ngrok`.  Can you confirm that there's an `ngrok.exe` in `C:/Users/akhil/AppData/Local/shopify/`, please?

**Comment by PrateekGoyal18** [comment]
Yes, It's there
![image](https://user-images.githubusercontent.com/15648366/95299375-3e1d6900-089b-11eb-9158-f7b6f9f5d347.png)

**Comment by mkevinosullivan** [comment]
What the output of running `ngrok` manually?
```
C:\Users\akhil\load> ..\AppData\Local\shopify\ngrok http 80
```

**Comment by PrateekGoyal18** [comment]
Thanks @mkevinosullivan , solved the issue by installing it with npm.

**Comment by mkevinosullivan** [comment]
Hi Prateek, when you say "installing it with npm", do you mean `ngrok`?

**Comment by Tejinder-22** [comment]
hi @mkevinosullivan  please resinstal ngroak 
2> reset token 
3> go to C:/Users/akhil/AppData/Local/shopify
4> replace ngroak.exe with your downloaded ngroak.exe rrecently in downloads
