### ISSUE TITLE
bash: shopify: command not found, after installing

### ISSUE THREAD

**Issue by Roaldkamman** [Shopify/shopify-app-cli#908]
Hey guys thanks for checking this out! I'm a relatively fresh web developer just finished learning React and I love Shopify. I want to make this my long term niche and I want to challenge myself by creating a Shopify app. But I ran into this issue. Hope we can get it fixed soon.

# Issue summary

After running: $ gem install shopify-cli, and: $ gem install shopify_api 
And then running: shopify version, or: shopify -v: or shopify help

I get: bash: shopify: command not found

## Expected behavior

Expected to return installed version number or output of help command.

## Actual behavior

I get: bash: shopify: command not found

`<details>bash: shopify: command not found</details>` 

## Steps to reproduce the problem

1. run install 
1. check the version

## Reduced test case

This section does not apply since it's within the CL and I can't easily sim my OS specific to my personal dev environment. 

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases). 

## Specifications

- App type: Shopify CLI 
- Operating System: Windows 10
- Shell: bash
- Ruby version (ruby -v): ruby 2.7.2p137

Any help appreciated! I'm really looking forward to work on my app idea for Shopify :)

**Comment by mllemango** [comment]
Hey @Roaldkamman! 
Did you run 
```
$ brew tap shopify/shopify
$ brew install shopify-cli
```
as well? ([from this here documentation](https://shopify.github.io/shopify-app-cli/getting-started/install/))

**Comment by Roaldkamman** [comment]
Hello @mllemango. 

I'm using Windows10 OS, I believe brew is for Mac OS according to the link you posted, right?

**Comment by mllemango** [comment]
My bad. Let me try and reproduce the error on my windows machine. In the meantime, does restarting bash help?

**Comment by Roaldkamman** [comment]
That's alright, I restarted my bash but shopify version producer the same error. I will try restarting my entire machine to see if that helps.

**Comment by Roaldkamman** [comment]
Restarting didn't do anything either.

**Comment by Roaldkamman** [comment]
Yes, here you go: 

$ gem list shopify-cli

*** LOCAL GEMS ***

shopify-cli (1.3.1)

$ gem list shopify_api

*** LOCAL GEMS ***

shopify_api (9.2.0)

$ echo $PATH
/mingw64/bin:/usr/bin:/c/Users/rjkam/bin:/c/Python39/Scripts:/c/Python39:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/c/ProgramData/chocolatey/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/cmd:/c/Program Files (x86)/Yarn/bin:/c/Program Files/nodejs:/c/Ruby27-x64/bin:/c/Users/rjkam/AppData/Local/Microsoft/WindowsApps:/c/Users/rjkam/AppData/Local/GitHubDesktop/bin:/c/Users/rjkam/AppData/Local/Programs/Microsoft VS Code/bin:/c/tools/dart-sdk/bin:/c/Users/rjkam/AppData/Roaming/Pub/Cache/bin:/c/Users/rjkam/AppData/Local/Microsoft/WindowsApps:/c/Users/rjkam/AppData/Local/Yarn/bin:/c/Program Files/heroku/bin:/c/Users/rjkam/AppData/Roaming/npm

**Comment by Roaldkamman** [comment]
I just used the Windows command prompt and the commands: shopify version, and shopify help work there. I was previously using the bash terminal in VSCode. 

But now my terminal in VSCode is not responsive to shopify-cli commands that I will need to run to build and develop my app. I'm not sure what to do.

**Comment by Roaldkamman** [comment]
I changed my default shell in VSCode to powershell instead of bash and that seems to fix it for me. Too bad I like bash but I can do without. 

Do you want to keep pursuing a fix for this bash incompatibility issue? I'm happy to help. 

Otherwise, this might come up again in the future.

**Comment by mllemango** [comment]
Hey! So the hypothesis for why it's not working is this: windows is able to run `shopify` because it goes through many types of file extensions, including our file extension `.bat`. It might be that bash or vscode skips this kind of behaviour resulting in the error/

Try running `$ shopify.bat version` and see if it works!

If so, you could always set an alias to call `shopify.bat` everytime you enter `shopify` instead! 

(Big thanks to @paulomarg)

**Comment by kk-007** [comment]
When I tried to run command:
shopify create

received this error:
 shopify create was not found

**Comment by ankitvyas13** [comment]
You can try _shopify.bat version_ command.

**Comment by SplinterDev** [comment]
> Hey! So the hypothesis for why it's not working is this: windows is able to run `shopify` because it goes through many types of file extensions, including our file extension `.bat`. It might be that bash or vscode skips this kind of behaviour resulting in the error/
> 
> Try running `$ shopify.bat version` and see if it works!
> 
> If so, you could always set an alias to call `shopify.bat` everytime you enter `shopify` instead!
> 
> (Big thanks to @paulomarg)

For more people having the bash issue, you can create an alias with `alias shopify="shopify.bat"`, and that alias will be valid only for the current session. To make it persistent, add the alias line to the `.bashrc` file. So:

1. `code ~/.bashrc` (I'm using vscode to edit the file here)
1. add `alias shopify="shopify.bat"` to the file and save it
1. open a new bash terminal and test it with `shopify version`

**Comment by Jtzuya** [comment]
Hey guys, I was having the same issues.  I use mac m1

This will show when I download using "brew install shopify-cli"

fatal: Could not resolve HEAD to a revision
Warning: No available formula with the name "ruby" (dependency of shopify/shopify/shopify-cli).
==> Searching for similarly named formulae...
These similarly named formulae were found:
homebrew/portable-ruby/portable-libyaml ✔
homebrew/portable-ruby/portable-ncurses
homebrew/portable-ruby/portable-openssl
homebrew/portable-ruby/portable-readline
homebrew/portable-ruby/portable-ruby
homebrew/portable-ruby/portable-zlib
shopify/shopify/shopify-ruby
To install one of them, run (for example):
  brew install homebrew/portable-ruby/portable-libyaml ✔
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

While nothing happens if I do "brew tap shopify/shopify"

I tried installing "gem install shopify-cli" and it seems that I have it. I saw "shopify-cli" when I export it to home. But when I check shopify version "command not found: shopify"  pops out

I don't know if this corrupts my system. Thank you for future response :)

**Comment by therbta** [comment]
> Hey guys, I was having the same issues. I use mac m1
> 
> This will show when I download using "brew install shopify-cli"
> 
> fatal: Could not resolve HEAD to a revision Warning: No available formula with the name "ruby" (dependency of shopify/shopify/shopify-cli). ==> Searching for similarly named formulae... These similarly named formulae were found: homebrew/portable-ruby/portable-libyaml ✔ homebrew/portable-ruby/portable-ncurses homebrew/portable-ruby/portable-openssl homebrew/portable-ruby/portable-readline homebrew/portable-ruby/portable-ruby homebrew/portable-ruby/portable-zlib shopify/shopify/shopify-ruby To install one of them, run (for example): brew install homebrew/portable-ruby/portable-libyaml ✔ ==> Searching for a previously deleted formula (in the last month)... Error: No previously deleted formula found. ==> Searching taps on GitHub... Error: No formulae found in taps.
> 
> While nothing happens if I do "brew tap shopify/shopify"
> 
> I tried installing "gem install shopify-cli" and it seems that I have it. I saw "shopify-cli" when I export it to home. But when I check shopify version "command not found: shopify" pops out
> 
> I don't know if this corrupts my system. Thank you for future response :)

Same error here.

**Comment by MehediHasan06** [comment]
Hi @mllemango,
I'm using linux mint and I've installed shopify properly. After installing it, I've got this when trying to check the version.
```
➜  ~ shopify version             
zsh: command not found: shopify
```
Can you indicate what's the problem here?

**Comment by georgegoldman** [comment]
hi

**Comment by georgegoldman** [comment]
it does not work...

**Comment by akgaurav88** [comment]
Using Shopify create command I get Shopify create was not found

**Comment by jashpatel1306** [comment]
Shopify CLI version 3 is not properly working. 

When I tried to run the command:
npm run dev -- --reset

received this error:
ngrok not stated.

https://share.vidyard.com/watch/ZjPBQhmHjKXJtEAqdsBxs5?
