### ISSUE TITLE
This command ran with ID: 50587 | invalid (ShopifyCli::OAuth::Error)

### ISSUE THREAD

**Issue by KalpitShah** [Shopify/shopify-app-cli#970]
# Issue summary

Write a short description of the issue here ↓
<details>
This command ran with ID: 50587
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        43: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/bin/shopify:32:in `<main>'
        42: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        41: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        40: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/bin/shopify:33:in `block in <main>'
        39: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/core/entry_point.rb:42:in `call'
        38: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/core/monorail.rb:20:in `log'
        37: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/core/executor.rb:15:in `call'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-ui/lib/cli/ui.rb:172:in `log_output_to'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/commands/create.rb:8:in `call'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/command.rb:19:in `call'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/sub_command.rb:12:in `call'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/project_types/node/commands/create.rb:16:in `call'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/form.rb:13:in `ask'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/project_types/node/forms/create.rb:13:in `ask'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/task.rb:7:in `call'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/tasks/select_org_and_shop.rb:11:in `call'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/tasks/select_org_and_shop.rb:38:in `get_organization'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/tasks/select_org_and_shop.rb:27:in `organizations'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api/organizations.rb:6:in `fetch_all'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api.rb:48:in `query'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api.rb:56:in `authenticated_req'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api.rb:49:in `block in query'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api.rb:67:in `api_client'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api.rb:73:in `access_token'
         6: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `get'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/db.rb:87:in `get'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api.rb:74:in `block in access_token'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api.rb:86:in `authenticate'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/oauth.rb:43:in `authenticate'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/oauth.rb:148:in `request_exchange_token'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/oauth.rb:169:in `post_token_request': Invalid 'subject_token' value: invalid (ShopifyCli::OAuth::Error)
</details>

## Expected behavior

What do you think should happen?

-> It should authenticate and should create node app.

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

-> Gives an error which I have pasted above.

## Steps to reproduce the problem

1. Use command "shopify create node"
2. Enter name for the app
3. Then we have to authenticate using the link and this error comes after I try to authenticate.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: Custom Node App
- Operating System: Windows 10
- Shell: CMD
- Ruby version (ruby -v): ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]

**Comment by paulomarg** [comment]
Hi @KalpitShah, thanks for reporting this. Just a few follow-up questions:

- Did the authentication go as expected, or did you have some problems authenticating?
- Is the `LOCALAPPDATA` environment variable set for you? If so, can you read / write file `.db.pstore` inside that folder?

**Comment by KalpitShah** [comment]
Hey @paulomarg, thanks for looking into it but actually the problem has been solved. I created a new shopify account and then went through the process that I have mentioned in the issue and it worked perfectly. So, I am closing this.
Thanks again!
