### ISSUE TITLE
Issues with app cli cmd navigation during select development store

### ISSUE THREAD

**Issue by ResonanceXS** [Shopify/shopify-app-cli#971]
# Issue summary

When I am at this part of the app cli and I try to navigate with k and j or f it would just "enter" 
choosing public and custom still works fine

Partner organization ---
? Select a development store (Navigate up with 'k' and down with 'j', press Enter to select, filter with 'f')
> 1.  --.myshopify.com
  2.  --.myshopify.com
  3.  ---.myshopify.com
  4.  ---.myshopify.com
  5.  ---.myshopify.com
  6.  ---.myshopify.com
  7.  ---.myshopify.com
  8.  ---.myshopify.com
  9.  ----.myshopify.com

## Expected behavior

Move to the options that you want with k, j or f

## Actual behavior

Just download the app

## Specifications

Windows cmd

**Comment by paulomarg** [comment]
Thanks for reporting this, we will look into it!
