### ISSUE TITLE
URL is not defined

### ISSUE THREAD

**Issue by GZ2829** [Shopify/shopify-app-cli#977]
# Issue summary

Write a short description of the issue here ↓

Downloaded CLI today. When running shopify serve, the build fails; stating a reference error the URL is not defined. Attempting to go to the link shows ngrok's "Failed to complete tunnel connection" page. The url generated from the CLI matches the one within the app settings. Ngrok auth token also matches with one on the system (no add ngrok auth token message).  

<img width="567" alt="Screen Shot 2020-11-14 at 4 53 47 PM" src="https://user-images.githubusercontent.com/35677098/99158621-50f53b80-269a-11eb-8414-4ad59d9fcd04.png">

## Expected behavior

What do you think should happen?

Run Serve without error, complete tunnel

## Actual behavior

What actually happens?

URL works properly and installs app on dev store.

## Steps to reproduce the problem

1. Shopify create - Node.js-Public
1. cd into app
1. Shopify Serve - generate ngrok url, accept yes for update.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: Public/Node.js: v8.11.1 npm: 6.14.8
- Operating System: MacOS
- Shell:
- Ruby version (ruby -v):

**Comment by paulomarg** [comment]
It seems that this is happening because of your node version (8). You can use version 10 or later to run the app, would it be possible for you to upgrade?

**Comment by GZ2829** [comment]
Excellent. that worked; this can be closed.
