### ISSUE TITLE
Local Image does not appear when using as src for img component and throws an error

### ISSUE THREAD

**Issue by hotmailbelike** [Shopify/shopify-app-cli#982]
# Issue summary

How do I use local image files in my app?
Because I can't seem to use it in my code.
Here is portion of my files structure:
![image](https://user-images.githubusercontent.com/25118296/99970866-a16d4700-2dc6-11eb-9008-53a171b2cd66.png)

I want to access the 'tile-icon-1.png' image in my Sidebar.js component.
But when I do use it in an img component like this:
`<img
            style={{ width: 35, height: 35 }}
            src="../../img/tile-icon-1.png"
            alt=""
          />`

I get an error: GET https://ca24cb067adf.ngrok.io/img/tile-icon-1.png 404
Screenshot:
![image](https://user-images.githubusercontent.com/25118296/99971308-2d7f6e80-2dc7-11eb-8fc7-095e0e6e8fb4.png)

## Expected behavior

The image should have appeared on my Sidebar.js component

## Actual behavior

The image does not appear and I see an error in the browser console:
![image](https://user-images.githubusercontent.com/25118296/99971308-2d7f6e80-2dc7-11eb-8fc7-095e0e6e8fb4.png)

Please help me resolve this.

**Comment by tanema** [comment]
This is not an issue with the CLI. Please use the forums for support like this. I believe you need to look into next.js public file serving https://nextjs.org/docs/basic-features/static-file-serving

**Comment by hotmailbelike** [comment]
Thanks
