### ISSUE TITLE
Safari blocking embedded app because of 3rd party cookies

### ISSUE THREAD

**Issue by chris8447** [Shopify/shopify-app-cli#990]
### Background
In a recent release Safari is now blocking 3rd party cookies by default. This highly affects all embedded apps through the Shopify Admin. I started a [thread](https://community.shopify.com/c/Shopify-APIs-SDKs/Embedded-App-blocked-by-3rd-party-cookie-policy-of-Safari/m-p/963428#M59146%3Futm_source=communitymembers&utm_medium=email&utm_campaign=immediate_general) in the Shopify forum and one of their staff explained that this will also become true for Chrome and Firefox in the future.

### Problem
Although I could just tell my app users (shop owners) to use Chrome for now to use the app the storefront is also affected. I am using a script tag to inject piece of code on the cart page. For some reason (I guess it's related to the cookie-block) the script is not loaded in Safari but is in Chrome. Please see the pictures:

**Chrome (script tag working)**
![Screenshot 2020-11-25 at 13 14 45](https://user-images.githubusercontent.com/36084535/100226676-59623780-2f20-11eb-8cf0-2ac8f9c28193.png)

**Safari (script tag not working)**
![Screenshot 2020-11-25 at 13 15 39](https://user-images.githubusercontent.com/36084535/100226686-5bc49180-2f20-11eb-96fd-4757a150cee3.png)

In Safari the script tag call is redirected to the "/auth" endpoint. That's probably because no cookies can be found to check the identity.

### Solution
Shopify's solution is to replace the old way of authenticating (cookies) with a new way which is not relying on cookies. Instead session tokens are generated and sent within the "Authorization" header of each request.

There are some tutorials from Shopify to show how its done, but for me they are not helpful.

- https://shopify.dev/tutorials/authenticate-your-app-using-session-tokens
- https://shopify.dev/tutorials/authenticate-server-side-rendered-apps-with-session-tokens-app-bridge-turbolinks

Has anyone done this before and can give some tips?

**Comment by tanema** [comment]
> Has anyone done this before and can give some tips?

If you are looking for discourse, please bring it to the forums instead. As I see that you are aware of our efforts to start migrating our authentication methods because of tighter cookie restrictions, I am going to close this issue. Thank you for your well documented issue
